libzmq: zmq::zmq_init_t Class Reference
zmq::zmq_init_t Class Reference
#include <zmq_init.hpp>
Public Member Functions
zmq_init_t (class io_thread_t *io_thread_, class socket_base_t *socket_, class session_t *session_, fd_t fd_, const options_t &options_)
~zmq_init_t ()
ctx_t * get_ctx ()
uint32_t get_tid ()
void inc_seqnum ()
void process_command (struct command_t &cmd_)
void register_term_acks (int count_)
void unregister_term_ack ()
Protected Member Functions
class io_thread_t * choose_io_thread (uint64_t affinity_)
void destroy_socket (class socket_base_t *socket_)
struct endpoint_t find_endpoint (const char *addr_)
void launch_child (own_t *object_)
void launch_sibling (own_t *object_)
void log (const char *format_,...)
virtual void process_activate_reader ()
virtual void process_activate_writer (uint64_t msgs_read_)
virtual void process_attach (struct i_engine *engine_, const blob_t &peer_identity_)
virtual void process_bind (class reader_t *in_pipe_, class writer_t *out_pipe_, const blob_t &peer_identity_)
virtual void process_destroy ()
virtual void process_pipe_term ()
virtual void process_pipe_term_ack ()
virtual void process_reap (class socket_base_t *socket_)
virtual void process_reaped ()
virtual void process_stop ()
void process_term (int linger_)
int register_endpoint (const char *addr_, struct endpoint_t &endpoint_)
void send_activate_reader (class reader_t *destination_)
void send_activate_writer (class writer_t *destination_, uint64_t msgs_read_)
void send_attach (class session_t *destination_, struct i_engine *engine_, const blob_t &peer_identity_, bool inc_seqnum_=true)
void send_bind (class own_t *destination_, class reader_t *in_pipe_, class writer_t *out_pipe_, const blob_t &peer_identity_, bool inc_seqnum_=true)
void send_done ()
void send_own (class own_t *destination_, class own_t *object_)
void send_pipe_term (class writer_t *destination_)
void send_pipe_term_ack (class reader_t *destination_)
void send_plug (class own_t *destination_, bool inc_seqnum_=true)
void send_reap (class socket_base_t *socket_)
void send_reaped ()
void send_stop ()
void send_term (class own_t *destination_, int linger_)
void send_term_ack (class own_t *destination_)
void send_term_req (class own_t *destination_, class own_t *object_)
void terminate ()
void unregister_endpoints (class socket_base_t *socket_)
Protected Attributes
options_t options
Private Types
enum prop_t { prop_type = 1, prop_identity = 2 }
typedef std::vector< msg_t > to_send_t
Private Member Functions
zmq_init_t (const zmq_init_t &)
void detach ()
void dispatch_engine ()
void finalise_initialisation ()
void flush ()
const zmq_init_t & operator= (const zmq_init_t &)
void process_plug ()
void process_unplug ()
bool read (class msg_t *msg_)
bool write (class msg_t *msg_)
Private Attributes
i_engine * engine
i_engine * ephemeral_engine
class io_thread_t * io_thread
blob_t peer_identity
bool received
class session_t * session
class socket_base_t * socket
to_send_t to_send
Detailed Description
Definition at line 39 of file zmq_init.hpp.
Member Typedef Documentation
typedef std::vector<msg_t> zmq::zmq_init_t::to_send_t [private]
Definition at line 77 of file zmq_init.hpp.
Member Enumeration Documentation
enum zmq::zmq_init_t::prop_t [private]
Enumerator:
prop_type
prop_identity
Definition at line 50 of file zmq_init.hpp.
        {
            prop_type = 1,
            prop_identity = 2
        };
Constructor & Destructor Documentation
zmq::zmq_init_t::zmq_init_t (class io_thread_t * io_thread_, class socket_base_t * socket_, class session_t * session_, fd_t fd_, const options_t & options_)
Definition at line 35 of file zmq_init.cpp.
References alloc_assert, zmq::msg_t::data, engine, errno_assert, zmq::generate_uuid(), zmq::options_t::identity, zmq::msg_t::init_size(), zmq::msg_t::more, zmq::own_t::options, peer_identity, prop_identity, prop_type, zmq::put_uint16(), zmq::msg_t::set_flags(), to_send, and zmq::options_t::type.
                                 :
    own_t (io_thread_, options_),
    ephemeral_engine (NULL),
    received (false),
    socket (socket_),
    session (session_),
    io_thread (io_thread_)
{
    //  Create the engine object for this connection.
    engine = new (std::nothrow) zmq_engine_t (fd_, options);
    alloc_assert (engine);
    //  Generate an unique identity.
    peer_identity.resize (17);
    peer_identity [0] = 0;
    generate_uuid (&peer_identity [1]);
    //  Create a list of props to send.
    msg_t msg;
    int rc = msg.init_size (4);
    errno_assert (rc == 0);
    unsigned char *data = (unsigned char*) msg.data ();
    put_uint16 (data, prop_type);
    put_uint16 (data + 2, options.type);
    msg.set_flags (msg_t::more);
    to_send.push_back (msg);
    if (!options.identity.empty ()) {
        rc = msg.init_size (2 + options.identity.size ());
        errno_assert (rc == 0);
        data = (unsigned char*) msg.data ();
        put_uint16 (data, prop_identity);
        memcpy (data + 2, options.identity.data (), options.identity.size ());
        msg.set_flags (msg_t::more);
        to_send.push_back (msg);
    }
    //  Remove the MORE flag from the last prop.
    to_send.back ().reset_flags (msg_t::more);
}
zmq::zmq_init_t::~zmq_init_t ()
Definition at line 78 of file zmq_init.cpp.
References errno_assert.
{
    if (engine)
        engine->terminate ();
    //  If there are unsent props still queued deallocate them.
    for (to_send_t::iterator it = to_send.begin (); it != to_send.end ();
          ++it) {
        int rc = it->close ();
        errno_assert (rc == 0);
    }
    to_send.clear ();
}
zmq::zmq_init_t::zmq_init_t (const zmq_init_t &) [private]
Member Function Documentation
zmq::io_thread_t * zmq::object_t::choose_io_thread (uint64_t affinity_) [protected, inherited]
Definition at line 164 of file object.cpp.
References zmq::object_t::choose_io_thread().
Referenced by zmq::object_t::choose_io_thread().
{
    return ctx->choose_io_thread (affinity_);
}
void zmq::object_t::destroy_socket (class socket_base_t * socket_) [protected, inherited]
Definition at line 151 of file object.cpp.
{
    ctx->destroy_socket (socket_);
}
void zmq::zmq_init_t::detach () [private, virtual]
Implements zmq::i_inout.
Definition at line 159 of file zmq_init.cpp.
{
    //  This function is called by engine when disconnection occurs.
    //  If there is an associated session, send it a null engine to let it know
    //  that connection process was unsuccesful.
    if (session)
        send_attach (session, NULL, blob_t (), true);
    //  The engine will destroy itself, so let's just drop the pointer here and
    //  start termination of the init object.
    engine = NULL;
    terminate ();
}
void zmq::zmq_init_t::dispatch_engine () [private]
Definition at line 197 of file zmq_init.cpp.
References alloc_assert, and zmq_assert.
{
    if (to_send.empty () && received) {
        //  Engine must be detached.
        zmq_assert (!engine);
        zmq_assert (ephemeral_engine);
        //  If we know what session we belong to, it's easy, just send the
        //  engine to that session and destroy the init object. Note that we
        //  know about the session only if this object is owned by it. Thus,
        //  lifetime of this object in contained in the lifetime of the session
        //  so the pointer cannot become invalid without notice.
        if (session) {
            send_attach (session, ephemeral_engine, peer_identity, true);
            terminate ();
            return;
        }
        //  All the cases below are listener-based. Therefore we need the socket
        //  reference so that new sessions can bind to that socket.
        zmq_assert (socket);
        //  We have no associated session. If the peer has no identity we'll
        //  create a transient session for the connection. Note that
        //  seqnum is incremented to account for attach command before the
        //  session is launched. That way we are sure it won't terminate before
        //  being attached.
        if (peer_identity [0] == 0) {
            session = new (std::nothrow) transient_session_t (io_thread,
                socket, options);
            alloc_assert (session);
            session->inc_seqnum ();
            launch_sibling (session);
            send_attach (session, ephemeral_engine, peer_identity, false);
            terminate ();
            return;
        }
        //  Try to find the session corresponding to the peer's identity.
        //  If found, send the engine to that session and destroy this object.
        //  Note that session's seqnum is incremented by find_session rather
        //  than by send_attach.
        session = socket->find_session (peer_identity);
        if (session) {
            send_attach (session, ephemeral_engine, peer_identity, false);
            terminate ();
            return;
        }
        //  There's no such named session. We have to create one. Note that
        //  seqnum is incremented to account for attach command before the
        //  session is launched. That way we are sure it won't terminate before
        //  being attached.
        session = new (std::nothrow) named_session_t (io_thread, socket,
            options, peer_identity);
        alloc_assert (session);
        session->inc_seqnum ();
        launch_sibling (session);
        send_attach (session, ephemeral_engine, peer_identity, false);
        terminate ();
        return;
    }
}
void zmq::zmq_init_t::finalise_initialisation () [private]
Definition at line 186 of file zmq_init.cpp.
{
     //  Unplug and prepare to dispatch engine.
     if (to_send.empty () && received) {
        ephemeral_engine = engine;
        engine = NULL;
        ephemeral_engine->unplug ();
        return;
    }
}
zmq::endpoint_t zmq::object_t::find_endpoint (const char * addr_) [read, protected, inherited]
Definition at line 146 of file object.cpp.
{
    return ctx->find_endpoint (addr_);
}
void zmq::zmq_init_t::flush () [private, virtual]
Implements zmq::i_inout.
Definition at line 148 of file zmq_init.cpp.
{
    //  Check if there's anything to flush.
    if (!received)
        return;
    //  Initialization is done, dispatch engine.
    if (ephemeral_engine)
        dispatch_engine ();
}
zmq::ctx_t * zmq::object_t::get_ctx () [inherited]
Definition at line 53 of file object.cpp.
{
    return ctx;
}
uint32_t zmq::object_t::get_tid () [inherited]
Definition at line 48 of file object.cpp.
Referenced by zmq::ctx_t::destroy_socket(), and zmq::object_t::send_command().
{
    return tid;
}
void zmq::own_t::inc_seqnum () [inherited]
Definition at line 56 of file own.cpp.
Referenced by zmq::ctx_t::find_endpoint(), zmq::socket_base_t::find_session(), zmq::object_t::send_attach(), zmq::object_t::send_bind(), zmq::object_t::send_own(), and zmq::object_t::send_plug().
{
    //  This function may be called from a different thread!
    sent_seqnum.add (1);
}
void zmq::own_t::launch_child (own_t * object_) [protected, inherited]
Definition at line 71 of file own.cpp.
References zmq::own_t::set_owner().
{
    //  Specify the owner of the object.
    object_->set_owner (this);
    //  Plug the object into the I/O thread.
    send_plug (object_);
    //  Take ownership of the object.
    send_own (this, object_);
}
void zmq::own_t::launch_sibling (own_t * object_) [protected, inherited]
Definition at line 83 of file own.cpp.
References zmq::own_t::set_owner().
{
    //  At this point it is important that object is plugged in before its
    //  owner has a chance to terminate it. Thus, 'plug' command is sent before
    //  the 'own' command. Given that the mailbox preserves ordering of
    //  commands, 'term' command from the owner cannot make it to the object
    //  before the already written 'plug' command.
    //  Specify the owner of the object.
    object_->set_owner (owner);
    //  Plug the object into its I/O thread.
    send_plug (object_);
    //  Make parent own the object.
    send_own (owner, object_);
}
void zmq::object_t::log (const char * format_, ...) [protected, inherited]
Definition at line 156 of file object.cpp.
{
    va_list args;
    va_start (args, format_);
    ctx->log (format_, args);
    va_end (args);
}
const zmq_init_t& zmq::zmq_init_t::operator= (const zmq_init_t &) [private]
void zmq::object_t::process_activate_reader () [protected, virtual, inherited]
Reimplemented in zmq::reader_t.
Definition at line 413 of file object.cpp.
References zmq_assert.
{
    zmq_assert (false);
}
void zmq::object_t::process_activate_writer (uint64_t msgs_read_) [protected, virtual, inherited]
Reimplemented in zmq::writer_t.
Definition at line 418 of file object.cpp.
References zmq_assert.
{
    zmq_assert (false);
}
void zmq::object_t::process_attach (struct i_engine * engine_, const blob_t & peer_identity_) [protected, virtual, inherited]
Reimplemented in zmq::session_t.
Definition at line 401 of file object.cpp.
References zmq_assert.
{
    zmq_assert (false);
}
void zmq::object_t::process_bind (class reader_t * in_pipe_, class writer_t * out_pipe_, const blob_t & peer_identity_) [protected, virtual, inherited]
Reimplemented in zmq::socket_base_t.
Definition at line 407 of file object.cpp.
References zmq_assert.
{
    zmq_assert (false);
}
void zmq::object_t::process_command (struct command_t & cmd_) [inherited]
Definition at line 58 of file object.cpp.
References zmq::command_t::activate_reader, zmq::command_t::activate_writer, zmq::command_t::args, zmq::command_t::attach, zmq::command_t::bind, zmq::deallocate_command(), zmq::command_t::own, zmq::command_t::pipe_term, zmq::command_t::pipe_term_ack, zmq::command_t::plug, zmq::command_t::reap, zmq::command_t::reaped, zmq::command_t::stop, zmq::command_t::term, zmq::command_t::term_ack, zmq::command_t::term_req, zmq::command_t::type, and zmq_assert.
Referenced by zmq::reaper_t::in_event(), zmq::io_thread_t::in_event(), and zmq::socket_base_t::process_commands().
{
    switch (cmd_.type) {
    case command_t::activate_reader:
        process_activate_reader ();
        break;
    case command_t::activate_writer:
        process_activate_writer (cmd_.args.activate_writer.msgs_read);
        break;
    case command_t::stop:
        process_stop ();
        break;
    case command_t::plug:
        process_plug ();
        process_seqnum ();
        return;
    case command_t::own:
        process_own (cmd_.args.own.object);
        process_seqnum ();
        break;
    case command_t::attach:
        process_attach (cmd_.args.attach.engine,
            cmd_.args.attach.peer_identity ?
            blob_t (cmd_.args.attach.peer_identity,
            cmd_.args.attach.peer_identity_size) : blob_t ());
        process_seqnum ();
        break;
    case command_t::bind:
        process_bind (cmd_.args.bind.in_pipe, cmd_.args.bind.out_pipe,
            cmd_.args.bind.peer_identity ? blob_t (cmd_.args.bind.peer_identity,
            cmd_.args.bind.peer_identity_size) : blob_t ());
        process_seqnum ();
        break;
    case command_t::pipe_term:
        process_pipe_term ();
        return;
    case command_t::pipe_term_ack:
        process_pipe_term_ack ();
        break;
    case command_t::term_req:
        process_term_req (cmd_.args.term_req.object);
        break;
    case command_t::term:
        process_term (cmd_.args.term.linger);
        break;
    case command_t::term_ack:
        process_term_ack ();
        break;
    case command_t::reap:
        process_reap (cmd_.args.reap.socket);
        break;
    case command_t::reaped:
        process_reaped ();
        break;
    default:
        zmq_assert (false);
    }
    //  The assumption here is that each command is processed once only,
    //  so deallocating it after processing is all right.
    deallocate_command (&cmd_);
}
void zmq::own_t::process_destroy () [protected, virtual, inherited]
Reimplemented in zmq::socket_base_t.
Definition at line 210 of file own.cpp.
Referenced by zmq::socket_base_t::check_destroy().
{
    delete this;
}
void zmq::object_t::process_pipe_term () [protected, virtual, inherited]
Reimplemented in zmq::writer_t.
Definition at line 423 of file object.cpp.
References zmq_assert.
{
    zmq_assert (false);
}
void zmq::object_t::process_pipe_term_ack () [protected, virtual, inherited]
Reimplemented in zmq::reader_t.
Definition at line 428 of file object.cpp.
References zmq_assert.
{
    zmq_assert (false);
}
void zmq::zmq_init_t::process_plug () [private, virtual]
Reimplemented from zmq::object_t.
Definition at line 174 of file zmq_init.cpp.
References zmq_assert.
{
    zmq_assert (engine);
    engine->plug (io_thread, this);
}
void zmq::object_t::process_reap (class socket_base_t * socket_) [protected, virtual, inherited]
Reimplemented in zmq::reaper_t.
Definition at line 448 of file object.cpp.
References zmq_assert.
{
    zmq_assert (false);
}
void zmq::object_t::process_reaped () [protected, virtual, inherited]
Reimplemented in zmq::reaper_t.
Definition at line 453 of file object.cpp.
References zmq_assert.
{
    zmq_assert (false);
}
void zmq::object_t::process_stop () [protected, virtual, inherited]
Reimplemented in zmq::io_thread_t, zmq::reaper_t, and zmq::socket_base_t.
Definition at line 386 of file object.cpp.
References zmq_assert.
{
    zmq_assert (false);
}
void zmq::own_t::process_term (int linger_) [protected, virtual, inherited]
Reimplemented from zmq::object_t.
Reimplemented in zmq::pair_t, zmq::pull_t, zmq::push_t, zmq::session_t, zmq::socket_base_t, zmq::xpub_t, zmq::xrep_t, zmq::xreq_t, zmq::xsub_t, and zmq::zmq_listener_t.
Definition at line 156 of file own.cpp.
References zmq_assert.
Referenced by zmq::session_t::proceed_with_term(), zmq::zmq_listener_t::process_term(), and zmq::socket_base_t::process_term().
{
    //  Double termination should never happen.
    zmq_assert (!terminating);
    //  Send termination request to all owned objects.
    for (owned_t::iterator it = owned.begin (); it != owned.end (); ++it)
        send_term (*it, linger_);
    register_term_acks ((int) owned.size ());
    owned.clear ();
    //  Start termination process and check whether by chance we cannot
    //  terminate immediately.
    terminating = true;
    check_term_acks ();
}
void zmq::zmq_init_t::process_unplug () [private]
Definition at line 180 of file zmq_init.cpp.
{
    if (engine)
        engine->unplug ();
}
bool zmq::zmq_init_t::read (class msg_t * msg_) [private, virtual]
Implements zmq::i_inout.
Definition at line 92 of file zmq_init.cpp.
{
    //  If the identity was already sent, do nothing.
    if (to_send.empty ())
        return false;
    //  Pass next property to the engine.
    *msg_ = to_send.front ();
    to_send.erase (to_send.begin ());
    //  Try finalize initialization.
    finalise_initialisation ();
    return true;
}
int zmq::object_t::register_endpoint (const char * addr_, struct endpoint_t & endpoint_) [protected, inherited]
Definition at line 136 of file object.cpp.
{
    return ctx->register_endpoint (addr_, endpoint_);
}
void zmq::own_t::register_term_acks (int count_) [inherited]
Definition at line 173 of file own.cpp.
{
    term_acks += count_;
}
void zmq::object_t::send_activate_reader (class reader_t * destination_) [protected, inherited]
Definition at line 270 of file object.cpp.
References zmq::command_t::activate_reader, zmq::command_t::destination, and zmq::command_t::type.
{
    command_t cmd;
#if defined ZMQ_MAKE_VALGRIND_HAPPY
    memset (&cmd, 0, sizeof (cmd));
#endif
    cmd.destination = destination_;
    cmd.type = command_t::activate_reader;
    send_command (cmd);
}
void zmq::object_t::send_activate_writer (class writer_t * destination_, uint64_t msgs_read_) [protected, inherited]
Definition at line 281 of file object.cpp.
References zmq::command_t::activate_writer, zmq::command_t::args, zmq::command_t::destination, and zmq::command_t::type.
{
    command_t cmd;
#if defined ZMQ_MAKE_VALGRIND_HAPPY
    memset (&cmd, 0, sizeof (cmd));
#endif
    cmd.destination = destination_;
    cmd.type = command_t::activate_writer;
    cmd.args.activate_writer.msgs_read = msgs_read_;
    send_command (cmd);
}
void zmq::object_t::send_attach (class session_t * destination_, struct i_engine * engine_, const blob_t & peer_identity_, bool inc_seqnum_ = true) [protected, inherited]
Definition at line 209 of file object.cpp.
References alloc_assert, zmq::command_t::args, zmq::command_t::attach, zmq::command_t::destination, zmq::own_t::inc_seqnum(), zmq::command_t::type, and zmq_assert.
{
    if (inc_seqnum_)
        destination_->inc_seqnum ();
    command_t cmd;
#if defined ZMQ_MAKE_VALGRIND_HAPPY
    memset (&cmd, 0, sizeof (cmd));
#endif
    cmd.destination = destination_;
    cmd.type = command_t::attach;
    cmd.args.attach.engine = engine_;
    if (peer_identity_.empty ()) {
        cmd.args.attach.peer_identity_size = 0;
        cmd.args.attach.peer_identity = NULL;
    }
    else {
        zmq_assert (peer_identity_.size () <= 0xff);
        cmd.args.attach.peer_identity_size =
            (unsigned char) peer_identity_.size ();
        cmd.args.attach.peer_identity =
            (unsigned char*) malloc (peer_identity_.size ());
        alloc_assert (cmd.args.attach.peer_identity_size);
        memcpy (cmd.args.attach.peer_identity, peer_identity_.data (),
            peer_identity_.size ());
    }
    send_command (cmd);
}
void zmq::object_t::send_bind (class own_t * destination_, class reader_t * in_pipe_, class writer_t * out_pipe_, const blob_t & peer_identity_, bool inc_seqnum_ = true) [protected, inherited]
Definition at line 239 of file object.cpp.
References alloc_assert, zmq::command_t::args, zmq::command_t::bind, zmq::command_t::destination, zmq::own_t::inc_seqnum(), zmq::command_t::type, and zmq_assert.
{
    if (inc_seqnum_)
        destination_->inc_seqnum ();
    command_t cmd;
#if defined ZMQ_MAKE_VALGRIND_HAPPY
    memset (&cmd, 0, sizeof (cmd));
#endif
    cmd.destination = destination_;
    cmd.type = command_t::bind;
    cmd.args.bind.in_pipe = in_pipe_;
    cmd.args.bind.out_pipe = out_pipe_;
    if (peer_identity_.empty ()) {
        cmd.args.bind.peer_identity_size = 0;
        cmd.args.bind.peer_identity = NULL;
    }
    else {
        zmq_assert (peer_identity_.size () <= 0xff);
        cmd.args.bind.peer_identity_size =
            (unsigned char) peer_identity_.size ();
        cmd.args.bind.peer_identity =
            (unsigned char*) malloc (peer_identity_.size ());
        alloc_assert (cmd.args.bind.peer_identity_size);
        memcpy (cmd.args.bind.peer_identity, peer_identity_.data (),
            peer_identity_.size ());
    }
    send_command (cmd);
}
void zmq::object_t::send_done () [protected, inherited]
Definition at line 375 of file object.cpp.
References zmq::command_t::destination, zmq::command_t::done, zmq::ctx_t::term_tid, and zmq::command_t::type.
{
    command_t cmd;
#if defined ZMQ_MAKE_VALGRIND_HAPPY
    memset (&cmd, 0, sizeof (cmd));
#endif
    cmd.destination = NULL;
    cmd.type = command_t::done;
    ctx->send_command (ctx_t::term_tid, cmd);
}
void zmq::object_t::send_own (class own_t * destination_, class own_t * object_) [protected, inherited]
Definition at line 196 of file object.cpp.
References zmq::command_t::args, zmq::command_t::destination, zmq::own_t::inc_seqnum(), zmq::command_t::own, and zmq::command_t::type.
{
    destination_->inc_seqnum ();
    command_t cmd;
#if defined ZMQ_MAKE_VALGRIND_HAPPY
    memset (&cmd, 0, sizeof (cmd));
#endif
    cmd.destination = destination_;
    cmd.type = command_t::own;
    cmd.args.own.object = object_;
    send_command (cmd);
}
void zmq::object_t::send_pipe_term (class writer_t * destination_) [protected, inherited]
Definition at line 294 of file object.cpp.
References zmq::command_t::destination, zmq::command_t::pipe_term, and zmq::command_t::type.
{
    command_t cmd;
#if defined ZMQ_MAKE_VALGRIND_HAPPY
    memset (&cmd, 0, sizeof (cmd));
#endif
    cmd.destination = destination_;
    cmd.type = command_t::pipe_term;
    send_command (cmd);
}
void zmq::object_t::send_pipe_term_ack (class reader_t * destination_) [protected, inherited]
Definition at line 305 of file object.cpp.
References zmq::command_t::destination, zmq::command_t::pipe_term_ack, and zmq::command_t::type.
{
    command_t cmd;
#if defined ZMQ_MAKE_VALGRIND_HAPPY
    memset (&cmd, 0, sizeof (cmd));
#endif
    cmd.destination = destination_;
    cmd.type = command_t::pipe_term_ack;
    send_command (cmd);
}
void zmq::object_t::send_plug (class own_t * destination_, bool inc_seqnum_ = true) [protected, inherited]
Definition at line 182 of file object.cpp.
References zmq::command_t::destination, zmq::own_t::inc_seqnum(), zmq::command_t::plug, and zmq::command_t::type.
{
    if (inc_seqnum_)
        destination_->inc_seqnum ();
    command_t cmd;
#if defined ZMQ_MAKE_VALGRIND_HAPPY
    memset (&cmd, 0, sizeof (cmd));
#endif
    cmd.destination = destination_;
    cmd.type = command_t::plug;
    send_command (cmd);
}
void zmq::object_t::send_reap (class socket_base_t * socket_) [protected, inherited]
Definition at line 352 of file object.cpp.
References zmq::command_t::args, zmq::command_t::destination, zmq::command_t::reap, and zmq::command_t::type.
{
    command_t cmd;
#if defined ZMQ_MAKE_VALGRIND_HAPPY
    memset (&cmd, 0, sizeof (cmd));
#endif
    cmd.destination = ctx->get_reaper ();
    cmd.type = command_t::reap;
    cmd.args.reap.socket = socket_;
    send_command (cmd);
}
void zmq::object_t::send_reaped () [protected, inherited]
Definition at line 364 of file object.cpp.
References zmq::command_t::destination, zmq::command_t::reaped, and zmq::command_t::type.
{
    command_t cmd;
#if defined ZMQ_MAKE_VALGRIND_HAPPY
    memset (&cmd, 0, sizeof (cmd));
#endif
    cmd.destination = ctx->get_reaper ();
    cmd.type = command_t::reaped;
    send_command (cmd);
}
void zmq::object_t::send_stop () [protected, inherited]
Definition at line 169 of file object.cpp.
References zmq::command_t::destination, zmq::command_t::stop, and zmq::command_t::type.
{
    //  'stop' command goes always from administrative thread to
    //  the current object.
    command_t cmd;
#if defined ZMQ_MAKE_VALGRIND_HAPPY
    memset (&cmd, 0, sizeof (cmd));
#endif
    cmd.destination = this;
    cmd.type = command_t::stop;
    ctx->send_command (tid, cmd);
}
void zmq::object_t::send_term (class own_t * destination_, int linger_) [protected, inherited]
Definition at line 329 of file object.cpp.
References zmq::command_t::args, zmq::command_t::destination, zmq::command_t::term, and zmq::command_t::type.
{
    command_t cmd;
#if defined ZMQ_MAKE_VALGRIND_HAPPY
    memset (&cmd, 0, sizeof (cmd));
#endif
    cmd.destination = destination_;
    cmd.type = command_t::term;
    cmd.args.term.linger = linger_;
    send_command (cmd);
}
void zmq::object_t::send_term_ack (class own_t * destination_) [protected, inherited]
Definition at line 341 of file object.cpp.
References zmq::command_t::destination, zmq::command_t::term_ack, and zmq::command_t::type.
{
    command_t cmd;
#if defined ZMQ_MAKE_VALGRIND_HAPPY
    memset (&cmd, 0, sizeof (cmd));
#endif
    cmd.destination = destination_;
    cmd.type = command_t::term_ack;
    send_command (cmd);
}
void zmq::object_t::send_term_req (class own_t * destination_, class own_t * object_) [protected, inherited]
Definition at line 316 of file object.cpp.
References zmq::command_t::args, zmq::command_t::destination, zmq::command_t::term_req, and zmq::command_t::type.
{
    command_t cmd;
#if defined ZMQ_MAKE_VALGRIND_HAPPY
    memset (&cmd, 0, sizeof (cmd));
#endif
    cmd.destination = destination_;
    cmd.type = command_t::term_req;
    cmd.args.term_req.object = object_;
    send_command (cmd);
}
void zmq::own_t::terminate () [protected, inherited]
Reimplemented in zmq::session_t.
Definition at line 138 of file own.cpp.
Referenced by zmq::reaper_t::process_reap(), and zmq::session_t::terminate().
{
    //  If termination is already underway, there's no point
    //  in starting it anew.
    if (terminating)
        return;
    //  As for the root of the ownership tree, there's noone to terminate it,
    //  so it has to terminate itself.
    if (!owner) {
        process_term (options.linger);
        return;
    }
    //  If I am an owned object, I'll ask my owner to terminate me.
    send_term_req (owner, this);
}
void zmq::object_t::unregister_endpoints (class socket_base_t * socket_) [protected, inherited]
Definition at line 141 of file object.cpp.
{
    return ctx->unregister_endpoints (socket_);
}
void zmq::own_t::unregister_term_ack () [inherited]
Definition at line 178 of file own.cpp.
References zmq_assert.
{
    zmq_assert (term_acks > 0);
    term_acks--;
    //  This may be a last ack we are waiting for before termination...
    check_term_acks ();
}
bool zmq::zmq_init_t::write (class msg_t * msg_) [private, virtual]
Implements zmq::i_inout.
Definition at line 108 of file zmq_init.cpp.
References zmq::msg_t::data, zmq::msg_t::flags, zmq::get_uint16(), zmq::msg_t::more, zmq::msg_t::size, and zmq_assert.
{
    //  If identity was already received, we are not interested
    //  in subsequent messages.
    if (received)
        return false;
    size_t size = msg_->size ();
    unsigned char *data = (unsigned char*) msg_->data ();
    //  There should be at least property type in the message.
    zmq_assert (size >= 2);
    uint16_t prop = get_uint16 (data);
    switch (prop) {
    case prop_type:
        {
            zmq_assert (size == 4);
            //  TODO: Check whether the type is OK.
            //  uint16_t type = get_uint16 (data + 2);
            //  ...
            break;
        };
    case prop_identity:
        {
             peer_identity.assign (data + 2, size - 2);
             break;
        }
    default:
        zmq_assert (false);
    }
    if (!(msg_->flags () & msg_t::more)) {
        received = true;
        finalise_initialisation ();
    }
    return true;
}
Member Data Documentation
i_engine* zmq::zmq_init_t::engine [private]
Definition at line 70 of file zmq_init.hpp.
Referenced by zmq_init_t().
i_engine* zmq::zmq_init_t::ephemeral_engine [private]
Definition at line 73 of file zmq_init.hpp.
class io_thread_t* zmq::zmq_init_t::io_thread [private]
Definition at line 96 of file zmq_init.hpp.
options_t zmq::own_t::options [protected, inherited]
Definition at line 95 of file own.hpp.
Referenced by zmq::pair_t::pair_t(), zmq::pub_t::pub_t(), zmq::pull_t::pull_t(), zmq::push_t::push_t(), zmq::rep_t::rep_t(), zmq::req_t::req_t(), zmq::sub_t::sub_t(), zmq::xpub_t::xpub_t(), zmq::xrep_t::xrep_t(), zmq::xreq_t::xreq_t(), zmq::xsub_t::xsub_t(), and zmq_init_t().
blob_t zmq::zmq_init_t::peer_identity [private]
Definition at line 92 of file zmq_init.hpp.
Referenced by zmq_init_t().
bool zmq::zmq_init_t::received [private]
Definition at line 81 of file zmq_init.hpp.
class session_t* zmq::zmq_init_t::session [private]
Definition at line 89 of file zmq_init.hpp.
class socket_base_t* zmq::zmq_init_t::socket [private]
Definition at line 84 of file zmq_init.hpp.
to_send_t zmq::zmq_init_t::to_send [private]
Definition at line 78 of file zmq_init.hpp.
Referenced by zmq_init_t().
The documentation for this class was generated from the following files:
/home/travlr/src/libzmq/src/zmq_init.hpp
/home/travlr/src/libzmq/src/zmq_init.cpp