libzmq: zmq::select_t Class Reference
zmq::select_t Class Reference
#include <select.hpp>
Classes
struct fd_entry_t
Public Types
typedef fd_t handle_t
Public Member Functions
select_t ()
~select_t ()
handle_t add_fd (fd_t fd_, struct i_poll_events *events_)
void add_timer (int timeout_, struct i_poll_events *sink_, int id_)
void cancel_timer (struct i_poll_events *sink_, int id_)
int get_load ()
void reset_pollin (handle_t handle_)
void reset_pollout (handle_t handle_)
void rm_fd (handle_t handle_)
void set_pollin (handle_t handle_)
void set_pollout (handle_t handle_)
void start ()
void stop ()
Protected Member Functions
void adjust_load (int amount_)
uint64_t execute_timers ()
Private Types
typedef std::vector< fd_entry_t > fd_set_t
Private Member Functions
select_t (const select_t &)
void loop ()
const select_t & operator= (const select_t &)
Static Private Member Functions
static bool is_retired_fd (const fd_entry_t &entry)
static void worker_routine (void *arg_)
Private Attributes
fd_set exceptfds
fd_set_t fds
fd_t maxfd
fd_set readfds
bool retired
fd_set source_set_err
fd_set source_set_in
fd_set source_set_out
bool stopping
thread_t worker
fd_set writefds
Detailed Description
Definition at line 48 of file select.hpp.
Member Typedef Documentation
typedef std::vector<fd_entry_t> zmq::select_t::fd_set_t [private]
Definition at line 86 of file select.hpp.
typedef fd_t zmq::select_t::handle_t
Definition at line 52 of file select.hpp.
Constructor & Destructor Documentation
zmq::select_t::select_t ()
Definition at line 44 of file select.cpp.
References source_set_err, source_set_in, and source_set_out.
                       :
    maxfd (retired_fd),
    retired (false),
    stopping (false)
{
    //  Clear file descriptor sets.
    FD_ZERO (&source_set_in);
    FD_ZERO (&source_set_out);
    FD_ZERO (&source_set_err);
}
zmq::select_t::~select_t ()
Definition at line 55 of file select.cpp.
References worker().
{
    worker.stop ();
}
zmq::select_t::select_t (const select_t &) [private]
Member Function Documentation
zmq::select_t::handle_t zmq::select_t::add_fd (fd_t fd_, struct i_poll_events * events_)
Definition at line 60 of file select.cpp.
References zmq_assert.
{
    //  Store the file descriptor.
    fd_entry_t entry = {fd_, events_};
    fds.push_back (entry);
    //  Ensure we do not attempt to select () on more than FD_SETSIZE
    //  file descriptors.
    zmq_assert (fds.size () <= FD_SETSIZE);
    //  Start polling on errors.
    FD_SET (fd_, &source_set_err);
    //  Adjust maxfd if necessary.
    if (fd_ > maxfd)
        maxfd = fd_;
    //  Increase the load metric of the thread.
    adjust_load (1);
    return fd_;
}
void zmq::poller_base_t::add_timer (int timeout_, struct i_poll_events * sink_, int id_) [inherited]
Definition at line 48 of file poller_base.cpp.
{
    uint64_t expiration = clock.now_ms () + timeout_;
    timer_info_t info = {sink_, id_};
    timers.insert (timers_t::value_type (expiration, info));
}
void zmq::poller_base_t::adjust_load (int amount_) [protected, inherited]
Definition at line 40 of file poller_base.cpp.
{
    if (amount_ > 0)
        load.add (amount_);
    else if (amount_ < 0)
        load.sub (-amount_);
}
void zmq::poller_base_t::cancel_timer (struct i_poll_events * sink_, int id_) [inherited]
Definition at line 55 of file poller_base.cpp.
References zmq_assert.
{
    //  Complexity of this operation is O(n). We assume it is rarely used.
    for (timers_t::iterator it = timers.begin (); it != timers.end (); ++it)
        if (it->second.sink == sink_ && it->second.id == id_) {
            timers.erase (it);
            return;
        }
    //  Timer not found.
    zmq_assert (false);
}
uint64_t zmq::poller_base_t::execute_timers () [protected, inherited]
Definition at line 68 of file poller_base.cpp.
{
    //  Fast track.
    if (timers.empty ())
        return 0;
    //  Get the current time.
    uint64_t current = clock.now_ms ();
    //   Execute the timers that are already due.
    timers_t::iterator it = timers.begin ();
    while (it != timers.end ()) {
        //  If we have to wait to execute the item, same will be true about
        //  all the following items (multimap is sorted). Thus we can stop
        //  checking the subsequent timers and return the time to wait for
        //  the next timer (at least 1ms).
        if (it->first > current)
            return it->first - current;
        //  Trigger the timer.
        it->second.sink->timer_event (it->second.id);
        //  Remove it from the list of active timers.
        timers_t::iterator o = it;
        ++it;
        timers.erase (o);
    }
    //  There are no more timers.
    return 0;
}
int zmq::poller_base_t::get_load () [inherited]
Definition at line 35 of file poller_base.cpp.
{
    return load.get ();
}
bool zmq::select_t::is_retired_fd (const fd_entry_t & entry) [static, private]
Definition at line 208 of file select.cpp.
References zmq::select_t::fd_entry_t::fd, and zmq::retired_fd.
Referenced by loop().
{
    return (entry.fd == retired_fd);
}
void zmq::select_t::loop () [private]
Definition at line 147 of file select.cpp.
References errno_assert, is_retired_fd(), and zmq::retired_fd.
{
    while (!stopping) {
        //  Execute any due timers.
        int timeout = (int) execute_timers ();
        //  Intialise the pollsets.
        memcpy (&readfds, &source_set_in, sizeof source_set_in);
        memcpy (&writefds, &source_set_out, sizeof source_set_out);
        memcpy (&exceptfds, &source_set_err, sizeof source_set_err);
        //  Wait for events.
        struct timeval tv = {(long) (timeout / 1000),
            (long) (timeout % 1000 * 1000)};
#ifdef ZMQ_HAVE_WINDOWS
        int rc = select (0, &readfds, &writefds, &exceptfds,
            timeout ? &tv : NULL);
        wsa_assert (rc != SOCKET_ERROR);
#else
        int rc = select (maxfd + 1, &readfds, &writefds, &exceptfds,
            timeout ? &tv : NULL);
        if (rc == -1 && errno == EINTR)
            continue;
        errno_assert (rc != -1);
#endif
        //  If there are no events (i.e. it's a timeout) there's no point
        //  in checking the pollset.
        if (rc == 0)
            continue;
        for (fd_set_t::size_type i = 0; i < fds.size (); i ++) {
            if (fds [i].fd == retired_fd)
                continue;
            if (FD_ISSET (fds [i].fd, &exceptfds))
                fds [i].events->in_event ();
            if (fds [i].fd == retired_fd)
                continue;
            if (FD_ISSET (fds [i].fd, &writefds))
                fds [i].events->out_event ();
            if (fds [i].fd == retired_fd)
                continue;
            if (FD_ISSET (fds [i].fd, &readfds))
                fds [i].events->in_event ();
        }
        //  Destroy retired event sources.
        if (retired) {
            fds.erase (std::remove_if (fds.begin (), fds.end (),
                zmq::select_t::is_retired_fd), fds.end ());
            retired = false;
        }
    }
}
const select_t& zmq::select_t::operator= (const select_t &) [private]
void zmq::select_t::reset_pollin (handle_t handle_)
Definition at line 122 of file select.cpp.
{
    FD_CLR (handle_, &source_set_in);
}
void zmq::select_t::reset_pollout (handle_t handle_)
Definition at line 132 of file select.cpp.
{
    FD_CLR (handle_, &source_set_out);
}
void zmq::select_t::rm_fd (handle_t handle_)
Definition at line 83 of file select.cpp.
References zmq::retired_fd, and zmq_assert.
{
    //  Mark the descriptor as retired.
    fd_set_t::iterator it;
    for (it = fds.begin (); it != fds.end (); ++it)
        if (it->fd == handle_)
            break;
    zmq_assert (it != fds.end ());
    it->fd = retired_fd;
    retired = true;
    //  Stop polling on the descriptor.
    FD_CLR (handle_, &source_set_in);
    FD_CLR (handle_, &source_set_out);
    FD_CLR (handle_, &source_set_err);
    //  Discard all events generated on this file descriptor.
    FD_CLR (handle_, &readfds);
    FD_CLR (handle_, &writefds);
    FD_CLR (handle_, &exceptfds);
    //  Adjust the maxfd attribute if we have removed the
    //  highest-numbered file descriptor.
    if (handle_ == maxfd) {
        maxfd = retired_fd;
        for (fd_set_t::iterator it = fds.begin (); it != fds.end (); ++it)
            if (it->fd > maxfd)
                maxfd = it->fd;
    }
    //  Decrease the load metric of the thread.
    adjust_load (-1);
}
void zmq::select_t::set_pollin (handle_t handle_)
Definition at line 117 of file select.cpp.
{
    FD_SET (handle_, &source_set_in);
}
void zmq::select_t::set_pollout (handle_t handle_)
Definition at line 127 of file select.cpp.
{
    FD_SET (handle_, &source_set_out);
}
void zmq::select_t::start ()
Definition at line 137 of file select.cpp.
References worker().
{
    worker.start (worker_routine, this);
}
void zmq::select_t::stop ()
Definition at line 142 of file select.cpp.
{
    stopping = true;
}
void zmq::select_t::worker_routine (void * arg_) [static, private]
Definition at line 203 of file select.cpp.
{
    ((select_t*) arg_)->loop ();
}
Member Data Documentation
fd_set zmq::select_t::exceptfds [private]
Definition at line 95 of file select.hpp.
fd_set_t zmq::select_t::fds [private]
Definition at line 87 of file select.hpp.
fd_t zmq::select_t::maxfd [private]
Definition at line 98 of file select.hpp.
fd_set zmq::select_t::readfds [private]
Definition at line 93 of file select.hpp.
bool zmq::select_t::retired [private]
Definition at line 101 of file select.hpp.
fd_set zmq::select_t::source_set_err [private]
Definition at line 91 of file select.hpp.
Referenced by select_t().
fd_set zmq::select_t::source_set_in [private]
Definition at line 89 of file select.hpp.
Referenced by select_t().
fd_set zmq::select_t::source_set_out [private]
Definition at line 90 of file select.hpp.
Referenced by select_t().
bool zmq::select_t::stopping [private]
Definition at line 104 of file select.hpp.
thread_t zmq::select_t::worker [private]
Definition at line 107 of file select.hpp.
fd_set zmq::select_t::writefds [private]
Definition at line 94 of file select.hpp.
The documentation for this class was generated from the following files:
/home/travlr/src/libzmq/src/select.hpp
/home/travlr/src/libzmq/src/select.cpp