libzmq: zmq::atomic_ptr_t< T > Class Template Reference
zmq::atomic_ptr_t< T > Class Template Reference
#include <atomic_ptr.hpp>
Public Member Functions
atomic_ptr_t ()
~atomic_ptr_t ()
T * cas (T *cmp_, T *val_)
void set (T *ptr_)
T * xchg (T *val_)
Private Member Functions
atomic_ptr_t (const atomic_ptr_t &)
const atomic_ptr_t & operator= (const atomic_ptr_t &)
Private Attributes
volatile T * ptr
mutex_t sync
Detailed Description
template<typename T>
class zmq::atomic_ptr_t< T >
Definition at line 51 of file atomic_ptr.hpp.
Constructor & Destructor Documentation
template<typename T> zmq::atomic_ptr_t< T >::atomic_ptr_t () [inline]
Definition at line 56 of file atomic_ptr.hpp.
template<typename T> zmq::atomic_ptr_t< T >::~atomic_ptr_t () [inline]
Definition at line 62 of file atomic_ptr.hpp.
template<typename T> zmq::atomic_ptr_t< T >::atomic_ptr_t (const atomic_ptr_t< T > &) [private]
Member Function Documentation
template<typename T> T* zmq::atomic_ptr_t< T >::cas (T * cmp_, T * val_) [inline]
Definition at line 104 of file atomic_ptr.hpp.
template<typename T> const atomic_ptr_t& zmq::atomic_ptr_t< T >::operator= (const atomic_ptr_t< T > &) [private]
template<typename T> void zmq::atomic_ptr_t< T >::set (T * ptr_) [inline]
Definition at line 69 of file atomic_ptr.hpp.
template<typename T> T* zmq::atomic_ptr_t< T >::xchg (T * val_) [inline]
Definition at line 76 of file atomic_ptr.hpp.
Referenced by zmq::yqueue_t< T, N >::pop(), zmq::yqueue_t< T, N >::push(), and zmq::yqueue_t< T, N >::~yqueue_t().
Member Data Documentation
template<typename T> volatile T* zmq::atomic_ptr_t< T >::ptr [private]
Definition at line 133 of file atomic_ptr.hpp.
Referenced by zmq::atomic_ptr_t< chunk_t >::atomic_ptr_t(), zmq::atomic_ptr_t< chunk_t >::cas(), zmq::atomic_ptr_t< chunk_t >::set(), and zmq::atomic_ptr_t< chunk_t >::xchg().
template<typename T> mutex_t zmq::atomic_ptr_t< T >::sync [private]
Definition at line 135 of file atomic_ptr.hpp.
Referenced by zmq::atomic_ptr_t< chunk_t >::cas(), and zmq::atomic_ptr_t< chunk_t >::xchg().
The documentation for this class was generated from the following file:
src/atomic_ptr.hpp