libzmq: zmq::io_thread_t Class Reference
zmq::io_thread_t Class Reference
#include <io_thread.hpp>
Public Member Functions
io_thread_t (class ctx_t *ctx_, uint32_t tid_)
~io_thread_t ()
ctx_t * get_ctx ()
int get_load ()
mailbox_t * get_mailbox ()
poller_t * get_poller ()
uint32_t get_tid ()
void in_event ()
void out_event ()
void process_command (struct command_t &cmd_)
void process_stop ()
void start ()
void stop ()
void timer_event (int id_)
Protected Member Functions
class io_thread_t * choose_io_thread (uint64_t affinity_)
void destroy_socket (class socket_base_t *socket_)
struct endpoint_t find_endpoint (const char *addr_)
void log (const char *format_,...)
virtual void process_activate_read ()
virtual void process_activate_write (uint64_t msgs_read_)
virtual void process_attach (struct i_engine *engine_, const blob_t &peer_identity_)
virtual void process_bind (class pipe_t *pipe_, const blob_t &peer_identity_)
virtual void process_hiccup (void *pipe_)
virtual void process_own (class own_t *object_)
virtual void process_pipe_term ()
virtual void process_pipe_term_ack ()
virtual void process_plug ()
virtual void process_reap (class socket_base_t *socket_)
virtual void process_reaped ()
virtual void process_seqnum ()
virtual void process_term (int linger_)
virtual void process_term_ack ()
virtual void process_term_req (class own_t *object_)
int register_endpoint (const char *addr_, struct endpoint_t &endpoint_)
void send_activate_read (class pipe_t *destination_)
void send_activate_write (class pipe_t *destination_, uint64_t msgs_read_)
void send_attach (class session_t *destination_, struct i_engine *engine_, const blob_t &peer_identity_, bool inc_seqnum_=true)
void send_bind (class own_t *destination_, class pipe_t *pipe_, const blob_t &peer_identity_, bool inc_seqnum_=true)
void send_done ()
void send_hiccup (class pipe_t *destination_, void *pipe_)
void send_own (class own_t *destination_, class own_t *object_)
void send_pipe_term (class pipe_t *destination_)
void send_pipe_term_ack (class pipe_t *destination_)
void send_plug (class own_t *destination_, bool inc_seqnum_=true)
void send_reap (class socket_base_t *socket_)
void send_reaped ()
void send_stop ()
void send_term (class own_t *destination_, int linger_)
void send_term_ack (class own_t *destination_)
void send_term_req (class own_t *destination_, class own_t *object_)
void unregister_endpoints (class socket_base_t *socket_)
Private Member Functions
io_thread_t (const io_thread_t &)
const io_thread_t & operator= (const io_thread_t &)
Private Attributes
mailbox_t mailbox
poller_t::handle_t mailbox_handle
poller_t * poller
Detailed Description
Definition at line 38 of file io_thread.hpp.
Constructor & Destructor Documentation
zmq::io_thread_t::io_thread_t (class ctx_t * ctx_, uint32_t tid_)
Definition at line 28 of file io_thread.cpp.
References alloc_assert, zmq::mailbox_t::get_fd(), mailbox, mailbox_handle, and poller.
zmq::io_thread_t::~io_thread_t ()
Definition at line 38 of file io_thread.cpp.
zmq::io_thread_t::io_thread_t (const io_thread_t &) [private]
Member Function Documentation
zmq::io_thread_t * zmq::object_t::choose_io_thread (uint64_t affinity_) [protected, inherited]
Definition at line 168 of file object.cpp.
References zmq::object_t::choose_io_thread().
Referenced by zmq::object_t::choose_io_thread().
void zmq::object_t::destroy_socket (class socket_base_t * socket_) [protected, inherited]
Definition at line 155 of file object.cpp.
zmq::endpoint_t zmq::object_t::find_endpoint (const char * addr_) [read, protected, inherited]
Definition at line 150 of file object.cpp.
zmq::ctx_t * zmq::object_t::get_ctx () [inherited]
Definition at line 53 of file object.cpp.
int zmq::io_thread_t::get_load ()
Definition at line 59 of file io_thread.cpp.
Referenced by zmq::ctx_t::choose_io_thread().
zmq::mailbox_t * zmq::io_thread_t::get_mailbox ()
Definition at line 54 of file io_thread.cpp.
Referenced by zmq::ctx_t::ctx_t().
zmq::poller_t * zmq::io_thread_t::get_poller ()
Definition at line 97 of file io_thread.cpp.
References zmq_assert.
Referenced by zmq::io_object_t::plug().
uint32_t zmq::object_t::get_tid () [inherited]
Definition at line 48 of file object.cpp.
Referenced by zmq::ctx_t::destroy_socket(), and zmq::object_t::send_command().
void zmq::io_thread_t::in_event () [virtual]
Implements zmq::i_poll_events.
Definition at line 64 of file io_thread.cpp.
References zmq::command_t::destination, errno_assert, and zmq::object_t::process_command().
void zmq::object_t::log (const char * format_, ...) [protected, inherited]
Definition at line 160 of file object.cpp.
const io_thread_t& zmq::io_thread_t::operator= (const io_thread_t &) [private]
void zmq::io_thread_t::out_event () [virtual]
Implements zmq::i_poll_events.
Definition at line 85 of file io_thread.cpp.
References zmq_assert.
void zmq::object_t::process_activate_read () [protected, virtual, inherited]
Reimplemented in zmq::pipe_t.
Definition at line 427 of file object.cpp.
References zmq_assert.
void zmq::object_t::process_activate_write (uint64_t msgs_read_) [protected, virtual, inherited]
Reimplemented in zmq::pipe_t.
Definition at line 432 of file object.cpp.
References zmq_assert.
void zmq::object_t::process_attach (struct i_engine * engine_, const blob_t & peer_identity_) [protected, virtual, inherited]
Reimplemented in zmq::session_t.
Definition at line 416 of file object.cpp.
References zmq_assert.
void zmq::object_t::process_bind (class pipe_t * pipe_, const blob_t & peer_identity_) [protected, virtual, inherited]
Reimplemented in zmq::socket_base_t.
Definition at line 422 of file object.cpp.
References zmq_assert.
void zmq::object_t::process_command (struct command_t & cmd_) [inherited]
Definition at line 58 of file object.cpp.
References zmq::command_t::activate_read, zmq::command_t::activate_write, zmq::command_t::args, zmq::command_t::attach, zmq::command_t::bind, zmq::command_t::hiccup, zmq::command_t::own, zmq::command_t::pipe_term, zmq::command_t::pipe_term_ack, zmq::command_t::plug, zmq::command_t::reap, zmq::command_t::reaped, zmq::command_t::stop, zmq::command_t::term, zmq::command_t::term_ack, zmq::command_t::term_req, zmq::command_t::type, and zmq_assert.
Referenced by zmq::reaper_t::in_event(), in_event(), and zmq::socket_base_t::process_commands().
void zmq::object_t::process_hiccup (void * pipe_) [protected, virtual, inherited]
Reimplemented in zmq::pipe_t.
Definition at line 437 of file object.cpp.
References zmq_assert.
void zmq::object_t::process_own (class own_t * object_) [protected, virtual, inherited]
Reimplemented in zmq::own_t.
Definition at line 411 of file object.cpp.
References zmq_assert.
void zmq::object_t::process_pipe_term () [protected, virtual, inherited]
Reimplemented in zmq::pipe_t.
Definition at line 442 of file object.cpp.
References zmq_assert.
void zmq::object_t::process_pipe_term_ack () [protected, virtual, inherited]
Reimplemented in zmq::pipe_t.
Definition at line 447 of file object.cpp.
References zmq_assert.
void zmq::object_t::process_plug () [protected, virtual, inherited]
Reimplemented in zmq::connect_session_t, zmq::session_t, zmq::zmq_connecter_t, zmq::zmq_init_t, and zmq::zmq_listener_t.
Definition at line 406 of file object.cpp.
References zmq_assert.
void zmq::object_t::process_reap (class socket_base_t * socket_) [protected, virtual, inherited]
Reimplemented in zmq::reaper_t.
Definition at line 467 of file object.cpp.
References zmq_assert.
void zmq::object_t::process_reaped () [protected, virtual, inherited]
Reimplemented in zmq::reaper_t.
Definition at line 472 of file object.cpp.
References zmq_assert.
void zmq::object_t::process_seqnum () [protected, virtual, inherited]
Reimplemented in zmq::own_t.
Definition at line 477 of file object.cpp.
References zmq_assert.
void zmq::io_thread_t::process_stop () [virtual]
Reimplemented from zmq::object_t.
Definition at line 103 of file io_thread.cpp.
void zmq::object_t::process_term (int linger_) [protected, virtual, inherited]
Reimplemented in zmq::own_t, zmq::session_t, zmq::socket_base_t, and zmq::zmq_listener_t.
Definition at line 457 of file object.cpp.
References zmq_assert.
void zmq::object_t::process_term_ack () [protected, virtual, inherited]
Reimplemented in zmq::own_t.
Definition at line 462 of file object.cpp.
References zmq_assert.
void zmq::object_t::process_term_req (class own_t * object_) [protected, virtual, inherited]
Reimplemented in zmq::own_t.
Definition at line 452 of file object.cpp.
References zmq_assert.
int zmq::object_t::register_endpoint (const char * addr_, struct endpoint_t & endpoint_) [protected, inherited]
Definition at line 140 of file object.cpp.
void zmq::object_t::send_activate_read (class pipe_t * destination_) [protected, inherited]
Definition at line 273 of file object.cpp.
References zmq::command_t::activate_read, zmq::command_t::destination, and zmq::command_t::type.
void zmq::object_t::send_activate_write (class pipe_t * destination_, uint64_t msgs_read_) [protected, inherited]
Definition at line 284 of file object.cpp.
References zmq::command_t::activate_write, zmq::command_t::args, zmq::command_t::destination, and zmq::command_t::type.
void zmq::object_t::send_attach (class session_t * destination_, struct i_engine * engine_, const blob_t & peer_identity_, bool inc_seqnum_ = true) [protected, inherited]
Definition at line 213 of file object.cpp.
References alloc_assert, zmq::command_t::args, zmq::command_t::attach, zmq::command_t::destination, zmq::own_t::inc_seqnum(), zmq::command_t::type, and zmq_assert.
void zmq::object_t::send_bind (class own_t * destination_, class pipe_t * pipe_, const blob_t & peer_identity_, bool inc_seqnum_ = true) [protected, inherited]
Definition at line 243 of file object.cpp.
References alloc_assert, zmq::command_t::args, zmq::command_t::bind, zmq::command_t::destination, zmq::own_t::inc_seqnum(), zmq::command_t::type, and zmq_assert.
void zmq::object_t::send_done () [protected, inherited]
Definition at line 390 of file object.cpp.
References zmq::command_t::destination, zmq::command_t::done, zmq::ctx_t::term_tid, and zmq::command_t::type.
void zmq::object_t::send_hiccup (class pipe_t * destination_, void * pipe_) [protected, inherited]
Definition at line 297 of file object.cpp.
References zmq::command_t::args, zmq::command_t::destination, zmq::command_t::hiccup, and zmq::command_t::type.
void zmq::object_t::send_own (class own_t * destination_, class own_t * object_) [protected, inherited]
Definition at line 200 of file object.cpp.
References zmq::command_t::args, zmq::command_t::destination, zmq::own_t::inc_seqnum(), zmq::command_t::own, and zmq::command_t::type.
void zmq::object_t::send_pipe_term (class pipe_t * destination_) [protected, inherited]
Definition at line 309 of file object.cpp.
References zmq::command_t::destination, zmq::command_t::pipe_term, and zmq::command_t::type.
void zmq::object_t::send_pipe_term_ack (class pipe_t * destination_) [protected, inherited]
Definition at line 320 of file object.cpp.
References zmq::command_t::destination, zmq::command_t::pipe_term_ack, and zmq::command_t::type.
void zmq::object_t::send_plug (class own_t * destination_, bool inc_seqnum_ = true) [protected, inherited]
Definition at line 186 of file object.cpp.
References zmq::command_t::destination, zmq::own_t::inc_seqnum(), zmq::command_t::plug, and zmq::command_t::type.
void zmq::object_t::send_reap (class socket_base_t * socket_) [protected, inherited]
Definition at line 367 of file object.cpp.
References zmq::command_t::args, zmq::command_t::destination, zmq::command_t::reap, and zmq::command_t::type.
void zmq::object_t::send_reaped () [protected, inherited]
Definition at line 379 of file object.cpp.
References zmq::command_t::destination, zmq::command_t::reaped, and zmq::command_t::type.
void zmq::object_t::send_stop () [protected, inherited]
Definition at line 173 of file object.cpp.
References zmq::command_t::destination, zmq::command_t::stop, and zmq::command_t::type.
void zmq::object_t::send_term (class own_t * destination_, int linger_) [protected, inherited]
Definition at line 344 of file object.cpp.
References zmq::command_t::args, zmq::command_t::destination, zmq::command_t::term, and zmq::command_t::type.
void zmq::object_t::send_term_ack (class own_t * destination_) [protected, inherited]
Definition at line 356 of file object.cpp.
References zmq::command_t::destination, zmq::command_t::term_ack, and zmq::command_t::type.
void zmq::object_t::send_term_req (class own_t * destination_, class own_t * object_) [protected, inherited]
Definition at line 331 of file object.cpp.
References zmq::command_t::args, zmq::command_t::destination, zmq::command_t::term_req, and zmq::command_t::type.
void zmq::io_thread_t::start ()
Definition at line 43 of file io_thread.cpp.
Referenced by zmq::ctx_t::ctx_t().
void zmq::io_thread_t::stop ()
Definition at line 49 of file io_thread.cpp.
void zmq::io_thread_t::timer_event (int id_) [virtual]
Implements zmq::i_poll_events.
Definition at line 91 of file io_thread.cpp.
References zmq_assert.
void zmq::object_t::unregister_endpoints (class socket_base_t * socket_) [protected, inherited]
Definition at line 145 of file object.cpp.
Member Data Documentation
mailbox_t zmq::io_thread_t::mailbox [private]
Definition at line 74 of file io_thread.hpp.
Referenced by io_thread_t().
poller_t::handle_t zmq::io_thread_t::mailbox_handle [private]
Definition at line 77 of file io_thread.hpp.
Referenced by io_thread_t().
poller_t* zmq::io_thread_t::poller [private]
Definition at line 80 of file io_thread.hpp.
Referenced by io_thread_t().
The documentation for this class was generated from the following files:
src/io_thread.hpp
src/io_thread.cpp