libzmq: zmq::decoder_t Class Reference
zmq::decoder_t Class Reference
#include <decoder.hpp>
Public Member Functions
decoder_t (size_t bufsize_, int64_t maxmsgsize_)
~decoder_t ()
void get_buffer (unsigned char **data_, size_t *size_)
size_t process_buffer (unsigned char *data_, size_t size_)
void set_session (class session_t *session_)
Protected Types
typedef bool(decoder_t::* step_t)()
Protected Member Functions
void decoding_error ()
void next_step (void *read_pos_, size_t to_read_, step_t next_)
Private Member Functions
decoder_t (const decoder_t &)
bool eight_byte_size_ready ()
bool flags_ready ()
bool message_ready ()
bool one_byte_size_ready ()
void operator= (const decoder_t &)
Private Attributes
msg_t in_progress
int64_t maxmsgsize
class session_t * session
unsigned char tmpbuf [8]
Detailed Description
Definition at line 180 of file decoder.hpp.
Member Typedef Documentation
typedef bool(decoder_t ::* zmq::decoder_base_t< decoder_t >::step_t)() [protected, inherited]
Definition at line 146 of file decoder.hpp.
Constructor & Destructor Documentation
zmq::decoder_t::decoder_t (size_t bufsize_, int64_t maxmsgsize_)
Definition at line 29 of file decoder.cpp.
References errno_assert, in_progress, zmq::msg_t::init(), zmq::decoder_base_t< decoder_t >::next_step(), one_byte_size_ready(), and tmpbuf.
zmq::decoder_t::~decoder_t ()
Definition at line 41 of file decoder.cpp.
References errno_assert.
zmq::decoder_t::decoder_t (const decoder_t &) [private]
Member Function Documentation
void zmq::decoder_base_t< decoder_t >::decoding_error () [inline, protected, inherited]
Definition at line 160 of file decoder.hpp.
References zmq::decoder_base_t< T >::next.
bool zmq::decoder_t::eight_byte_size_ready () [private]
Definition at line 90 of file decoder.cpp.
References errno_assert, and flags_ready().
Referenced by one_byte_size_ready().
bool zmq::decoder_t::flags_ready () [private]
Definition at line 124 of file decoder.cpp.
References message_ready().
Referenced by eight_byte_size_ready(), and one_byte_size_ready().
void zmq::decoder_base_t< decoder_t >::get_buffer (unsigned char ** data_, size_t * size_) [inline, inherited]
Definition at line 69 of file decoder.hpp.
References zmq::decoder_base_t< T >::buf, zmq::decoder_base_t< T >::bufsize, zmq::decoder_base_t< T >::read_pos, and zmq::decoder_base_t< T >::to_read.
bool zmq::decoder_t::message_ready () [private]
Definition at line 135 of file decoder.cpp.
References one_byte_size_ready().
Referenced by flags_ready().
void zmq::decoder_base_t< decoder_t >::next_step (void * read_pos_, size_t to_read_, step_t next_) [inline, protected, inherited]
Definition at line 150 of file decoder.hpp.
References zmq::decoder_base_t< T >::next, zmq::decoder_base_t< T >::read_pos, and zmq::decoder_base_t< T >::to_read.
Referenced by decoder_t().
bool zmq::decoder_t::one_byte_size_ready () [private]
Definition at line 52 of file decoder.cpp.
References eight_byte_size_ready(), errno_assert, and flags_ready().
Referenced by decoder_t(), and message_ready().
void zmq::decoder_t::operator= (const decoder_t &) [private]
size_t zmq::decoder_base_t< decoder_t >::process_buffer (unsigned char * data_, size_t size_) [inline, inherited]
Definition at line 93 of file decoder.hpp.
References zmq::decoder_base_t< T >::next, zmq::decoder_base_t< T >::read_pos, zmq::decoder_base_t< T >::to_read, and unlikely.
void zmq::decoder_t::set_session (class session_t * session_)
Definition at line 47 of file decoder.cpp.
Member Data Documentation
msg_t zmq::decoder_t::in_progress [private]
Definition at line 198 of file decoder.hpp.
Referenced by decoder_t().
int64_t zmq::decoder_t::maxmsgsize [private]
Definition at line 200 of file decoder.hpp.
class session_t* zmq::decoder_t::session [private]
Definition at line 196 of file decoder.hpp.
unsigned char zmq::decoder_t::tmpbuf[8] [private]
Definition at line 197 of file decoder.hpp.
Referenced by decoder_t().
The documentation for this class was generated from the following files:
/home/travlr/dev/zmq-contribution/repos/libzmq/src/decoder.hpp
/home/travlr/dev/zmq-contribution/repos/libzmq/src/decoder.cpp