libzmq: zmq::atomic_counter_t Class Reference
zmq::atomic_counter_t Class Reference
#include <atomic_counter.hpp>
Public Types
typedef uint32_t integer_t
Public Member Functions
atomic_counter_t (integer_t value_=0)
~atomic_counter_t ()
integer_t add (integer_t increment_)
integer_t get ()
void set (integer_t value_)
bool sub (integer_t decrement)
Private Member Functions
atomic_counter_t (const atomic_counter_t &)
const atomic_counter_t & operator= (const atomic_counter_t &)
Private Attributes
mutex_t sync
volatile integer_t value
Detailed Description
Definition at line 54 of file atomic_counter.hpp.
Member Typedef Documentation
typedef uint32_t zmq::atomic_counter_t::integer_t
Definition at line 58 of file atomic_counter.hpp.
Constructor & Destructor Documentation
zmq::atomic_counter_t::atomic_counter_t (integer_t value_ = 0) [inline]
Definition at line 60 of file atomic_counter.hpp.
zmq::atomic_counter_t::~atomic_counter_t () [inline]
Definition at line 65 of file atomic_counter.hpp.
zmq::atomic_counter_t::atomic_counter_t (const atomic_counter_t &) [private]
Member Function Documentation
integer_t zmq::atomic_counter_t::add (integer_t increment_) [inline]
Definition at line 76 of file atomic_counter.hpp.
References zmq::mutex_t::lock(), sync, zmq::mutex_t::unlock(), and value.
integer_t zmq::atomic_counter_t::get () [inline]
Definition at line 132 of file atomic_counter.hpp.
References value.
const atomic_counter_t& zmq::atomic_counter_t::operator= (const atomic_counter_t &) [private]
void zmq::atomic_counter_t::set (integer_t value_) [inline]
Definition at line 70 of file atomic_counter.hpp.
References value.
bool zmq::atomic_counter_t::sub (integer_t decrement) [inline]
Definition at line 103 of file atomic_counter.hpp.
References zmq::mutex_t::lock(), sync, zmq::mutex_t::unlock(), and value.
Member Data Documentation
mutex_t zmq::atomic_counter_t::sync [private]
Definition at line 141 of file atomic_counter.hpp.
Referenced by add(), and sub().
volatile integer_t zmq::atomic_counter_t::value [private]
Definition at line 139 of file atomic_counter.hpp.
Referenced by add(), get(), set(), and sub().
The documentation for this class was generated from the following file:
src/atomic_counter.hpp