libzmq: zmq::clock_t Class Reference
zmq::clock_t Class Reference
#include <clock.hpp>
Public Member Functions
clock_t ()
~clock_t ()
uint64_t now_ms ()
Static Public Member Functions
static uint64_t now_us ()
static uint64_t rdtsc ()
Private Member Functions
clock_t (const clock_t &)
const clock_t & operator= (const clock_t &)
Private Attributes
uint64_t last_time
uint64_t last_tsc
Detailed Description
Definition at line 29 of file clock.hpp.
Constructor & Destructor Documentation
zmq::clock_t::clock_t ()
Definition at line 37 of file clock.cpp.
                     :
    last_tsc (rdtsc ()),
    last_time (now_us () / 1000)
{
}
zmq::clock_t::~clock_t ()
Definition at line 43 of file clock.cpp.
{
}
zmq::clock_t::clock_t (const clock_t &) [private]
Member Function Documentation
uint64_t zmq::clock_t::now_ms ()
Definition at line 75 of file clock.cpp.
References zmq::clock_precision, and likely.
Referenced by zmq_poll().
{
    uint64_t tsc = rdtsc ();
    //  If TSC is not supported, get precise time and chop off the microseconds.
    if (!tsc)
        return now_us () / 1000;
    //  If TSC haven't jumped back (in case of migration to a different
    //  CPU core) and if not too much time elapsed since last measurement,
    //  we can return cached time value.
    if (likely (tsc - last_tsc <= (clock_precision / 2) && tsc >= last_tsc))
        return last_time;
    last_tsc = tsc;
    last_time = now_us () / 1000;
    return last_time;
}
uint64_t zmq::clock_t::now_us () [static]
Definition at line 47 of file clock.cpp.
References errno_assert.
Referenced by zmq_stopwatch_start(), and zmq_stopwatch_stop().
{
#if defined ZMQ_HAVE_WINDOWS
    //  Get the high resolution counter's accuracy.
    LARGE_INTEGER ticksPerSecond;
    QueryPerformanceFrequency (&ticksPerSecond);
    //  What time is it?
    LARGE_INTEGER tick;
    QueryPerformanceCounter (&tick);
    //  Convert the tick number into the number of seconds
    //  since the system was started.
    double ticks_div = (double) (ticksPerSecond.QuadPart / 1000000);
    return (uint64_t) (tick.QuadPart / ticks_div);
#else
    //  Use POSIX gettimeofday function to get precise time.
    struct timeval tv;
    int rc = gettimeofday (&tv, NULL);
    errno_assert (rc == 0);
    return (tv.tv_sec * (uint64_t) 1000000 + tv.tv_usec);
#endif
}
const clock_t& zmq::clock_t::operator= (const clock_t &) [private]
uint64_t zmq::clock_t::rdtsc () [static]
Definition at line 94 of file clock.cpp.
Referenced by zmq::socket_base_t::process_commands().
{
#if (defined _MSC_VER && (defined _M_IX86 || defined _M_X64))
    return __rdtsc ();
#elif (defined __GNUC__ && (defined __i386__ || defined __x86_64__))
    uint32_t low, high;
    __asm__ volatile ("rdtsc" : "=a" (low), "=d" (high));
    return (uint64_t) high << 32 | low;
#elif (defined __SUNPRO_CC && (__SUNPRO_CC >= 0x5100) && (defined __i386 || \
    defined __amd64 || defined __x86_64))
    union {
        uint64_t u64val;
        uint32_t u32val [2];
    } tsc;
    asm("rdtsc" : "=a" (tsc.u32val [0]), "=d" (tsc.u32val [1]));
    return tsc.u64val;
#elif defined(__s390__)
    uint64_t tsc;
    asm("\tstck\t%0\n" : "=Q" (tsc) : : "cc");
    tsc >>= 12;     /* convert to microseconds just to be consistent */
    return(tsc);
#else
    return 0;
#endif
}
Member Data Documentation
uint64_t zmq::clock_t::last_time [private]
Definition at line 52 of file clock.hpp.
uint64_t zmq::clock_t::last_tsc [private]
Definition at line 49 of file clock.hpp.
The documentation for this class was generated from the following files:
/home/travlr/src/libzmq/src/clock.hpp
/home/travlr/src/libzmq/src/clock.cpp