libzmq: zmq::sub_session_t Class Reference
zmq::sub_session_t Class Reference
#include <sub.hpp>
Public Member Functions
sub_session_t (class io_thread_t *io_thread_, bool connect_, class socket_base_t *socket_, const options_t &options_, const char *protocol_, const char *address_)
~sub_session_t ()
void attach_pipe (class pipe_t *pipe_)
void detach ()
void flush ()
ctx_t * get_ctx ()
uint32_t get_tid ()
void hiccuped (class pipe_t *pipe_)
void inc_seqnum ()
void plug (class io_thread_t *io_thread_)
void process_command (struct command_t &cmd_)
virtual int read (msg_t *msg_)
void read_activated (class pipe_t *pipe_)
void register_term_acks (int count_)
void terminated (class pipe_t *pipe_)
void unplug ()
void unregister_term_ack ()
virtual int write (msg_t *msg_)
void write_activated (class pipe_t *pipe_)
Static Public Member Functions
static session_base_t * create (class io_thread_t *io_thread_, bool connect_, class socket_base_t *socket_, const options_t &options_, const char *protocol_, const char *address_)
Protected Types
typedef poller_t::handle_t handle_t
Protected Member Functions
handle_t add_fd (fd_t fd_)
void add_timer (int timout_, int id_)
void cancel_timer (int id_)
class io_thread_t * choose_io_thread (uint64_t affinity_)
void destroy_socket (class socket_base_t *socket_)
struct endpoint_t find_endpoint (const char *addr_)
void in_event ()
bool is_terminating ()
void launch_child (own_t *object_)
void launch_sibling (own_t *object_)
void log (const char *format_,...)
void out_event ()
virtual void process_activate_read ()
virtual void process_activate_write (uint64_t msgs_read_)
virtual void process_bind (class pipe_t *pipe_)
virtual void process_destroy ()
virtual void process_hiccup (void *pipe_)
virtual void process_pipe_term ()
virtual void process_pipe_term_ack ()
virtual void process_reap (class socket_base_t *socket_)
virtual void process_reaped ()
virtual void process_stop ()
int register_endpoint (const char *addr_, struct endpoint_t &endpoint_)
void reset_pollin (handle_t handle_)
void reset_pollout (handle_t handle_)
void rm_fd (handle_t handle_)
void send_activate_read (class pipe_t *destination_)
void send_activate_write (class pipe_t *destination_, uint64_t msgs_read_)
void send_attach (class session_base_t *destination_, struct i_engine *engine_, bool inc_seqnum_=true)
void send_bind (class own_t *destination_, class pipe_t *pipe_, bool inc_seqnum_=true)
void send_done ()
void send_hiccup (class pipe_t *destination_, void *pipe_)
void send_own (class own_t *destination_, class own_t *object_)
void send_pipe_term (class pipe_t *destination_)
void send_pipe_term_ack (class pipe_t *destination_)
void send_plug (class own_t *destination_, bool inc_seqnum_=true)
void send_reap (class socket_base_t *socket_)
void send_reaped ()
void send_stop ()
void send_term (class own_t *destination_, int linger_)
void send_term_ack (class own_t *destination_)
void send_term_req (class own_t *destination_, class own_t *object_)
void set_pollin (handle_t handle_)
void set_pollout (handle_t handle_)
void terminate ()
void unregister_endpoints (class socket_base_t *socket_)
Protected Attributes
options_t options
Private Member Functions
sub_session_t (const sub_session_t &)
const sub_session_t & operator= (const sub_session_t &)
Detailed Description
Definition at line 48 of file sub.hpp.
Member Typedef Documentation
typedef poller_t::handle_t zmq::io_object_t::handle_t [protected, inherited]
Definition at line 51 of file io_object.hpp.
Constructor & Destructor Documentation
zmq::sub_session_t::sub_session_t (class io_thread_t * io_thread_, bool connect_, class socket_base_t * socket_, const options_t & options_, const char * protocol_, const char * address_)
Definition at line 82 of file sub.cpp.
zmq::sub_session_t::~sub_session_t ()
Definition at line 90 of file sub.cpp.
zmq::sub_session_t::sub_session_t (const sub_session_t &) [private]
Member Function Documentation
zmq::io_object_t::handle_t zmq::io_object_t::add_fd (fd_t fd_) [protected, inherited]
Definition at line 54 of file io_object.cpp.
void zmq::io_object_t::add_timer (int timout_, int id_) [protected, inherited]
Definition at line 84 of file io_object.cpp.
void zmq::session_base_t::attach_pipe (class pipe_t * pipe_) [inherited]
Definition at line 142 of file session_base.cpp.
References zmq::pipe_t::set_event_sink(), and zmq_assert.
Referenced by zmq::socket_base_t::connect().
void zmq::io_object_t::cancel_timer (int id_) [protected, inherited]
Definition at line 89 of file io_object.cpp.
zmq::io_thread_t * zmq::object_t::choose_io_thread (uint64_t affinity_) [protected, inherited]
Definition at line 159 of file object.cpp.
References zmq::object_t::choose_io_thread().
Referenced by zmq::object_t::choose_io_thread().
zmq::session_base_t * zmq::session_base_t::create (class io_thread_t * io_thread_, bool connect_, class socket_base_t * socket_, const options_t & options_, const char * protocol_, const char * address_) [static, inherited]
Definition at line 46 of file session_base.cpp.
References alloc_assert, zmq::options_t::type, ZMQ_PAIR, ZMQ_PUB, ZMQ_PULL, ZMQ_PUSH, ZMQ_REP, ZMQ_REQ, ZMQ_ROUTER, ZMQ_SUB, ZMQ_XPUB, ZMQ_XREP, ZMQ_XREQ, and ZMQ_XSUB.
Referenced by zmq::socket_base_t::connect(), zmq::tcp_listener_t::in_event(), and zmq::ipc_listener_t::in_event().
void zmq::object_t::destroy_socket (class socket_base_t * socket_) [protected, inherited]
Definition at line 146 of file object.cpp.
void zmq::session_base_t::detach () [inherited]
Definition at line 285 of file session_base.cpp.
zmq::endpoint_t zmq::object_t::find_endpoint (const char * addr_) [read, protected, inherited]
Definition at line 141 of file object.cpp.
void zmq::session_base_t::flush () [inherited]
Definition at line 175 of file session_base.cpp.
zmq::ctx_t * zmq::object_t::get_ctx () [inherited]
Definition at line 53 of file object.cpp.
uint32_t zmq::object_t::get_tid () [inherited]
Definition at line 48 of file object.cpp.
Referenced by zmq::ctx_t::destroy_socket(), and zmq::object_t::send_command().
void zmq::session_base_t::hiccuped (class pipe_t * pipe_) [virtual, inherited]
Implements zmq::i_pipe_events.
Definition at line 236 of file session_base.cpp.
References zmq_assert.
void zmq::io_object_t::in_event () [protected, virtual, inherited]
Implements zmq::i_poll_events.
Reimplemented in zmq::ipc_connecter_t, zmq::ipc_listener_t, zmq::stream_engine_t, zmq::tcp_connecter_t, and zmq::tcp_listener_t.
Definition at line 94 of file io_object.cpp.
References zmq_assert.
void zmq::own_t::inc_seqnum () [inherited]
Definition at line 56 of file own.cpp.
Referenced by zmq::ctx_t::find_endpoint(), zmq::tcp_listener_t::in_event(), zmq::ipc_listener_t::in_event(), zmq::object_t::send_attach(), zmq::object_t::send_bind(), zmq::object_t::send_own(), and zmq::object_t::send_plug().
bool zmq::own_t::is_terminating () [protected, inherited]
Definition at line 156 of file own.cpp.
void zmq::own_t::launch_child (own_t * object_) [protected, inherited]
Definition at line 71 of file own.cpp.
References zmq::own_t::set_owner().
void zmq::own_t::launch_sibling (own_t * object_) [protected, inherited]
Definition at line 83 of file own.cpp.
References zmq::own_t::set_owner().
void zmq::object_t::log (const char * format_, ...) [protected, inherited]
Definition at line 151 of file object.cpp.
const sub_session_t& zmq::sub_session_t::operator= (const sub_session_t &) [private]
void zmq::io_object_t::out_event () [protected, virtual, inherited]
Implements zmq::i_poll_events.
Reimplemented in zmq::ipc_connecter_t, zmq::stream_engine_t, and zmq::tcp_connecter_t.
Definition at line 99 of file io_object.cpp.
References zmq_assert.
void zmq::io_object_t::plug (class io_thread_t * io_thread_) [inherited]
Definition at line 36 of file io_object.cpp.
References zmq::io_thread_t::get_poller(), and zmq_assert.
Referenced by zmq::io_object_t::io_object_t(), and zmq::stream_engine_t::plug().
void zmq::object_t::process_activate_read () [protected, virtual, inherited]
Reimplemented in zmq::pipe_t.
Definition at line 389 of file object.cpp.
References zmq_assert.
void zmq::object_t::process_activate_write (uint64_t msgs_read_) [protected, virtual, inherited]
Reimplemented in zmq::pipe_t.
Definition at line 394 of file object.cpp.
References zmq_assert.
void zmq::object_t::process_bind (class pipe_t * pipe_) [protected, virtual, inherited]
Reimplemented in zmq::socket_base_t.
Definition at line 384 of file object.cpp.
References zmq_assert.
void zmq::object_t::process_command (struct command_t & cmd_) [inherited]
Definition at line 58 of file object.cpp.
References zmq::command_t::activate_read, zmq::command_t::activate_write, zmq::command_t::args, zmq::command_t::attach, zmq::command_t::bind, zmq::command_t::hiccup, zmq::command_t::own, zmq::command_t::pipe_term, zmq::command_t::pipe_term_ack, zmq::command_t::plug, zmq::command_t::reap, zmq::command_t::reaped, zmq::command_t::stop, zmq::command_t::term, zmq::command_t::term_ack, zmq::command_t::term_req, zmq::command_t::type, and zmq_assert.
Referenced by zmq::reaper_t::in_event(), zmq::io_thread_t::in_event(), and zmq::socket_base_t::process_commands().
void zmq::own_t::process_destroy () [protected, virtual, inherited]
Reimplemented in zmq::socket_base_t.
Definition at line 215 of file own.cpp.
Referenced by zmq::socket_base_t::check_destroy().
void zmq::object_t::process_hiccup (void * pipe_) [protected, virtual, inherited]
Reimplemented in zmq::pipe_t.
Definition at line 399 of file object.cpp.
References zmq_assert.
void zmq::object_t::process_pipe_term () [protected, virtual, inherited]
Reimplemented in zmq::pipe_t.
Definition at line 404 of file object.cpp.
References zmq_assert.
void zmq::object_t::process_pipe_term_ack () [protected, virtual, inherited]
Reimplemented in zmq::pipe_t.
Definition at line 409 of file object.cpp.
References zmq_assert.
void zmq::object_t::process_reap (class socket_base_t * socket_) [protected, virtual, inherited]
Reimplemented in zmq::reaper_t.
Definition at line 429 of file object.cpp.
References zmq_assert.
void zmq::object_t::process_reaped () [protected, virtual, inherited]
Reimplemented in zmq::reaper_t.
Definition at line 434 of file object.cpp.
References zmq_assert.
void zmq::object_t::process_stop () [protected, virtual, inherited]
Reimplemented in zmq::io_thread_t, zmq::reaper_t, and zmq::socket_base_t.
Definition at line 364 of file object.cpp.
References zmq_assert.
int zmq::session_base_t::read (msg_t * msg_) [virtual, inherited]
Definition at line 151 of file session_base.cpp.
References zmq::msg_t::flags, zmq::msg_t::label, and zmq::msg_t::more.
void zmq::session_base_t::read_activated (class pipe_t * pipe_) [virtual, inherited]
Implements zmq::i_pipe_events.
Definition at line 218 of file session_base.cpp.
References likely, and zmq_assert.
int zmq::object_t::register_endpoint (const char * addr_, struct endpoint_t & endpoint_) [protected, inherited]
Definition at line 131 of file object.cpp.
void zmq::own_t::register_term_acks (int count_) [inherited]
Definition at line 178 of file own.cpp.
void zmq::io_object_t::reset_pollin (handle_t handle_) [protected, inherited]
Definition at line 69 of file io_object.cpp.
void zmq::io_object_t::reset_pollout (handle_t handle_) [protected, inherited]
Definition at line 79 of file io_object.cpp.
void zmq::io_object_t::rm_fd (handle_t handle_) [protected, inherited]
Definition at line 59 of file io_object.cpp.
void zmq::object_t::send_activate_read (class pipe_t * destination_) [protected, inherited]
Definition at line 236 of file object.cpp.
References zmq::command_t::activate_read, zmq::command_t::destination, and zmq::command_t::type.
void zmq::object_t::send_activate_write (class pipe_t * destination_, uint64_t msgs_read_) [protected, inherited]
Definition at line 247 of file object.cpp.
References zmq::command_t::activate_write, zmq::command_t::args, zmq::command_t::destination, and zmq::command_t::type.
void zmq::object_t::send_attach (class session_base_t * destination_, struct i_engine * engine_, bool inc_seqnum_ = true) [protected, inherited]
Definition at line 204 of file object.cpp.
References zmq::command_t::args, zmq::command_t::attach, zmq::command_t::destination, zmq::own_t::inc_seqnum(), and zmq::command_t::type.
void zmq::object_t::send_bind (class own_t * destination_, class pipe_t * pipe_, bool inc_seqnum_ = true) [protected, inherited]
Definition at line 220 of file object.cpp.
References zmq::command_t::args, zmq::command_t::bind, zmq::command_t::destination, zmq::own_t::inc_seqnum(), and zmq::command_t::type.
void zmq::object_t::send_done () [protected, inherited]
Definition at line 353 of file object.cpp.
References zmq::command_t::destination, zmq::command_t::done, zmq::ctx_t::term_tid, and zmq::command_t::type.
void zmq::object_t::send_hiccup (class pipe_t * destination_, void * pipe_) [protected, inherited]
Definition at line 260 of file object.cpp.
References zmq::command_t::args, zmq::command_t::destination, zmq::command_t::hiccup, and zmq::command_t::type.
void zmq::object_t::send_own (class own_t * destination_, class own_t * object_) [protected, inherited]
Definition at line 191 of file object.cpp.
References zmq::command_t::args, zmq::command_t::destination, zmq::own_t::inc_seqnum(), zmq::command_t::own, and zmq::command_t::type.
void zmq::object_t::send_pipe_term (class pipe_t * destination_) [protected, inherited]
Definition at line 272 of file object.cpp.
References zmq::command_t::destination, zmq::command_t::pipe_term, and zmq::command_t::type.
void zmq::object_t::send_pipe_term_ack (class pipe_t * destination_) [protected, inherited]
Definition at line 283 of file object.cpp.
References zmq::command_t::destination, zmq::command_t::pipe_term_ack, and zmq::command_t::type.
void zmq::object_t::send_plug (class own_t * destination_, bool inc_seqnum_ = true) [protected, inherited]
Definition at line 177 of file object.cpp.
References zmq::command_t::destination, zmq::own_t::inc_seqnum(), zmq::command_t::plug, and zmq::command_t::type.
void zmq::object_t::send_reap (class socket_base_t * socket_) [protected, inherited]
Definition at line 330 of file object.cpp.
References zmq::command_t::args, zmq::command_t::destination, zmq::command_t::reap, and zmq::command_t::type.
void zmq::object_t::send_reaped () [protected, inherited]
Definition at line 342 of file object.cpp.
References zmq::command_t::destination, zmq::command_t::reaped, and zmq::command_t::type.
void zmq::object_t::send_stop () [protected, inherited]
Definition at line 164 of file object.cpp.
References zmq::command_t::destination, zmq::command_t::stop, and zmq::command_t::type.
void zmq::object_t::send_term (class own_t * destination_, int linger_) [protected, inherited]
Definition at line 307 of file object.cpp.
References zmq::command_t::args, zmq::command_t::destination, zmq::command_t::term, and zmq::command_t::type.
void zmq::object_t::send_term_ack (class own_t * destination_) [protected, inherited]
Definition at line 319 of file object.cpp.
References zmq::command_t::destination, zmq::command_t::term_ack, and zmq::command_t::type.
void zmq::object_t::send_term_req (class own_t * destination_, class own_t * object_) [protected, inherited]
Definition at line 294 of file object.cpp.
References zmq::command_t::args, zmq::command_t::destination, zmq::command_t::term_req, and zmq::command_t::type.
void zmq::io_object_t::set_pollin (handle_t handle_) [protected, inherited]
Definition at line 64 of file io_object.cpp.
void zmq::io_object_t::set_pollout (handle_t handle_) [protected, inherited]
Definition at line 74 of file io_object.cpp.
void zmq::own_t::terminate () [protected, inherited]
Definition at line 138 of file own.cpp.
void zmq::session_base_t::terminated (class pipe_t * pipe_) [virtual, inherited]
Implements zmq::i_pipe_events.
Definition at line 205 of file session_base.cpp.
References zmq_assert.
void zmq::io_object_t::unplug () [inherited]
Reimplemented in zmq::stream_engine_t.
Definition at line 45 of file io_object.cpp.
References zmq_assert.
Referenced by zmq::stream_engine_t::unplug().
void zmq::object_t::unregister_endpoints (class socket_base_t * socket_) [protected, inherited]
Definition at line 136 of file object.cpp.
void zmq::own_t::unregister_term_ack () [inherited]
Definition at line 183 of file own.cpp.
References zmq_assert.
int zmq::session_base_t::write (msg_t * msg_) [virtual, inherited]
Reimplemented in zmq::req_session_t.
Definition at line 163 of file session_base.cpp.
References errno_assert, and zmq::msg_t::init().
Referenced by zmq::req_session_t::write().
void zmq::session_base_t::write_activated (class pipe_t * pipe_) [virtual, inherited]
Implements zmq::i_pipe_events.
Definition at line 228 of file session_base.cpp.
References zmq_assert.
Member Data Documentation
options_t zmq::own_t::options [protected, inherited]
Definition at line 98 of file own.hpp.
Referenced by zmq::pair_t::pair_t(), zmq::pub_t::pub_t(), zmq::pull_t::pull_t(), zmq::push_t::push_t(), zmq::rep_t::rep_t(), zmq::req_t::req_t(), zmq::router_t::router_t(), zmq::sub_t::sub_t(), zmq::xpub_t::xpub_t(), zmq::xrep_t::xrep_t(), zmq::xreq_t::xreq_t(), and zmq::xsub_t::xsub_t().
The documentation for this class was generated from the following files:
libzmq/doxygen/src/sub.hpp
libzmq/doxygen/src/sub.cpp