libzmq: zmq::zmq_connecter_t Class Reference
zmq::zmq_connecter_t Class Reference
#include <zmq_connecter.hpp>
Public Member Functions
zmq_connecter_t (class io_thread_t *io_thread_, class session_t *session_, const options_t &options_, const char *protocol_, const char *address_, bool delay_)
~zmq_connecter_t ()
ctx_t * get_ctx ()
uint32_t get_tid ()
void inc_seqnum ()
void plug (class io_thread_t *io_thread_)
void process_command (struct command_t &cmd_)
void register_term_acks (int count_)
void unplug ()
void unregister_term_ack ()
Protected Types
typedef poller_t::handle_t handle_t
Protected Member Functions
handle_t add_fd (fd_t fd_)
void add_timer (int timout_, int id_)
void cancel_timer (int id_)
class io_thread_t * choose_io_thread (uint64_t affinity_)
void destroy_socket (class socket_base_t *socket_)
struct endpoint_t find_endpoint (const char *addr_)
void launch_child (own_t *object_)
void launch_sibling (own_t *object_)
void log (const char *format_,...)
virtual void process_activate_reader ()
virtual void process_activate_writer (uint64_t msgs_read_)
virtual void process_attach (struct i_engine *engine_, const blob_t &peer_identity_)
virtual void process_bind (class reader_t *in_pipe_, class writer_t *out_pipe_, const blob_t &peer_identity_)
virtual void process_destroy ()
virtual void process_pipe_term ()
virtual void process_pipe_term_ack ()
virtual void process_reap (class socket_base_t *socket_)
virtual void process_reaped ()
virtual void process_stop ()
void process_term (int linger_)
int register_endpoint (const char *addr_, struct endpoint_t &endpoint_)
void reset_pollin (handle_t handle_)
void reset_pollout (handle_t handle_)
void rm_fd (handle_t handle_)
void send_activate_reader (class reader_t *destination_)
void send_activate_writer (class writer_t *destination_, uint64_t msgs_read_)
void send_attach (class session_t *destination_, struct i_engine *engine_, const blob_t &peer_identity_, bool inc_seqnum_=true)
void send_bind (class own_t *destination_, class reader_t *in_pipe_, class writer_t *out_pipe_, const blob_t &peer_identity_, bool inc_seqnum_=true)
void send_done ()
void send_own (class own_t *destination_, class own_t *object_)
void send_pipe_term (class writer_t *destination_)
void send_pipe_term_ack (class reader_t *destination_)
void send_plug (class own_t *destination_, bool inc_seqnum_=true)
void send_reap (class socket_base_t *socket_)
void send_reaped ()
void send_stop ()
void send_term (class own_t *destination_, int linger_)
void send_term_ack (class own_t *destination_)
void send_term_req (class own_t *destination_, class own_t *object_)
void set_pollin (handle_t handle_)
void set_pollout (handle_t handle_)
void terminate ()
void unregister_endpoints (class socket_base_t *socket_)
Protected Attributes
options_t options
Private Types
enum { reconnect_timer_id = 1 }
Private Member Functions
zmq_connecter_t (const zmq_connecter_t &)
void add_reconnect_timer ()
int get_new_reconnect_ivl ()
void in_event ()
const zmq_connecter_t & operator= (const zmq_connecter_t &)
void out_event ()
void process_plug ()
void start_connecting ()
void timer_event (int id_)
Private Attributes
int current_reconnect_ivl
handle_t handle
bool handle_valid
class session_t * session
tcp_connecter_t tcp_connecter
bool wait
Detailed Description
Definition at line 32 of file zmq_connecter.hpp.
Member Typedef Documentation
typedef poller_t::handle_t zmq::io_object_t::handle_t [protected, inherited]
Definition at line 51 of file io_object.hpp.
Member Enumeration Documentation
anonymous enum [private]
Enumerator:
reconnect_timer_id
Definition at line 46 of file zmq_connecter.hpp.
{reconnect_timer_id = 1};
Constructor & Destructor Documentation
zmq::zmq_connecter_t::zmq_connecter_t (class io_thread_t * io_thread_, class session_t * session_, const options_t & options_, const char * protocol_, const char * address_, bool delay_)
Definition at line 37 of file zmq_connecter.cpp.
References zmq::tcp_connecter_t::set_address(), tcp_connecter, and zmq_assert.
                                                               :
    own_t (io_thread_, options_),
    io_object_t (io_thread_),
    handle_valid (false),
    wait (wait_),
    session (session_),
    current_reconnect_ivl(options.reconnect_ivl)
{
    int rc = tcp_connecter.set_address (protocol_, address_);
    zmq_assert (rc == 0); //TODO: take care ENOMEM, EINVAL
}
zmq::zmq_connecter_t::~zmq_connecter_t ()
Definition at line 51 of file zmq_connecter.cpp.
{
    if (wait)
        cancel_timer (reconnect_timer_id);
    if (handle_valid)
        rm_fd (handle);
}
zmq::zmq_connecter_t::zmq_connecter_t (const zmq_connecter_t &) [private]
Member Function Documentation
zmq::io_object_t::handle_t zmq::io_object_t::add_fd (fd_t fd_) [protected, inherited]
Definition at line 54 of file io_object.cpp.
{
    return poller->add_fd (fd_, this);
}
void zmq::zmq_connecter_t::add_reconnect_timer () [private]
Definition at line 137 of file zmq_connecter.cpp.
{
    add_timer (get_new_reconnect_ivl(), reconnect_timer_id);
}
void zmq::io_object_t::add_timer (int timout_, int id_) [protected, inherited]
Definition at line 84 of file io_object.cpp.
{
    poller->add_timer (timeout_, this, id_);
}
void zmq::io_object_t::cancel_timer (int id_) [protected, inherited]
Definition at line 89 of file io_object.cpp.
{
    poller->cancel_timer (this, id_);
}
zmq::io_thread_t * zmq::object_t::choose_io_thread (uint64_t affinity_) [protected, inherited]
Definition at line 164 of file object.cpp.
References zmq::object_t::choose_io_thread().
Referenced by zmq::object_t::choose_io_thread().
{
    return ctx->choose_io_thread (affinity_);
}
void zmq::object_t::destroy_socket (class socket_base_t * socket_) [protected, inherited]
Definition at line 151 of file object.cpp.
{
    ctx->destroy_socket (socket_);
}
zmq::endpoint_t zmq::object_t::find_endpoint (const char * addr_) [read, protected, inherited]
Definition at line 146 of file object.cpp.
{
    return ctx->find_endpoint (addr_);
}
zmq::ctx_t * zmq::object_t::get_ctx () [inherited]
Definition at line 53 of file object.cpp.
{
    return ctx;
}
int zmq::zmq_connecter_t::get_new_reconnect_ivl () [private]
Definition at line 142 of file zmq_connecter.cpp.
{
#if defined ZMQ_HAVE_WINDOWS
    int pid = (int) GetCurrentProcessId ();
#else
    int pid = (int) getpid ();
#endif
    //  The new interval is the current interval + random value.
    int this_interval = current_reconnect_ivl +
        ((pid * 13) % options.reconnect_ivl);
    //  Only change the current reconnect interval  if the maximum reconnect
    //  interval was set and if it's larger than the reconnect interval.
    if (options.reconnect_ivl_max > 0 &&
        options.reconnect_ivl_max > options.reconnect_ivl) {
        //  Calculate the next interval
        current_reconnect_ivl = current_reconnect_ivl * 2;
        if(current_reconnect_ivl >= options.reconnect_ivl_max) {
            current_reconnect_ivl = options.reconnect_ivl_max;
        }
    }
    return this_interval;
}
uint32_t zmq::object_t::get_tid () [inherited]
Definition at line 48 of file object.cpp.
Referenced by zmq::ctx_t::destroy_socket(), and zmq::object_t::send_command().
{
    return tid;
}
void zmq::zmq_connecter_t::in_event () [private, virtual]
Reimplemented from zmq::io_object_t.
Definition at line 67 of file zmq_connecter.cpp.
{
    //  We are not polling for incomming data, so we are actually called
    //  because of error here. However, we can get error on out event as well
    //  on some platforms, so we'll simply handle both events in the same way.
    out_event ();
}
void zmq::own_t::inc_seqnum () [inherited]
Definition at line 56 of file own.cpp.
Referenced by zmq::ctx_t::find_endpoint(), zmq::socket_base_t::find_session(), zmq::object_t::send_attach(), zmq::object_t::send_bind(), zmq::object_t::send_own(), and zmq::object_t::send_plug().
{
    //  This function may be called from a different thread!
    sent_seqnum.add (1);
}
void zmq::own_t::launch_child (own_t * object_) [protected, inherited]
Definition at line 71 of file own.cpp.
References zmq::own_t::set_owner().
{
    //  Specify the owner of the object.
    object_->set_owner (this);
    //  Plug the object into the I/O thread.
    send_plug (object_);
    //  Take ownership of the object.
    send_own (this, object_);
}
void zmq::own_t::launch_sibling (own_t * object_) [protected, inherited]
Definition at line 83 of file own.cpp.
References zmq::own_t::set_owner().
{
    //  At this point it is important that object is plugged in before its
    //  owner has a chance to terminate it. Thus, 'plug' command is sent before
    //  the 'own' command. Given that the mailbox preserves ordering of
    //  commands, 'term' command from the owner cannot make it to the object
    //  before the already written 'plug' command.
    //  Specify the owner of the object.
    object_->set_owner (owner);
    //  Plug the object into its I/O thread.
    send_plug (object_);
    //  Make parent own the object.
    send_own (owner, object_);
}
void zmq::object_t::log (const char * format_, ...) [protected, inherited]
Definition at line 156 of file object.cpp.
{
    va_list args;
    va_start (args, format_);
    ctx->log (format_, args);
    va_end (args);
}
const zmq_connecter_t& zmq::zmq_connecter_t::operator= (const zmq_connecter_t &) [private]
void zmq::zmq_connecter_t::out_event () [private, virtual]
Reimplemented from zmq::io_object_t.
Definition at line 75 of file zmq_connecter.cpp.
References alloc_assert, zmq::retired_fd, and zmq_assert.
{
    fd_t fd = tcp_connecter.connect ();
    rm_fd (handle);
    handle_valid = false;
    //  Handle the error condition by attempt to reconnect.
    if (fd == retired_fd) {
        tcp_connecter.close ();
        wait = true;
        add_reconnect_timer();
        return;
    }
    //  Choose I/O thread to run connecter in. Given that we are already
    //  running in an I/O thread, there must be at least one available.
    io_thread_t *io_thread = choose_io_thread (options.affinity);
    zmq_assert (io_thread);
    //  Create an init object.
    zmq_init_t *init = new (std::nothrow) zmq_init_t (io_thread, NULL,
        session, fd, options);
    alloc_assert (init);
    launch_sibling (init);
    //  Shut the connecter down.
    terminate ();
}
void zmq::io_object_t::plug (class io_thread_t * io_thread_) [inherited]
Definition at line 36 of file io_object.cpp.
References zmq::io_thread_t::get_poller(), and zmq_assert.
Referenced by zmq::io_object_t::io_object_t(), and zmq::zmq_engine_t::plug().
{
    zmq_assert (io_thread_);
    zmq_assert (!poller);
    //  Retrieve the poller from the thread we are running in.
    poller = io_thread_->get_poller ();
}
void zmq::object_t::process_activate_reader () [protected, virtual, inherited]
Reimplemented in zmq::reader_t.
Definition at line 413 of file object.cpp.
References zmq_assert.
{
    zmq_assert (false);
}
void zmq::object_t::process_activate_writer (uint64_t msgs_read_) [protected, virtual, inherited]
Reimplemented in zmq::writer_t.
Definition at line 418 of file object.cpp.
References zmq_assert.
{
    zmq_assert (false);
}
void zmq::object_t::process_attach (struct i_engine * engine_, const blob_t & peer_identity_) [protected, virtual, inherited]
Reimplemented in zmq::session_t.
Definition at line 401 of file object.cpp.
References zmq_assert.
{
    zmq_assert (false);
}
void zmq::object_t::process_bind (class reader_t * in_pipe_, class writer_t * out_pipe_, const blob_t & peer_identity_) [protected, virtual, inherited]
Reimplemented in zmq::socket_base_t.
Definition at line 407 of file object.cpp.
References zmq_assert.
{
    zmq_assert (false);
}
void zmq::object_t::process_command (struct command_t & cmd_) [inherited]
Definition at line 58 of file object.cpp.
References zmq::command_t::activate_reader, zmq::command_t::activate_writer, zmq::command_t::args, zmq::command_t::attach, zmq::command_t::bind, zmq::deallocate_command(), zmq::command_t::own, zmq::command_t::pipe_term, zmq::command_t::pipe_term_ack, zmq::command_t::plug, zmq::command_t::reap, zmq::command_t::reaped, zmq::command_t::stop, zmq::command_t::term, zmq::command_t::term_ack, zmq::command_t::term_req, zmq::command_t::type, and zmq_assert.
Referenced by zmq::reaper_t::in_event(), zmq::io_thread_t::in_event(), and zmq::socket_base_t::process_commands().
{
    switch (cmd_.type) {
    case command_t::activate_reader:
        process_activate_reader ();
        break;
    case command_t::activate_writer:
        process_activate_writer (cmd_.args.activate_writer.msgs_read);
        break;
    case command_t::stop:
        process_stop ();
        break;
    case command_t::plug:
        process_plug ();
        process_seqnum ();
        return;
    case command_t::own:
        process_own (cmd_.args.own.object);
        process_seqnum ();
        break;
    case command_t::attach:
        process_attach (cmd_.args.attach.engine,
            cmd_.args.attach.peer_identity ?
            blob_t (cmd_.args.attach.peer_identity,
            cmd_.args.attach.peer_identity_size) : blob_t ());
        process_seqnum ();
        break;
    case command_t::bind:
        process_bind (cmd_.args.bind.in_pipe, cmd_.args.bind.out_pipe,
            cmd_.args.bind.peer_identity ? blob_t (cmd_.args.bind.peer_identity,
            cmd_.args.bind.peer_identity_size) : blob_t ());
        process_seqnum ();
        break;
    case command_t::pipe_term:
        process_pipe_term ();
        return;
    case command_t::pipe_term_ack:
        process_pipe_term_ack ();
        break;
    case command_t::term_req:
        process_term_req (cmd_.args.term_req.object);
        break;
    case command_t::term:
        process_term (cmd_.args.term.linger);
        break;
    case command_t::term_ack:
        process_term_ack ();
        break;
    case command_t::reap:
        process_reap (cmd_.args.reap.socket);
        break;
    case command_t::reaped:
        process_reaped ();
        break;
    default:
        zmq_assert (false);
    }
    //  The assumption here is that each command is processed once only,
    //  so deallocating it after processing is all right.
    deallocate_command (&cmd_);
}
void zmq::own_t::process_destroy () [protected, virtual, inherited]
Reimplemented in zmq::socket_base_t.
Definition at line 210 of file own.cpp.
Referenced by zmq::socket_base_t::check_destroy().
{
    delete this;
}
void zmq::object_t::process_pipe_term () [protected, virtual, inherited]
Reimplemented in zmq::writer_t.
Definition at line 423 of file object.cpp.
References zmq_assert.
{
    zmq_assert (false);
}
void zmq::object_t::process_pipe_term_ack () [protected, virtual, inherited]
Reimplemented in zmq::reader_t.
Definition at line 428 of file object.cpp.
References zmq_assert.
{
    zmq_assert (false);
}
void zmq::zmq_connecter_t::process_plug () [private, virtual]
Reimplemented from zmq::object_t.
Definition at line 59 of file zmq_connecter.cpp.
{
    if (wait)
        add_reconnect_timer();
    else
        start_connecting ();
}
void zmq::object_t::process_reap (class socket_base_t * socket_) [protected, virtual, inherited]
Reimplemented in zmq::reaper_t.
Definition at line 448 of file object.cpp.
References zmq_assert.
{
    zmq_assert (false);
}
void zmq::object_t::process_reaped () [protected, virtual, inherited]
Reimplemented in zmq::reaper_t.
Definition at line 453 of file object.cpp.
References zmq_assert.
{
    zmq_assert (false);
}
void zmq::object_t::process_stop () [protected, virtual, inherited]
Reimplemented in zmq::io_thread_t, zmq::reaper_t, and zmq::socket_base_t.
Definition at line 386 of file object.cpp.
References zmq_assert.
{
    zmq_assert (false);
}
void zmq::own_t::process_term (int linger_) [protected, virtual, inherited]
Reimplemented from zmq::object_t.
Reimplemented in zmq::pair_t, zmq::pull_t, zmq::push_t, zmq::session_t, zmq::socket_base_t, zmq::xpub_t, zmq::xrep_t, zmq::xreq_t, zmq::xsub_t, and zmq::zmq_listener_t.
Definition at line 156 of file own.cpp.
References zmq_assert.
Referenced by zmq::session_t::proceed_with_term(), zmq::zmq_listener_t::process_term(), and zmq::socket_base_t::process_term().
{
    //  Double termination should never happen.
    zmq_assert (!terminating);
    //  Send termination request to all owned objects.
    for (owned_t::iterator it = owned.begin (); it != owned.end (); ++it)
        send_term (*it, linger_);
    register_term_acks ((int) owned.size ());
    owned.clear ();
    //  Start termination process and check whether by chance we cannot
    //  terminate immediately.
    terminating = true;
    check_term_acks ();
}
int zmq::object_t::register_endpoint (const char * addr_, struct endpoint_t & endpoint_) [protected, inherited]
Definition at line 136 of file object.cpp.
{
    return ctx->register_endpoint (addr_, endpoint_);
}
void zmq::own_t::register_term_acks (int count_) [inherited]
Definition at line 173 of file own.cpp.
{
    term_acks += count_;
}
void zmq::io_object_t::reset_pollin (handle_t handle_) [protected, inherited]
Definition at line 69 of file io_object.cpp.
{
    poller->reset_pollin (handle_);
}
void zmq::io_object_t::reset_pollout (handle_t handle_) [protected, inherited]
Definition at line 79 of file io_object.cpp.
{
    poller->reset_pollout (handle_);
}
void zmq::io_object_t::rm_fd (handle_t handle_) [protected, inherited]
Definition at line 59 of file io_object.cpp.
{
    poller->rm_fd (handle_);
}
void zmq::object_t::send_activate_reader (class reader_t * destination_) [protected, inherited]
Definition at line 270 of file object.cpp.
References zmq::command_t::activate_reader, zmq::command_t::destination, and zmq::command_t::type.
{
    command_t cmd;
#if defined ZMQ_MAKE_VALGRIND_HAPPY
    memset (&cmd, 0, sizeof (cmd));
#endif
    cmd.destination = destination_;
    cmd.type = command_t::activate_reader;
    send_command (cmd);
}
void zmq::object_t::send_activate_writer (class writer_t * destination_, uint64_t msgs_read_) [protected, inherited]
Definition at line 281 of file object.cpp.
References zmq::command_t::activate_writer, zmq::command_t::args, zmq::command_t::destination, and zmq::command_t::type.
{
    command_t cmd;
#if defined ZMQ_MAKE_VALGRIND_HAPPY
    memset (&cmd, 0, sizeof (cmd));
#endif
    cmd.destination = destination_;
    cmd.type = command_t::activate_writer;
    cmd.args.activate_writer.msgs_read = msgs_read_;
    send_command (cmd);
}
void zmq::object_t::send_attach (class session_t * destination_, struct i_engine * engine_, const blob_t & peer_identity_, bool inc_seqnum_ = true) [protected, inherited]
Definition at line 209 of file object.cpp.
References alloc_assert, zmq::command_t::args, zmq::command_t::attach, zmq::command_t::destination, zmq::own_t::inc_seqnum(), zmq::command_t::type, and zmq_assert.
{
    if (inc_seqnum_)
        destination_->inc_seqnum ();
    command_t cmd;
#if defined ZMQ_MAKE_VALGRIND_HAPPY
    memset (&cmd, 0, sizeof (cmd));
#endif
    cmd.destination = destination_;
    cmd.type = command_t::attach;
    cmd.args.attach.engine = engine_;
    if (peer_identity_.empty ()) {
        cmd.args.attach.peer_identity_size = 0;
        cmd.args.attach.peer_identity = NULL;
    }
    else {
        zmq_assert (peer_identity_.size () <= 0xff);
        cmd.args.attach.peer_identity_size =
            (unsigned char) peer_identity_.size ();
        cmd.args.attach.peer_identity =
            (unsigned char*) malloc (peer_identity_.size ());
        alloc_assert (cmd.args.attach.peer_identity_size);
        memcpy (cmd.args.attach.peer_identity, peer_identity_.data (),
            peer_identity_.size ());
    }
    send_command (cmd);
}
void zmq::object_t::send_bind (class own_t * destination_, class reader_t * in_pipe_, class writer_t * out_pipe_, const blob_t & peer_identity_, bool inc_seqnum_ = true) [protected, inherited]
Definition at line 239 of file object.cpp.
References alloc_assert, zmq::command_t::args, zmq::command_t::bind, zmq::command_t::destination, zmq::own_t::inc_seqnum(), zmq::command_t::type, and zmq_assert.
{
    if (inc_seqnum_)
        destination_->inc_seqnum ();
    command_t cmd;
#if defined ZMQ_MAKE_VALGRIND_HAPPY
    memset (&cmd, 0, sizeof (cmd));
#endif
    cmd.destination = destination_;
    cmd.type = command_t::bind;
    cmd.args.bind.in_pipe = in_pipe_;
    cmd.args.bind.out_pipe = out_pipe_;
    if (peer_identity_.empty ()) {
        cmd.args.bind.peer_identity_size = 0;
        cmd.args.bind.peer_identity = NULL;
    }
    else {
        zmq_assert (peer_identity_.size () <= 0xff);
        cmd.args.bind.peer_identity_size =
            (unsigned char) peer_identity_.size ();
        cmd.args.bind.peer_identity =
            (unsigned char*) malloc (peer_identity_.size ());
        alloc_assert (cmd.args.bind.peer_identity_size);
        memcpy (cmd.args.bind.peer_identity, peer_identity_.data (),
            peer_identity_.size ());
    }
    send_command (cmd);
}
void zmq::object_t::send_done () [protected, inherited]
Definition at line 375 of file object.cpp.
References zmq::command_t::destination, zmq::command_t::done, zmq::ctx_t::term_tid, and zmq::command_t::type.
{
    command_t cmd;
#if defined ZMQ_MAKE_VALGRIND_HAPPY
    memset (&cmd, 0, sizeof (cmd));
#endif
    cmd.destination = NULL;
    cmd.type = command_t::done;
    ctx->send_command (ctx_t::term_tid, cmd);
}
void zmq::object_t::send_own (class own_t * destination_, class own_t * object_) [protected, inherited]
Definition at line 196 of file object.cpp.
References zmq::command_t::args, zmq::command_t::destination, zmq::own_t::inc_seqnum(), zmq::command_t::own, and zmq::command_t::type.
{
    destination_->inc_seqnum ();
    command_t cmd;
#if defined ZMQ_MAKE_VALGRIND_HAPPY
    memset (&cmd, 0, sizeof (cmd));
#endif
    cmd.destination = destination_;
    cmd.type = command_t::own;
    cmd.args.own.object = object_;
    send_command (cmd);
}
void zmq::object_t::send_pipe_term (class writer_t * destination_) [protected, inherited]
Definition at line 294 of file object.cpp.
References zmq::command_t::destination, zmq::command_t::pipe_term, and zmq::command_t::type.
{
    command_t cmd;
#if defined ZMQ_MAKE_VALGRIND_HAPPY
    memset (&cmd, 0, sizeof (cmd));
#endif
    cmd.destination = destination_;
    cmd.type = command_t::pipe_term;
    send_command (cmd);
}
void zmq::object_t::send_pipe_term_ack (class reader_t * destination_) [protected, inherited]
Definition at line 305 of file object.cpp.
References zmq::command_t::destination, zmq::command_t::pipe_term_ack, and zmq::command_t::type.
{
    command_t cmd;
#if defined ZMQ_MAKE_VALGRIND_HAPPY
    memset (&cmd, 0, sizeof (cmd));
#endif
    cmd.destination = destination_;
    cmd.type = command_t::pipe_term_ack;
    send_command (cmd);
}
void zmq::object_t::send_plug (class own_t * destination_, bool inc_seqnum_ = true) [protected, inherited]
Definition at line 182 of file object.cpp.
References zmq::command_t::destination, zmq::own_t::inc_seqnum(), zmq::command_t::plug, and zmq::command_t::type.
{
    if (inc_seqnum_)
        destination_->inc_seqnum ();
    command_t cmd;
#if defined ZMQ_MAKE_VALGRIND_HAPPY
    memset (&cmd, 0, sizeof (cmd));
#endif
    cmd.destination = destination_;
    cmd.type = command_t::plug;
    send_command (cmd);
}
void zmq::object_t::send_reap (class socket_base_t * socket_) [protected, inherited]
Definition at line 352 of file object.cpp.
References zmq::command_t::args, zmq::command_t::destination, zmq::command_t::reap, and zmq::command_t::type.
{
    command_t cmd;
#if defined ZMQ_MAKE_VALGRIND_HAPPY
    memset (&cmd, 0, sizeof (cmd));
#endif
    cmd.destination = ctx->get_reaper ();
    cmd.type = command_t::reap;
    cmd.args.reap.socket = socket_;
    send_command (cmd);
}
void zmq::object_t::send_reaped () [protected, inherited]
Definition at line 364 of file object.cpp.
References zmq::command_t::destination, zmq::command_t::reaped, and zmq::command_t::type.
{
    command_t cmd;
#if defined ZMQ_MAKE_VALGRIND_HAPPY
    memset (&cmd, 0, sizeof (cmd));
#endif
    cmd.destination = ctx->get_reaper ();
    cmd.type = command_t::reaped;
    send_command (cmd);
}
void zmq::object_t::send_stop () [protected, inherited]
Definition at line 169 of file object.cpp.
References zmq::command_t::destination, zmq::command_t::stop, and zmq::command_t::type.
{
    //  'stop' command goes always from administrative thread to
    //  the current object.
    command_t cmd;
#if defined ZMQ_MAKE_VALGRIND_HAPPY
    memset (&cmd, 0, sizeof (cmd));
#endif
    cmd.destination = this;
    cmd.type = command_t::stop;
    ctx->send_command (tid, cmd);
}
void zmq::object_t::send_term (class own_t * destination_, int linger_) [protected, inherited]
Definition at line 329 of file object.cpp.
References zmq::command_t::args, zmq::command_t::destination, zmq::command_t::term, and zmq::command_t::type.
{
    command_t cmd;
#if defined ZMQ_MAKE_VALGRIND_HAPPY
    memset (&cmd, 0, sizeof (cmd));
#endif
    cmd.destination = destination_;
    cmd.type = command_t::term;
    cmd.args.term.linger = linger_;
    send_command (cmd);
}
void zmq::object_t::send_term_ack (class own_t * destination_) [protected, inherited]
Definition at line 341 of file object.cpp.
References zmq::command_t::destination, zmq::command_t::term_ack, and zmq::command_t::type.
{
    command_t cmd;
#if defined ZMQ_MAKE_VALGRIND_HAPPY
    memset (&cmd, 0, sizeof (cmd));
#endif
    cmd.destination = destination_;
    cmd.type = command_t::term_ack;
    send_command (cmd);
}
void zmq::object_t::send_term_req (class own_t * destination_, class own_t * object_) [protected, inherited]
Definition at line 316 of file object.cpp.
References zmq::command_t::args, zmq::command_t::destination, zmq::command_t::term_req, and zmq::command_t::type.
{
    command_t cmd;
#if defined ZMQ_MAKE_VALGRIND_HAPPY
    memset (&cmd, 0, sizeof (cmd));
#endif
    cmd.destination = destination_;
    cmd.type = command_t::term_req;
    cmd.args.term_req.object = object_;
    send_command (cmd);
}
void zmq::io_object_t::set_pollin (handle_t handle_) [protected, inherited]
Definition at line 64 of file io_object.cpp.
{
    poller->set_pollin (handle_);
}
void zmq::io_object_t::set_pollout (handle_t handle_) [protected, inherited]
Definition at line 74 of file io_object.cpp.
{
    poller->set_pollout (handle_);
}
void zmq::zmq_connecter_t::start_connecting () [private]
Definition at line 111 of file zmq_connecter.cpp.
{
    //  Open the connecting socket.
    int rc = tcp_connecter.open ();
    //  Connect may succeed in synchronous manner.
    if (rc == 0) {
        handle = add_fd (tcp_connecter.get_fd ());
        handle_valid = true;
        out_event ();
        return;
    }
    //  Connection establishment may be dealyed. Poll for its completion.
    else if (rc == -1 && errno == EAGAIN) {
        handle = add_fd (tcp_connecter.get_fd ());
        handle_valid = true;
        set_pollout (handle);
        return;
    }
    //  Handle any other error condition by eventual reconnect.
    wait = true;
    add_reconnect_timer();
}
void zmq::own_t::terminate () [protected, inherited]
Reimplemented in zmq::session_t.
Definition at line 138 of file own.cpp.
Referenced by zmq::reaper_t::process_reap(), and zmq::session_t::terminate().
{
    //  If termination is already underway, there's no point
    //  in starting it anew.
    if (terminating)
        return;
    //  As for the root of the ownership tree, there's noone to terminate it,
    //  so it has to terminate itself.
    if (!owner) {
        process_term (options.linger);
        return;
    }
    //  If I am an owned object, I'll ask my owner to terminate me.
    send_term_req (owner, this);
}
void zmq::zmq_connecter_t::timer_event (int id_) [private, virtual]
Reimplemented from zmq::io_object_t.
Definition at line 104 of file zmq_connecter.cpp.
References zmq_assert.
{
    zmq_assert (id_ == reconnect_timer_id);
    wait = false;
    start_connecting ();
}
void zmq::io_object_t::unplug () [inherited]
Reimplemented in zmq::zmq_engine_t.
Definition at line 45 of file io_object.cpp.
References zmq_assert.
Referenced by zmq::zmq_engine_t::unplug().
{
    zmq_assert (poller);
    //  Forget about old poller in preparation to be migrated
    //  to a different I/O thread.
    poller = NULL;
}
void zmq::object_t::unregister_endpoints (class socket_base_t * socket_) [protected, inherited]
Definition at line 141 of file object.cpp.
{
    return ctx->unregister_endpoints (socket_);
}
void zmq::own_t::unregister_term_ack () [inherited]
Definition at line 178 of file own.cpp.
References zmq_assert.
{
    zmq_assert (term_acks > 0);
    term_acks--;
    //  This may be a last ack we are waiting for before termination...
    check_term_acks ();
}
Member Data Documentation
int zmq::zmq_connecter_t::current_reconnect_ivl [private]
Definition at line 84 of file zmq_connecter.hpp.
handle_t zmq::zmq_connecter_t::handle [private]
Definition at line 71 of file zmq_connecter.hpp.
bool zmq::zmq_connecter_t::handle_valid [private]
Definition at line 75 of file zmq_connecter.hpp.
options_t zmq::own_t::options [protected, inherited]
Definition at line 95 of file own.hpp.
Referenced by zmq::pair_t::pair_t(), zmq::pub_t::pub_t(), zmq::pull_t::pull_t(), zmq::push_t::push_t(), zmq::rep_t::rep_t(), zmq::req_t::req_t(), zmq::sub_t::sub_t(), zmq::xpub_t::xpub_t(), zmq::xrep_t::xrep_t(), zmq::xreq_t::xreq_t(), zmq::xsub_t::xsub_t(), and zmq::zmq_init_t::zmq_init_t().
class session_t* zmq::zmq_connecter_t::session [private]
Definition at line 81 of file zmq_connecter.hpp.
tcp_connecter_t zmq::zmq_connecter_t::tcp_connecter [private]
Definition at line 68 of file zmq_connecter.hpp.
Referenced by zmq_connecter_t().
bool zmq::zmq_connecter_t::wait [private]
Definition at line 78 of file zmq_connecter.hpp.
The documentation for this class was generated from the following files:
/home/travlr/src/libzmq/src/zmq_connecter.hpp
/home/travlr/src/libzmq/src/zmq_connecter.cpp