libzmq: zmq::io_object_t Class Reference
zmq::io_object_t Class Reference
#include <io_object.hpp>
Public Member Functions
io_object_t (class io_thread_t *io_thread_=NULL)
~io_object_t ()
void plug (class io_thread_t *io_thread_)
void unplug ()
Protected Types
typedef poller_t::handle_t handle_t
Protected Member Functions
handle_t add_fd (fd_t fd_)
void add_timer (int timout_, int id_)
void cancel_timer (int id_)
void in_event ()
void out_event ()
void reset_pollin (handle_t handle_)
void reset_pollout (handle_t handle_)
void rm_fd (handle_t handle_)
void set_pollin (handle_t handle_)
void set_pollout (handle_t handle_)
void timer_event (int id_)
Private Member Functions
io_object_t (const io_object_t &)
const io_object_t & operator= (const io_object_t &)
Private Attributes
poller_t * poller
Detailed Description
Definition at line 37 of file io_object.hpp.
Member Typedef Documentation
typedef poller_t::handle_t zmq::io_object_t::handle_t [protected]
Definition at line 51 of file io_object.hpp.
Constructor & Destructor Documentation
zmq::io_object_t::io_object_t (class io_thread_t * io_thread_ = NULL)
Definition at line 25 of file io_object.cpp.
References plug().
zmq::io_object_t::~io_object_t ()
Definition at line 32 of file io_object.cpp.
zmq::io_object_t::io_object_t (const io_object_t &) [private]
Member Function Documentation
zmq::io_object_t::handle_t zmq::io_object_t::add_fd (fd_t fd_) [protected]
Definition at line 54 of file io_object.cpp.
void zmq::io_object_t::add_timer (int timout_, int id_) [protected]
Definition at line 84 of file io_object.cpp.
void zmq::io_object_t::cancel_timer (int id_) [protected]
Definition at line 89 of file io_object.cpp.
void zmq::io_object_t::in_event () [protected, virtual]
Implements zmq::i_poll_events.
Reimplemented in zmq::zmq_connecter_t, zmq::zmq_engine_t, and zmq::zmq_listener_t.
Definition at line 94 of file io_object.cpp.
References zmq_assert.
const io_object_t& zmq::io_object_t::operator= (const io_object_t &) [private]
void zmq::io_object_t::out_event () [protected, virtual]
Implements zmq::i_poll_events.
Reimplemented in zmq::zmq_connecter_t, and zmq::zmq_engine_t.
Definition at line 99 of file io_object.cpp.
References zmq_assert.
void zmq::io_object_t::plug (class io_thread_t * io_thread_)
Definition at line 36 of file io_object.cpp.
References zmq::io_thread_t::get_poller(), and zmq_assert.
Referenced by io_object_t(), and zmq::zmq_engine_t::plug().
void zmq::io_object_t::reset_pollin (handle_t handle_) [protected]
Definition at line 69 of file io_object.cpp.
void zmq::io_object_t::reset_pollout (handle_t handle_) [protected]
Definition at line 79 of file io_object.cpp.
void zmq::io_object_t::rm_fd (handle_t handle_) [protected]
Definition at line 59 of file io_object.cpp.
void zmq::io_object_t::set_pollin (handle_t handle_) [protected]
Definition at line 64 of file io_object.cpp.
void zmq::io_object_t::set_pollout (handle_t handle_) [protected]
Definition at line 74 of file io_object.cpp.
void zmq::io_object_t::timer_event (int id_) [protected, virtual]
Implements zmq::i_poll_events.
Reimplemented in zmq::session_t, and zmq::zmq_connecter_t.
Definition at line 104 of file io_object.cpp.
References zmq_assert.
void zmq::io_object_t::unplug ()
Reimplemented in zmq::zmq_engine_t.
Definition at line 45 of file io_object.cpp.
References zmq_assert.
Referenced by zmq::zmq_engine_t::unplug().
Member Data Documentation
poller_t* zmq::io_object_t::poller [private]
Definition at line 70 of file io_object.hpp.
The documentation for this class was generated from the following files:
src/io_object.hpp
src/io_object.cpp