libzmq: zmq::mutex_t Class Reference
zmq::mutex_t Class Reference
#include <mutex.hpp>
Public Member Functions
mutex_t ()
~mutex_t ()
void lock ()
void unlock ()
Private Member Functions
mutex_t (const mutex_t &)
const mutex_t & operator= (const mutex_t &)
Private Attributes
pthread_mutex_t mutex
Detailed Description
Definition at line 77 of file mutex.hpp.
Constructor & Destructor Documentation
zmq::mutex_t::mutex_t () [inline]
Definition at line 80 of file mutex.hpp.
References mutex, and posix_assert.
zmq::mutex_t::~mutex_t () [inline]
Definition at line 87 of file mutex.hpp.
References mutex, and posix_assert.
zmq::mutex_t::mutex_t (const mutex_t &) [private]
Member Function Documentation
void zmq::mutex_t::lock () [inline]
Definition at line 94 of file mutex.hpp.
References mutex, and posix_assert.
Referenced by zmq::atomic_counter_t::add(), zmq::atomic_ptr_t< chunk_t >::cas(), zmq::atomic_counter_t::sub(), and zmq::atomic_ptr_t< chunk_t >::xchg().
const mutex_t& zmq::mutex_t::operator= (const mutex_t &) [private]
void zmq::mutex_t::unlock () [inline]
Definition at line 101 of file mutex.hpp.
References mutex, and posix_assert.
Referenced by zmq::atomic_counter_t::add(), zmq::atomic_ptr_t< chunk_t >::cas(), zmq::atomic_counter_t::sub(), and zmq::atomic_ptr_t< chunk_t >::xchg().
Member Data Documentation
pthread_mutex_t zmq::mutex_t::mutex [private]
Definition at line 110 of file mutex.hpp.
Referenced by lock(), mutex_t(), unlock(), and ~mutex_t().
The documentation for this class was generated from the following file:
src/mutex.hpp