libzmq: zmq::lb_t Class Reference
zmq::lb_t Class Reference
#include <lb.hpp>
Public Member Functions
lb_t (class own_t *sink_)
~lb_t ()
void activated (writer_t *pipe_)
void attach (writer_t *pipe_)
bool has_out ()
int send (msg_t *msg_, int flags_)
void terminate ()
void terminated (writer_t *pipe_)
Private Types
typedef array_t< class writer_t > pipes_t
Private Member Functions
lb_t (const lb_t &)
const lb_t & operator= (const lb_t &)
Private Attributes
pipes_t::size_type active
pipes_t::size_type current
bool dropping
bool more
pipes_t pipes
class own_t * sink
bool terminating
Detailed Description
Definition at line 32 of file lb.hpp.
Member Typedef Documentation
typedef array_t<class writer_t> zmq::lb_t::pipes_t [private]
Definition at line 51 of file lb.hpp.
Constructor & Destructor Documentation
zmq::lb_t::lb_t (class own_t * sink_)
Definition at line 27 of file lb.cpp.
                           :
    active (0),
    current (0),
    more (false),
    dropping (false),
    sink (sink_),
    terminating (false)
{
}
zmq::lb_t::~lb_t ()
Definition at line 37 of file lb.cpp.
References zmq_assert.
{
    zmq_assert (pipes.empty ());
}
zmq::lb_t::lb_t (const lb_t &) [private]
Member Function Documentation
void zmq::lb_t::activated (writer_t * pipe_) [virtual]
Implements zmq::i_writer_events.
Definition at line 88 of file lb.cpp.
{
    //  Move the pipe to the list of active pipes.
    pipes.swap (pipes.index (pipe_), active);
    active++;
}
void zmq::lb_t::attach (writer_t * pipe_)
Definition at line 42 of file lb.cpp.
References zmq::writer_t::set_event_sink(), and zmq::writer_t::terminate().
{
    pipe_->set_event_sink (this);
    pipes.push_back (pipe_);
    pipes.swap (active, pipes.size () - 1);
    active++;
    if (terminating) {
        sink->register_term_acks (1);
        pipe_->terminate ();
    }
}
bool zmq::lb_t::has_out ()
Definition at line 146 of file lb.cpp.
References zmq::msg_t::close(), errno_assert, and zmq::msg_t::init().
{
    //  If one part of the message was already written we can definitely
    //  write the rest of the message.
    if (more)
        return true;
    while (active > 0) {
        //  Check whether zero-sized message can be written to the pipe.
        msg_t msg;
        int rc = msg.init ();
        errno_assert (rc == 0);
        if (pipes [current]->check_write (&msg)) {
            rc = msg.close ();
            errno_assert (rc == 0);
            return true;
        }
        rc = msg.close ();
        errno_assert (rc == 0);
        //  Deactivate the pipe.
        active--;
        pipes.swap (current, active);
        if (current == active)
            current = 0;
    }
    return false;
}
const lb_t& zmq::lb_t::operator= (const lb_t &) [private]
int zmq::lb_t::send (msg_t * msg_, int flags_)
Definition at line 95 of file lb.cpp.
References zmq::msg_t::close(), errno_assert, zmq::msg_t::flags, zmq::msg_t::init(), zmq::msg_t::more, and zmq_assert.
{
    //  Drop the message if required. If we are at the end of the message
    //  switch back to non-dropping mode.
    if (dropping) {
        more = msg_->flags () & msg_t::more;
        if (!more)
            dropping = false;
        int rc = msg_->close ();
        errno_assert (rc == 0);
        rc = msg_->init ();
        zmq_assert (rc == 0);
        return 0;
    }
    while (active > 0) {
        if (pipes [current]->write (msg_)) {
            more = msg_->flags () & msg_t::more;
            break;
        }
        zmq_assert (!more);
        active--;
        if (current < active)
            pipes.swap (current, active);
        else
            current = 0;
    }
    //  If there are no pipes we cannot send the message.
    if (active == 0) {
        errno = EAGAIN;
        return -1;
    }
    //  If it's final part of the message we can fluch it downstream and
    //  continue round-robinning (load balance).
    if (!more) {
        pipes [current]->flush ();
        current = (current + 1) % active;
    }
    //  Detach the message from the data buffer.
    int rc = msg_->init ();
    errno_assert (rc == 0);
    return 0;
}
void zmq::lb_t::terminate ()
Definition at line 56 of file lb.cpp.
References zmq_assert.
{
    zmq_assert (!terminating);
    terminating = true;
    sink->register_term_acks ((int) pipes.size ());
    for (pipes_t::size_type i = 0; i != pipes.size (); i++)
        pipes [i]->terminate ();
}
void zmq::lb_t::terminated (writer_t * pipe_) [virtual]
Implements zmq::i_writer_events.
Definition at line 66 of file lb.cpp.
{
    pipes_t::size_type index = pipes.index (pipe_);
    //  If we are in the middle of multipart message and current pipe
    //  have disconnected, we have to drop the remainder of the message.
    if (index == current && more)
        dropping = true;
    //  Remove the pipe from the list; adjust number of active pipes
    //  accordingly.
    if (index < active) {
        active--;
        if (current == active)
            current = 0;
    }
    pipes.erase (pipe_);
    if (terminating)
        sink->unregister_term_ack ();
}
Member Data Documentation
pipes_t::size_type zmq::lb_t::active [private]
Definition at line 56 of file lb.hpp.
pipes_t::size_type zmq::lb_t::current [private]
Definition at line 59 of file lb.hpp.
bool zmq::lb_t::dropping [private]
Definition at line 65 of file lb.hpp.
bool zmq::lb_t::more [private]
Definition at line 62 of file lb.hpp.
pipes_t zmq::lb_t::pipes [private]
Definition at line 52 of file lb.hpp.
class own_t* zmq::lb_t::sink [private]
Definition at line 68 of file lb.hpp.
bool zmq::lb_t::terminating [private]
Definition at line 71 of file lb.hpp.
The documentation for this class was generated from the following files:
/home/travlr/src/libzmq/src/lb.hpp
/home/travlr/src/libzmq/src/lb.cpp