libzmq: zmq::zmq_engine_t Class Reference
zmq::zmq_engine_t Class Reference
#include <zmq_engine.hpp>
Public Member Functions
zmq_engine_t (fd_t fd_, const options_t &options_)
~zmq_engine_t ()
void activate_in ()
void activate_out ()
void in_event ()
void out_event ()
void plug (class io_thread_t *io_thread_)
void plug (class io_thread_t *io_thread_, class session_t *session_)
void terminate ()
void unplug ()
Protected Types
typedef poller_t::handle_t handle_t
Protected Member Functions
handle_t add_fd (fd_t fd_)
void add_timer (int timout_, int id_)
void cancel_timer (int id_)
void reset_pollin (handle_t handle_)
void reset_pollout (handle_t handle_)
void rm_fd (handle_t handle_)
void set_pollin (handle_t handle_)
void set_pollout (handle_t handle_)
void timer_event (int id_)
Private Member Functions
zmq_engine_t (const zmq_engine_t &)
void error ()
const zmq_engine_t & operator= (const zmq_engine_t &)
Private Attributes
decoder_t decoder
encoder_t encoder
handle_t handle
unsigned char * inpos
size_t insize
class session_t * leftover_session
options_t options
unsigned char * outpos
size_t outsize
bool plugged
class session_t * session
tcp_socket_t tcp_socket
Detailed Description
Definition at line 38 of file zmq_engine.hpp.
Member Typedef Documentation
typedef poller_t::handle_t zmq::io_object_t::handle_t [protected, inherited]
Definition at line 51 of file io_object.hpp.
Constructor & Destructor Documentation
zmq::zmq_engine_t::zmq_engine_t (fd_t fd_, const options_t & options_)
Definition at line 36 of file zmq_engine.cpp.
References zmq::tcp_socket_t::open(), options, zmq::options_t::rcvbuf, zmq::options_t::sndbuf, tcp_socket, and zmq_assert.
zmq::zmq_engine_t::~zmq_engine_t ()
Definition at line 53 of file zmq_engine.cpp.
References zmq_assert.
zmq::zmq_engine_t::zmq_engine_t (const zmq_engine_t &) [private]
Member Function Documentation
void zmq::zmq_engine_t::activate_in () [virtual]
Implements zmq::i_engine.
Definition at line 210 of file zmq_engine.cpp.
void zmq::zmq_engine_t::activate_out () [virtual]
Implements zmq::i_engine.
Definition at line 199 of file zmq_engine.cpp.
zmq::io_object_t::handle_t zmq::io_object_t::add_fd (fd_t fd_) [protected, inherited]
Definition at line 54 of file io_object.cpp.
void zmq::io_object_t::add_timer (int timout_, int id_) [protected, inherited]
Definition at line 84 of file io_object.cpp.
void zmq::io_object_t::cancel_timer (int id_) [protected, inherited]
Definition at line 89 of file io_object.cpp.
void zmq::zmq_engine_t::error () [private]
Definition at line 218 of file zmq_engine.cpp.
References zmq_assert.
void zmq::zmq_engine_t::in_event () [virtual]
Reimplemented from zmq::io_object_t.
Definition at line 105 of file zmq_engine.cpp.
References unlikely, and zmq_assert.
const zmq_engine_t& zmq::zmq_engine_t::operator= (const zmq_engine_t &) [private]
void zmq::zmq_engine_t::out_event () [virtual]
Reimplemented from zmq::io_object_t.
Definition at line 160 of file zmq_engine.cpp.
References unlikely, and zmq_assert.
void zmq::io_object_t::plug (class io_thread_t * io_thread_) [inherited]
Definition at line 36 of file io_object.cpp.
References zmq::io_thread_t::get_poller(), and zmq_assert.
Referenced by zmq::io_object_t::io_object_t(), and plug().
void zmq::zmq_engine_t::plug (class io_thread_t * io_thread_, class session_t * session_) [virtual]
Implements zmq::i_engine.
Definition at line 58 of file zmq_engine.cpp.
References zmq::io_object_t::plug(), and zmq_assert.
void zmq::io_object_t::reset_pollin (handle_t handle_) [protected, inherited]
Definition at line 69 of file io_object.cpp.
void zmq::io_object_t::reset_pollout (handle_t handle_) [protected, inherited]
Definition at line 79 of file io_object.cpp.
void zmq::io_object_t::rm_fd (handle_t handle_) [protected, inherited]
Definition at line 59 of file io_object.cpp.
void zmq::io_object_t::set_pollin (handle_t handle_) [protected, inherited]
Definition at line 64 of file io_object.cpp.
void zmq::io_object_t::set_pollout (handle_t handle_) [protected, inherited]
Definition at line 74 of file io_object.cpp.
void zmq::zmq_engine_t::terminate () [virtual]
Implements zmq::i_engine.
Definition at line 99 of file zmq_engine.cpp.
void zmq::io_object_t::timer_event (int id_) [protected, virtual, inherited]
Implements zmq::i_poll_events.
Reimplemented in zmq::session_t, and zmq::zmq_connecter_t.
Definition at line 104 of file io_object.cpp.
References zmq_assert.
void zmq::zmq_engine_t::unplug () [virtual]
Implements zmq::i_engine.
Definition at line 81 of file zmq_engine.cpp.
References zmq::io_object_t::unplug(), and zmq_assert.
Member Data Documentation
decoder_t zmq::zmq_engine_t::decoder [private]
Definition at line 66 of file zmq_engine.hpp.
encoder_t zmq::zmq_engine_t::encoder [private]
Definition at line 70 of file zmq_engine.hpp.
handle_t zmq::zmq_engine_t::handle [private]
Definition at line 62 of file zmq_engine.hpp.
unsigned char* zmq::zmq_engine_t::inpos [private]
Definition at line 64 of file zmq_engine.hpp.
size_t zmq::zmq_engine_t::insize [private]
Definition at line 65 of file zmq_engine.hpp.
class session_t* zmq::zmq_engine_t::leftover_session [private]
Definition at line 76 of file zmq_engine.hpp.
options_t zmq::zmq_engine_t::options [private]
Definition at line 78 of file zmq_engine.hpp.
Referenced by zmq_engine_t().
unsigned char* zmq::zmq_engine_t::outpos [private]
Definition at line 68 of file zmq_engine.hpp.
size_t zmq::zmq_engine_t::outsize [private]
Definition at line 69 of file zmq_engine.hpp.
bool zmq::zmq_engine_t::plugged [private]
Definition at line 80 of file zmq_engine.hpp.
class session_t* zmq::zmq_engine_t::session [private]
Definition at line 73 of file zmq_engine.hpp.
tcp_socket_t zmq::zmq_engine_t::tcp_socket [private]
Definition at line 61 of file zmq_engine.hpp.
Referenced by zmq_engine_t().
The documentation for this class was generated from the following files:
src/zmq_engine.hpp
src/zmq_engine.cpp