libzmq: zmq::transient_session_t Class Reference
zmq::transient_session_t Class Reference
#include <transient_session.hpp>
Public Member Functions
transient_session_t (class io_thread_t *io_thread_, class socket_base_t *socket_, const options_t &options_)
~transient_session_t ()
void attach_pipe (class pipe_t *pipe_)
void detach ()
void flush ()
ctx_t * get_ctx ()
uint32_t get_tid ()
void hiccuped (class pipe_t *pipe_)
void inc_seqnum ()
void plug (class io_thread_t *io_thread_)
void process_command (struct command_t &cmd_)
bool read (msg_t *msg_)
void read_activated (class pipe_t *pipe_)
void register_term_acks (int count_)
void terminated (class pipe_t *pipe_)
void unplug ()
void unregister_term_ack ()
bool write (msg_t *msg_)
void write_activated (class pipe_t *pipe_)
Protected Types
typedef poller_t::handle_t handle_t
Protected Member Functions
handle_t add_fd (fd_t fd_)
void add_timer (int timout_, int id_)
void cancel_timer (int id_)
class io_thread_t * choose_io_thread (uint64_t affinity_)
void destroy_socket (class socket_base_t *socket_)
struct endpoint_t find_endpoint (const char *addr_)
bool has_engine ()
void in_event ()
bool is_terminating ()
void launch_child (own_t *object_)
void launch_sibling (own_t *object_)
void log (const char *format_,...)
void out_event ()
virtual void process_activate_read ()
virtual void process_activate_write (uint64_t msgs_read_)
virtual void process_bind (class pipe_t *pipe_, const blob_t &peer_identity_)
virtual void process_destroy ()
virtual void process_hiccup (void *pipe_)
virtual void process_pipe_term ()
virtual void process_pipe_term_ack ()
virtual void process_reap (class socket_base_t *socket_)
virtual void process_reaped ()
virtual void process_stop ()
int register_endpoint (const char *addr_, struct endpoint_t &endpoint_)
bool register_session (const blob_t &name_, class session_t *session_)
void reset_pollin (handle_t handle_)
void reset_pollout (handle_t handle_)
void rm_fd (handle_t handle_)
void send_activate_read (class pipe_t *destination_)
void send_activate_write (class pipe_t *destination_, uint64_t msgs_read_)
void send_attach (class session_t *destination_, struct i_engine *engine_, const blob_t &peer_identity_, bool inc_seqnum_=true)
void send_bind (class own_t *destination_, class pipe_t *pipe_, const blob_t &peer_identity_, bool inc_seqnum_=true)
void send_done ()
void send_hiccup (class pipe_t *destination_, void *pipe_)
void send_own (class own_t *destination_, class own_t *object_)
void send_pipe_term (class pipe_t *destination_)
void send_pipe_term_ack (class pipe_t *destination_)
void send_plug (class own_t *destination_, bool inc_seqnum_=true)
void send_reap (class socket_base_t *socket_)
void send_reaped ()
void send_stop ()
void send_term (class own_t *destination_, int linger_)
void send_term_ack (class own_t *destination_)
void send_term_req (class own_t *destination_, class own_t *object_)
void set_pollin (handle_t handle_)
void set_pollout (handle_t handle_)
void terminate ()
void unregister_endpoints (class socket_base_t *socket_)
void unregister_session (const blob_t &name_)
Protected Attributes
options_t options
Private Member Functions
transient_session_t (const transient_session_t &)
const transient_session_t & operator= (const transient_session_t &)
bool xattached (const blob_t &peer_identity_)
bool xdetached ()
Detailed Description
Definition at line 32 of file transient_session.hpp.
Member Typedef Documentation
typedef poller_t::handle_t zmq::io_object_t::handle_t [protected, inherited]
Definition at line 51 of file io_object.hpp.
Constructor & Destructor Documentation
zmq::transient_session_t::transient_session_t (class io_thread_t * io_thread_, class socket_base_t * socket_, const options_t & options_)
Definition at line 23 of file transient_session.cpp.
zmq::transient_session_t::~transient_session_t ()
Definition at line 29 of file transient_session.cpp.
zmq::transient_session_t::transient_session_t (const transient_session_t &) [private]
Member Function Documentation
zmq::io_object_t::handle_t zmq::io_object_t::add_fd (fd_t fd_) [protected, inherited]
Definition at line 54 of file io_object.cpp.
void zmq::io_object_t::add_timer (int timout_, int id_) [protected, inherited]
Definition at line 84 of file io_object.cpp.
void zmq::session_t::attach_pipe (class pipe_t * pipe_) [inherited]
Definition at line 57 of file session.cpp.
References zmq::pipe_t::set_event_sink(), and zmq_assert.
Referenced by zmq::socket_base_t::connect().
void zmq::io_object_t::cancel_timer (int id_) [protected, inherited]
Definition at line 89 of file io_object.cpp.
zmq::io_thread_t * zmq::object_t::choose_io_thread (uint64_t affinity_) [protected, inherited]
Definition at line 168 of file object.cpp.
References zmq::object_t::choose_io_thread().
Referenced by zmq::object_t::choose_io_thread().
void zmq::object_t::destroy_socket (class socket_base_t * socket_) [protected, inherited]
Definition at line 155 of file object.cpp.
void zmq::session_t::detach () [virtual, inherited]
Implements zmq::i_inout.
Definition at line 203 of file session.cpp.
zmq::endpoint_t zmq::object_t::find_endpoint (const char * addr_) [read, protected, inherited]
Definition at line 150 of file object.cpp.
void zmq::session_t::flush () [virtual, inherited]
Implements zmq::i_inout.
Definition at line 88 of file session.cpp.
zmq::ctx_t * zmq::object_t::get_ctx () [inherited]
Definition at line 53 of file object.cpp.
uint32_t zmq::object_t::get_tid () [inherited]
Definition at line 48 of file object.cpp.
Referenced by zmq::ctx_t::destroy_socket(), and zmq::object_t::send_command().
bool zmq::session_t::has_engine () [protected, inherited]
Definition at line 273 of file session.cpp.
void zmq::session_t::hiccuped (class pipe_t * pipe_) [virtual, inherited]
Implements zmq::i_pipe_events.
Definition at line 149 of file session.cpp.
References zmq_assert.
void zmq::io_object_t::in_event () [protected, virtual, inherited]
Implements zmq::i_poll_events.
Reimplemented in zmq::zmq_connecter_t, zmq::zmq_engine_t, and zmq::zmq_listener_t.
Definition at line 94 of file io_object.cpp.
References zmq_assert.
void zmq::own_t::inc_seqnum () [inherited]
Definition at line 56 of file own.cpp.
Referenced by zmq::ctx_t::find_endpoint(), zmq::socket_base_t::find_session(), zmq::object_t::send_attach(), zmq::object_t::send_bind(), zmq::object_t::send_own(), and zmq::object_t::send_plug().
bool zmq::own_t::is_terminating () [protected, inherited]
Definition at line 156 of file own.cpp.
void zmq::own_t::launch_child (own_t * object_) [protected, inherited]
Definition at line 71 of file own.cpp.
References zmq::own_t::set_owner().
void zmq::own_t::launch_sibling (own_t * object_) [protected, inherited]
Definition at line 83 of file own.cpp.
References zmq::own_t::set_owner().
void zmq::object_t::log (const char * format_, ...) [protected, inherited]
Definition at line 160 of file object.cpp.
const transient_session_t& zmq::transient_session_t::operator= (const transient_session_t &) [private]
void zmq::io_object_t::out_event () [protected, virtual, inherited]
Implements zmq::i_poll_events.
Reimplemented in zmq::zmq_connecter_t, and zmq::zmq_engine_t.
Definition at line 99 of file io_object.cpp.
References zmq_assert.
void zmq::io_object_t::plug (class io_thread_t * io_thread_) [inherited]
Definition at line 36 of file io_object.cpp.
References zmq::io_thread_t::get_poller(), and zmq_assert.
Referenced by zmq::io_object_t::io_object_t(), and zmq::zmq_engine_t::plug().
void zmq::object_t::process_activate_read () [protected, virtual, inherited]
Reimplemented in zmq::pipe_t.
Definition at line 427 of file object.cpp.
References zmq_assert.
void zmq::object_t::process_activate_write (uint64_t msgs_read_) [protected, virtual, inherited]
Reimplemented in zmq::pipe_t.
Definition at line 432 of file object.cpp.
References zmq_assert.
void zmq::object_t::process_bind (class pipe_t * pipe_, const blob_t & peer_identity_) [protected, virtual, inherited]
Reimplemented in zmq::socket_base_t.
Definition at line 422 of file object.cpp.
References zmq_assert.
void zmq::object_t::process_command (struct command_t & cmd_) [inherited]
Definition at line 58 of file object.cpp.
References zmq::command_t::activate_read, zmq::command_t::activate_write, zmq::command_t::args, zmq::command_t::attach, zmq::command_t::bind, zmq::command_t::hiccup, zmq::command_t::own, zmq::command_t::pipe_term, zmq::command_t::pipe_term_ack, zmq::command_t::plug, zmq::command_t::reap, zmq::command_t::reaped, zmq::command_t::stop, zmq::command_t::term, zmq::command_t::term_ack, zmq::command_t::term_req, zmq::command_t::type, and zmq_assert.
Referenced by zmq::reaper_t::in_event(), zmq::io_thread_t::in_event(), and zmq::socket_base_t::process_commands().
void zmq::own_t::process_destroy () [protected, virtual, inherited]
Reimplemented in zmq::socket_base_t.
Definition at line 215 of file own.cpp.
Referenced by zmq::socket_base_t::check_destroy().
void zmq::object_t::process_hiccup (void * pipe_) [protected, virtual, inherited]
Reimplemented in zmq::pipe_t.
Definition at line 437 of file object.cpp.
References zmq_assert.
void zmq::object_t::process_pipe_term () [protected, virtual, inherited]
Reimplemented in zmq::pipe_t.
Definition at line 442 of file object.cpp.
References zmq_assert.
void zmq::object_t::process_pipe_term_ack () [protected, virtual, inherited]
Reimplemented in zmq::pipe_t.
Definition at line 447 of file object.cpp.
References zmq_assert.
void zmq::object_t::process_reap (class socket_base_t * socket_) [protected, virtual, inherited]
Reimplemented in zmq::reaper_t.
Definition at line 467 of file object.cpp.
References zmq_assert.
void zmq::object_t::process_reaped () [protected, virtual, inherited]
Reimplemented in zmq::reaper_t.
Definition at line 472 of file object.cpp.
References zmq_assert.
void zmq::object_t::process_stop () [protected, virtual, inherited]
Reimplemented in zmq::io_thread_t, zmq::reaper_t, and zmq::socket_base_t.
Definition at line 401 of file object.cpp.
References zmq_assert.
bool zmq::session_t::read (msg_t * msg_) [virtual, inherited]
Implements zmq::i_inout.
Definition at line 65 of file session.cpp.
References zmq::msg_t::flags, and zmq::msg_t::more.
void zmq::session_t::read_activated (class pipe_t * pipe_) [virtual, inherited]
Implements zmq::i_pipe_events.
Definition at line 131 of file session.cpp.
References likely, and zmq_assert.
int zmq::object_t::register_endpoint (const char * addr_, struct endpoint_t & endpoint_) [protected, inherited]
Definition at line 140 of file object.cpp.
bool zmq::session_t::register_session (const blob_t & name_, class session_t * session_) [protected, inherited]
Definition at line 278 of file session.cpp.
void zmq::own_t::register_term_acks (int count_) [inherited]
Definition at line 178 of file own.cpp.
void zmq::io_object_t::reset_pollin (handle_t handle_) [protected, inherited]
Definition at line 69 of file io_object.cpp.
void zmq::io_object_t::reset_pollout (handle_t handle_) [protected, inherited]
Definition at line 79 of file io_object.cpp.
void zmq::io_object_t::rm_fd (handle_t handle_) [protected, inherited]
Definition at line 59 of file io_object.cpp.
void zmq::object_t::send_activate_read (class pipe_t * destination_) [protected, inherited]
Definition at line 273 of file object.cpp.
References zmq::command_t::activate_read, zmq::command_t::destination, and zmq::command_t::type.
void zmq::object_t::send_activate_write (class pipe_t * destination_, uint64_t msgs_read_) [protected, inherited]
Definition at line 284 of file object.cpp.
References zmq::command_t::activate_write, zmq::command_t::args, zmq::command_t::destination, and zmq::command_t::type.
void zmq::object_t::send_attach (class session_t * destination_, struct i_engine * engine_, const blob_t & peer_identity_, bool inc_seqnum_ = true) [protected, inherited]
Definition at line 213 of file object.cpp.
References alloc_assert, zmq::command_t::args, zmq::command_t::attach, zmq::command_t::destination, zmq::own_t::inc_seqnum(), zmq::command_t::type, and zmq_assert.
void zmq::object_t::send_bind (class own_t * destination_, class pipe_t * pipe_, const blob_t & peer_identity_, bool inc_seqnum_ = true) [protected, inherited]
Definition at line 243 of file object.cpp.
References alloc_assert, zmq::command_t::args, zmq::command_t::bind, zmq::command_t::destination, zmq::own_t::inc_seqnum(), zmq::command_t::type, and zmq_assert.
void zmq::object_t::send_done () [protected, inherited]
Definition at line 390 of file object.cpp.
References zmq::command_t::destination, zmq::command_t::done, zmq::ctx_t::term_tid, and zmq::command_t::type.
void zmq::object_t::send_hiccup (class pipe_t * destination_, void * pipe_) [protected, inherited]
Definition at line 297 of file object.cpp.
References zmq::command_t::args, zmq::command_t::destination, zmq::command_t::hiccup, and zmq::command_t::type.
void zmq::object_t::send_own (class own_t * destination_, class own_t * object_) [protected, inherited]
Definition at line 200 of file object.cpp.
References zmq::command_t::args, zmq::command_t::destination, zmq::own_t::inc_seqnum(), zmq::command_t::own, and zmq::command_t::type.
void zmq::object_t::send_pipe_term (class pipe_t * destination_) [protected, inherited]
Definition at line 309 of file object.cpp.
References zmq::command_t::destination, zmq::command_t::pipe_term, and zmq::command_t::type.
void zmq::object_t::send_pipe_term_ack (class pipe_t * destination_) [protected, inherited]
Definition at line 320 of file object.cpp.
References zmq::command_t::destination, zmq::command_t::pipe_term_ack, and zmq::command_t::type.
void zmq::object_t::send_plug (class own_t * destination_, bool inc_seqnum_ = true) [protected, inherited]
Definition at line 186 of file object.cpp.
References zmq::command_t::destination, zmq::own_t::inc_seqnum(), zmq::command_t::plug, and zmq::command_t::type.
void zmq::object_t::send_reap (class socket_base_t * socket_) [protected, inherited]
Definition at line 367 of file object.cpp.
References zmq::command_t::args, zmq::command_t::destination, zmq::command_t::reap, and zmq::command_t::type.
void zmq::object_t::send_reaped () [protected, inherited]
Definition at line 379 of file object.cpp.
References zmq::command_t::destination, zmq::command_t::reaped, and zmq::command_t::type.
void zmq::object_t::send_stop () [protected, inherited]
Definition at line 173 of file object.cpp.
References zmq::command_t::destination, zmq::command_t::stop, and zmq::command_t::type.
void zmq::object_t::send_term (class own_t * destination_, int linger_) [protected, inherited]
Definition at line 344 of file object.cpp.
References zmq::command_t::args, zmq::command_t::destination, zmq::command_t::term, and zmq::command_t::type.
void zmq::object_t::send_term_ack (class own_t * destination_) [protected, inherited]
Definition at line 356 of file object.cpp.
References zmq::command_t::destination, zmq::command_t::term_ack, and zmq::command_t::type.
void zmq::object_t::send_term_req (class own_t * destination_, class own_t * object_) [protected, inherited]
Definition at line 331 of file object.cpp.
References zmq::command_t::args, zmq::command_t::destination, zmq::command_t::term_req, and zmq::command_t::type.
void zmq::io_object_t::set_pollin (handle_t handle_) [protected, inherited]
Definition at line 64 of file io_object.cpp.
void zmq::io_object_t::set_pollout (handle_t handle_) [protected, inherited]
Definition at line 74 of file io_object.cpp.
void zmq::own_t::terminate () [protected, inherited]
Definition at line 138 of file own.cpp.
void zmq::session_t::terminated (class pipe_t * pipe_) [virtual, inherited]
Implements zmq::i_pipe_events.
Definition at line 118 of file session.cpp.
References zmq_assert.
void zmq::io_object_t::unplug () [inherited]
Reimplemented in zmq::zmq_engine_t.
Definition at line 45 of file io_object.cpp.
References zmq_assert.
Referenced by zmq::zmq_engine_t::unplug().
void zmq::object_t::unregister_endpoints (class socket_base_t * socket_) [protected, inherited]
Definition at line 145 of file object.cpp.
void zmq::session_t::unregister_session (const blob_t & name_) [protected, inherited]
Definition at line 283 of file session.cpp.
void zmq::own_t::unregister_term_ack () [inherited]
Definition at line 183 of file own.cpp.
References zmq_assert.
bool zmq::session_t::write (msg_t * msg_) [virtual, inherited]
Implements zmq::i_inout.
Definition at line 77 of file session.cpp.
References errno_assert, and zmq::msg_t::init().
void zmq::session_t::write_activated (class pipe_t * pipe_) [virtual, inherited]
Implements zmq::i_pipe_events.
Definition at line 141 of file session.cpp.
References zmq_assert.
bool zmq::transient_session_t::xattached (const blob_t & peer_identity_) [private, virtual]
Implements zmq::session_t.
Definition at line 33 of file transient_session.cpp.
bool zmq::transient_session_t::xdetached () [private, virtual]
Implements zmq::session_t.
Definition at line 39 of file transient_session.cpp.
Member Data Documentation
options_t zmq::own_t::options [protected, inherited]
Definition at line 98 of file own.hpp.
Referenced by zmq::pair_t::pair_t(), zmq::pub_t::pub_t(), zmq::pull_t::pull_t(), zmq::push_t::push_t(), zmq::rep_t::rep_t(), zmq::req_t::req_t(), zmq::sub_t::sub_t(), zmq::xpub_t::xpub_t(), zmq::xrep_t::xrep_t(), zmq::xreq_t::xreq_t(), zmq::xsub_t::xsub_t(), and zmq::zmq_init_t::zmq_init_t().
The documentation for this class was generated from the following files:
src/transient_session.hpp
src/transient_session.cpp