libzmq: zmq::writer_t Class Reference
zmq::writer_t Class Reference
#include <pipe.hpp>
Public Member Functions
bool check_write (msg_t *msg_)
void flush ()
int get_array_index ()
ctx_t * get_ctx ()
uint32_t get_tid ()
void process_command (struct command_t &cmd_)
void rollback ()
void set_array_index (int index_)
void set_event_sink (i_writer_events *endpoint_)
void terminate ()
bool write (msg_t *msg_)
Protected Member Functions
class io_thread_t * choose_io_thread (uint64_t affinity_)
void destroy_socket (class socket_base_t *socket_)
struct endpoint_t find_endpoint (const char *addr_)
void log (const char *format_,...)
virtual void process_activate_reader ()
virtual void process_attach (struct i_engine *engine_, const blob_t &peer_identity_)
virtual void process_bind (class reader_t *in_pipe_, class writer_t *out_pipe_, const blob_t &peer_identity_)
virtual void process_own (class own_t *object_)
virtual void process_pipe_term_ack ()
virtual void process_plug ()
virtual void process_reap (class socket_base_t *socket_)
virtual void process_reaped ()
virtual void process_seqnum ()
virtual void process_stop ()
virtual void process_term (int linger_)
virtual void process_term_ack ()
virtual void process_term_req (class own_t *object_)
int register_endpoint (const char *addr_, struct endpoint_t &endpoint_)
void send_activate_reader (class reader_t *destination_)
void send_activate_writer (class writer_t *destination_, uint64_t msgs_read_)
void send_attach (class session_t *destination_, struct i_engine *engine_, const blob_t &peer_identity_, bool inc_seqnum_=true)
void send_bind (class own_t *destination_, class reader_t *in_pipe_, class writer_t *out_pipe_, const blob_t &peer_identity_, bool inc_seqnum_=true)
void send_done ()
void send_own (class own_t *destination_, class own_t *object_)
void send_pipe_term (class writer_t *destination_)
void send_pipe_term_ack (class reader_t *destination_)
void send_plug (class own_t *destination_, bool inc_seqnum_=true)
void send_reap (class socket_base_t *socket_)
void send_reaped ()
void send_stop ()
void send_term (class own_t *destination_, int linger_)
void send_term_ack (class own_t *destination_)
void send_term_req (class own_t *destination_, class own_t *object_)
void unregister_endpoints (class socket_base_t *socket_)
Private Member Functions
writer_t (class object_t *parent_, pipe_t *pipe_, reader_t *reader_, int hwm_)
writer_t (const writer_t &)
~writer_t ()
const writer_t & operator= (const writer_t &)
bool pipe_full ()
void process_activate_writer (uint64_t msgs_read_)
void process_pipe_term ()
Private Attributes
bool active
int hwm
uint64_t msgs_read
uint64_t msgs_written
pipe_t * pipe
reader_t * reader
i_writer_events * sink
bool terminating
Friends
void create_pipe (object_t *, object_t *, int, reader_t **, writer_t **)
Detailed Description
Definition at line 125 of file pipe.hpp.
Constructor & Destructor Documentation
zmq::writer_t::writer_t (class object_t * parent_, pipe_t * pipe_, reader_t * reader_, int hwm_) [private]
Definition at line 160 of file pipe.cpp.
References reader, and zmq::reader_t::set_writer().
                :
    object_t (parent_),
    active (true),
    pipe (pipe_),
    reader (reader_),
    hwm (hwm_),
    msgs_read (0),
    msgs_written (0),
    sink (NULL),
    terminating (false)
{
    //  Inform reader about the writer.
    reader->set_writer (this);
}
zmq::writer_t::~writer_t () [private]
Definition at line 176 of file pipe.cpp.
{
}
zmq::writer_t::writer_t (const writer_t &) [private]
Member Function Documentation
bool zmq::writer_t::check_write (msg_t * msg_)
Definition at line 186 of file pipe.cpp.
References unlikely.
{
    //  We've already checked and there's no space free for the new message.
    //  There's no point in checking once again.
    if (unlikely (!active))
        return false;
    if (unlikely (pipe_full ())) {
        active = false;
        return false;
    }
    return true;
}
zmq::io_thread_t * zmq::object_t::choose_io_thread (uint64_t affinity_) [protected, inherited]
Definition at line 164 of file object.cpp.
References zmq::object_t::choose_io_thread().
Referenced by zmq::object_t::choose_io_thread().
{
    return ctx->choose_io_thread (affinity_);
}
void zmq::object_t::destroy_socket (class socket_base_t * socket_) [protected, inherited]
Definition at line 151 of file object.cpp.
{
    ctx->destroy_socket (socket_);
}
zmq::endpoint_t zmq::object_t::find_endpoint (const char * addr_) [read, protected, inherited]
Definition at line 146 of file object.cpp.
{
    return ctx->find_endpoint (addr_);
}
void zmq::writer_t::flush ()
Definition at line 224 of file pipe.cpp.
Referenced by zmq::dist_t::write().
{
    if (!pipe->flush ())
        send_activate_reader (reader);
}
int zmq::array_item_t::get_array_index () [inline, inherited]
Definition at line 53 of file array.hpp.
References zmq::array_item_t::array_index.
        {
            return array_index;
        }
zmq::ctx_t * zmq::object_t::get_ctx () [inherited]
Definition at line 53 of file object.cpp.
{
    return ctx;
}
uint32_t zmq::object_t::get_tid () [inherited]
Definition at line 48 of file object.cpp.
Referenced by zmq::ctx_t::destroy_socket(), and zmq::object_t::send_command().
{
    return tid;
}
void zmq::object_t::log (const char * format_, ...) [protected, inherited]
Definition at line 156 of file object.cpp.
{
    va_list args;
    va_start (args, format_);
    ctx->log (format_, args);
    va_end (args);
}
const writer_t& zmq::writer_t::operator= (const writer_t &) [private]
bool zmq::writer_t::pipe_full () [private]
Definition at line 283 of file pipe.cpp.
{
    return hwm > 0 && msgs_written - msgs_read == uint64_t (hwm);
}
void zmq::object_t::process_activate_reader () [protected, virtual, inherited]
Reimplemented in zmq::reader_t.
Definition at line 413 of file object.cpp.
References zmq_assert.
{
    zmq_assert (false);
}
void zmq::writer_t::process_activate_writer (uint64_t msgs_read_) [private, virtual]
Reimplemented from zmq::object_t.
Definition at line 252 of file pipe.cpp.
References zmq_assert.
{
    //  Store the reader's message sequence number.
    msgs_read = msgs_read_;
    //  If the writer was non-active before, let's make it active
    //  (available for writing messages to).
    if (!active && !terminating) {
        active = true;
        zmq_assert (sink);
        sink->activated (this);
    }
}
void zmq::object_t::process_attach (struct i_engine * engine_, const blob_t & peer_identity_) [protected, virtual, inherited]
Reimplemented in zmq::session_t.
Definition at line 401 of file object.cpp.
References zmq_assert.
{
    zmq_assert (false);
}
void zmq::object_t::process_bind (class reader_t * in_pipe_, class writer_t * out_pipe_, const blob_t & peer_identity_) [protected, virtual, inherited]
Reimplemented in zmq::socket_base_t.
Definition at line 407 of file object.cpp.
References zmq_assert.
{
    zmq_assert (false);
}
void zmq::object_t::process_command (struct command_t & cmd_) [inherited]
Definition at line 58 of file object.cpp.
References zmq::command_t::activate_reader, zmq::command_t::activate_writer, zmq::command_t::args, zmq::command_t::attach, zmq::command_t::bind, zmq::deallocate_command(), zmq::command_t::own, zmq::command_t::pipe_term, zmq::command_t::pipe_term_ack, zmq::command_t::plug, zmq::command_t::reap, zmq::command_t::reaped, zmq::command_t::stop, zmq::command_t::term, zmq::command_t::term_ack, zmq::command_t::term_req, zmq::command_t::type, and zmq_assert.
Referenced by zmq::reaper_t::in_event(), zmq::io_thread_t::in_event(), and zmq::socket_base_t::process_commands().
{
    switch (cmd_.type) {
    case command_t::activate_reader:
        process_activate_reader ();
        break;
    case command_t::activate_writer:
        process_activate_writer (cmd_.args.activate_writer.msgs_read);
        break;
    case command_t::stop:
        process_stop ();
        break;
    case command_t::plug:
        process_plug ();
        process_seqnum ();
        return;
    case command_t::own:
        process_own (cmd_.args.own.object);
        process_seqnum ();
        break;
    case command_t::attach:
        process_attach (cmd_.args.attach.engine,
            cmd_.args.attach.peer_identity ?
            blob_t (cmd_.args.attach.peer_identity,
            cmd_.args.attach.peer_identity_size) : blob_t ());
        process_seqnum ();
        break;
    case command_t::bind:
        process_bind (cmd_.args.bind.in_pipe, cmd_.args.bind.out_pipe,
            cmd_.args.bind.peer_identity ? blob_t (cmd_.args.bind.peer_identity,
            cmd_.args.bind.peer_identity_size) : blob_t ());
        process_seqnum ();
        break;
    case command_t::pipe_term:
        process_pipe_term ();
        return;
    case command_t::pipe_term_ack:
        process_pipe_term_ack ();
        break;
    case command_t::term_req:
        process_term_req (cmd_.args.term_req.object);
        break;
    case command_t::term:
        process_term (cmd_.args.term.linger);
        break;
    case command_t::term_ack:
        process_term_ack ();
        break;
    case command_t::reap:
        process_reap (cmd_.args.reap.socket);
        break;
    case command_t::reaped:
        process_reaped ();
        break;
    default:
        zmq_assert (false);
    }
    //  The assumption here is that each command is processed once only,
    //  so deallocating it after processing is all right.
    deallocate_command (&cmd_);
}
void zmq::object_t::process_own (class own_t * object_) [protected, virtual, inherited]
Reimplemented in zmq::own_t.
Definition at line 396 of file object.cpp.
References zmq_assert.
{
    zmq_assert (false);
}
void zmq::writer_t::process_pipe_term () [private, virtual]
Reimplemented from zmq::object_t.
Definition at line 266 of file pipe.cpp.
References zmq_assert.
{
    send_pipe_term_ack (reader);
    //  The above command allows reader to deallocate itself and the pipe.
    //  For safety's sake we'll drop the pointers here.
    reader = NULL;
    pipe = NULL;
    //  Notify owner about the termination.
    zmq_assert (sink);
    sink->terminated (this);
    //  Deallocate the resources.
    delete this;
}
void zmq::object_t::process_pipe_term_ack () [protected, virtual, inherited]
Reimplemented in zmq::reader_t.
Definition at line 428 of file object.cpp.
References zmq_assert.
{
    zmq_assert (false);
}
void zmq::object_t::process_plug () [protected, virtual, inherited]
Reimplemented in zmq::connect_session_t, zmq::session_t, zmq::zmq_connecter_t, zmq::zmq_init_t, and zmq::zmq_listener_t.
Definition at line 391 of file object.cpp.
References zmq_assert.
{
    zmq_assert (false);
}
void zmq::object_t::process_reap (class socket_base_t * socket_) [protected, virtual, inherited]
Reimplemented in zmq::reaper_t.
Definition at line 448 of file object.cpp.
References zmq_assert.
{
    zmq_assert (false);
}
void zmq::object_t::process_reaped () [protected, virtual, inherited]
Reimplemented in zmq::reaper_t.
Definition at line 453 of file object.cpp.
References zmq_assert.
{
    zmq_assert (false);
}
void zmq::object_t::process_seqnum () [protected, virtual, inherited]
Reimplemented in zmq::own_t.
Definition at line 458 of file object.cpp.
References zmq_assert.
{
    zmq_assert (false);
}
void zmq::object_t::process_stop () [protected, virtual, inherited]
Reimplemented in zmq::io_thread_t, zmq::reaper_t, and zmq::socket_base_t.
Definition at line 386 of file object.cpp.
References zmq_assert.
{
    zmq_assert (false);
}
void zmq::object_t::process_term (int linger_) [protected, virtual, inherited]
Reimplemented in zmq::own_t, zmq::pair_t, zmq::pull_t, zmq::push_t, zmq::session_t, zmq::socket_base_t, zmq::xpub_t, zmq::xrep_t, zmq::xreq_t, zmq::xsub_t, and zmq::zmq_listener_t.
Definition at line 438 of file object.cpp.
References zmq_assert.
{
    zmq_assert (false);
}
void zmq::object_t::process_term_ack () [protected, virtual, inherited]
Reimplemented in zmq::own_t.
Definition at line 443 of file object.cpp.
References zmq_assert.
{
    zmq_assert (false);
}
void zmq::object_t::process_term_req (class own_t * object_) [protected, virtual, inherited]
Reimplemented in zmq::own_t.
Definition at line 433 of file object.cpp.
References zmq_assert.
{
    zmq_assert (false);
}
int zmq::object_t::register_endpoint (const char * addr_, struct endpoint_t & endpoint_) [protected, inherited]
Definition at line 136 of file object.cpp.
{
    return ctx->register_endpoint (addr_, endpoint_);
}
void zmq::writer_t::rollback ()
Definition at line 213 of file pipe.cpp.
References zmq::msg_t::close(), errno_assert, zmq::msg_t::flags, zmq::msg_t::more, and zmq_assert.
{
    //  Remove incomplete message from the pipe.
    msg_t msg;
    while (pipe->unwrite (&msg)) {
        zmq_assert (msg.flags () & msg_t::more);
        int rc = msg.close ();
        errno_assert (rc == 0);
    }
}
void zmq::object_t::send_activate_reader (class reader_t * destination_) [protected, inherited]
Definition at line 270 of file object.cpp.
References zmq::command_t::activate_reader, zmq::command_t::destination, and zmq::command_t::type.
{
    command_t cmd;
#if defined ZMQ_MAKE_VALGRIND_HAPPY
    memset (&cmd, 0, sizeof (cmd));
#endif
    cmd.destination = destination_;
    cmd.type = command_t::activate_reader;
    send_command (cmd);
}
void zmq::object_t::send_activate_writer (class writer_t * destination_, uint64_t msgs_read_) [protected, inherited]
Definition at line 281 of file object.cpp.
References zmq::command_t::activate_writer, zmq::command_t::args, zmq::command_t::destination, and zmq::command_t::type.
{
    command_t cmd;
#if defined ZMQ_MAKE_VALGRIND_HAPPY
    memset (&cmd, 0, sizeof (cmd));
#endif
    cmd.destination = destination_;
    cmd.type = command_t::activate_writer;
    cmd.args.activate_writer.msgs_read = msgs_read_;
    send_command (cmd);
}
void zmq::object_t::send_attach (class session_t * destination_, struct i_engine * engine_, const blob_t & peer_identity_, bool inc_seqnum_ = true) [protected, inherited]
Definition at line 209 of file object.cpp.
References alloc_assert, zmq::command_t::args, zmq::command_t::attach, zmq::command_t::destination, zmq::own_t::inc_seqnum(), zmq::command_t::type, and zmq_assert.
{
    if (inc_seqnum_)
        destination_->inc_seqnum ();
    command_t cmd;
#if defined ZMQ_MAKE_VALGRIND_HAPPY
    memset (&cmd, 0, sizeof (cmd));
#endif
    cmd.destination = destination_;
    cmd.type = command_t::attach;
    cmd.args.attach.engine = engine_;
    if (peer_identity_.empty ()) {
        cmd.args.attach.peer_identity_size = 0;
        cmd.args.attach.peer_identity = NULL;
    }
    else {
        zmq_assert (peer_identity_.size () <= 0xff);
        cmd.args.attach.peer_identity_size =
            (unsigned char) peer_identity_.size ();
        cmd.args.attach.peer_identity =
            (unsigned char*) malloc (peer_identity_.size ());
        alloc_assert (cmd.args.attach.peer_identity_size);
        memcpy (cmd.args.attach.peer_identity, peer_identity_.data (),
            peer_identity_.size ());
    }
    send_command (cmd);
}
void zmq::object_t::send_bind (class own_t * destination_, class reader_t * in_pipe_, class writer_t * out_pipe_, const blob_t & peer_identity_, bool inc_seqnum_ = true) [protected, inherited]
Definition at line 239 of file object.cpp.
References alloc_assert, zmq::command_t::args, zmq::command_t::bind, zmq::command_t::destination, zmq::own_t::inc_seqnum(), zmq::command_t::type, and zmq_assert.
{
    if (inc_seqnum_)
        destination_->inc_seqnum ();
    command_t cmd;
#if defined ZMQ_MAKE_VALGRIND_HAPPY
    memset (&cmd, 0, sizeof (cmd));
#endif
    cmd.destination = destination_;
    cmd.type = command_t::bind;
    cmd.args.bind.in_pipe = in_pipe_;
    cmd.args.bind.out_pipe = out_pipe_;
    if (peer_identity_.empty ()) {
        cmd.args.bind.peer_identity_size = 0;
        cmd.args.bind.peer_identity = NULL;
    }
    else {
        zmq_assert (peer_identity_.size () <= 0xff);
        cmd.args.bind.peer_identity_size =
            (unsigned char) peer_identity_.size ();
        cmd.args.bind.peer_identity =
            (unsigned char*) malloc (peer_identity_.size ());
        alloc_assert (cmd.args.bind.peer_identity_size);
        memcpy (cmd.args.bind.peer_identity, peer_identity_.data (),
            peer_identity_.size ());
    }
    send_command (cmd);
}
void zmq::object_t::send_done () [protected, inherited]
Definition at line 375 of file object.cpp.
References zmq::command_t::destination, zmq::command_t::done, zmq::ctx_t::term_tid, and zmq::command_t::type.
{
    command_t cmd;
#if defined ZMQ_MAKE_VALGRIND_HAPPY
    memset (&cmd, 0, sizeof (cmd));
#endif
    cmd.destination = NULL;
    cmd.type = command_t::done;
    ctx->send_command (ctx_t::term_tid, cmd);
}
void zmq::object_t::send_own (class own_t * destination_, class own_t * object_) [protected, inherited]
Definition at line 196 of file object.cpp.
References zmq::command_t::args, zmq::command_t::destination, zmq::own_t::inc_seqnum(), zmq::command_t::own, and zmq::command_t::type.
{
    destination_->inc_seqnum ();
    command_t cmd;
#if defined ZMQ_MAKE_VALGRIND_HAPPY
    memset (&cmd, 0, sizeof (cmd));
#endif
    cmd.destination = destination_;
    cmd.type = command_t::own;
    cmd.args.own.object = object_;
    send_command (cmd);
}
void zmq::object_t::send_pipe_term (class writer_t * destination_) [protected, inherited]
Definition at line 294 of file object.cpp.
References zmq::command_t::destination, zmq::command_t::pipe_term, and zmq::command_t::type.
{
    command_t cmd;
#if defined ZMQ_MAKE_VALGRIND_HAPPY
    memset (&cmd, 0, sizeof (cmd));
#endif
    cmd.destination = destination_;
    cmd.type = command_t::pipe_term;
    send_command (cmd);
}
void zmq::object_t::send_pipe_term_ack (class reader_t * destination_) [protected, inherited]
Definition at line 305 of file object.cpp.
References zmq::command_t::destination, zmq::command_t::pipe_term_ack, and zmq::command_t::type.
{
    command_t cmd;
#if defined ZMQ_MAKE_VALGRIND_HAPPY
    memset (&cmd, 0, sizeof (cmd));
#endif
    cmd.destination = destination_;
    cmd.type = command_t::pipe_term_ack;
    send_command (cmd);
}
void zmq::object_t::send_plug (class own_t * destination_, bool inc_seqnum_ = true) [protected, inherited]
Definition at line 182 of file object.cpp.
References zmq::command_t::destination, zmq::own_t::inc_seqnum(), zmq::command_t::plug, and zmq::command_t::type.
{
    if (inc_seqnum_)
        destination_->inc_seqnum ();
    command_t cmd;
#if defined ZMQ_MAKE_VALGRIND_HAPPY
    memset (&cmd, 0, sizeof (cmd));
#endif
    cmd.destination = destination_;
    cmd.type = command_t::plug;
    send_command (cmd);
}
void zmq::object_t::send_reap (class socket_base_t * socket_) [protected, inherited]
Definition at line 352 of file object.cpp.
References zmq::command_t::args, zmq::command_t::destination, zmq::command_t::reap, and zmq::command_t::type.
{
    command_t cmd;
#if defined ZMQ_MAKE_VALGRIND_HAPPY
    memset (&cmd, 0, sizeof (cmd));
#endif
    cmd.destination = ctx->get_reaper ();
    cmd.type = command_t::reap;
    cmd.args.reap.socket = socket_;
    send_command (cmd);
}
void zmq::object_t::send_reaped () [protected, inherited]
Definition at line 364 of file object.cpp.
References zmq::command_t::destination, zmq::command_t::reaped, and zmq::command_t::type.
{
    command_t cmd;
#if defined ZMQ_MAKE_VALGRIND_HAPPY
    memset (&cmd, 0, sizeof (cmd));
#endif
    cmd.destination = ctx->get_reaper ();
    cmd.type = command_t::reaped;
    send_command (cmd);
}
void zmq::object_t::send_stop () [protected, inherited]
Definition at line 169 of file object.cpp.
References zmq::command_t::destination, zmq::command_t::stop, and zmq::command_t::type.
{
    //  'stop' command goes always from administrative thread to
    //  the current object.
    command_t cmd;
#if defined ZMQ_MAKE_VALGRIND_HAPPY
    memset (&cmd, 0, sizeof (cmd));
#endif
    cmd.destination = this;
    cmd.type = command_t::stop;
    ctx->send_command (tid, cmd);
}
void zmq::object_t::send_term (class own_t * destination_, int linger_) [protected, inherited]
Definition at line 329 of file object.cpp.
References zmq::command_t::args, zmq::command_t::destination, zmq::command_t::term, and zmq::command_t::type.
{
    command_t cmd;
#if defined ZMQ_MAKE_VALGRIND_HAPPY
    memset (&cmd, 0, sizeof (cmd));
#endif
    cmd.destination = destination_;
    cmd.type = command_t::term;
    cmd.args.term.linger = linger_;
    send_command (cmd);
}
void zmq::object_t::send_term_ack (class own_t * destination_) [protected, inherited]
Definition at line 341 of file object.cpp.
References zmq::command_t::destination, zmq::command_t::term_ack, and zmq::command_t::type.
{
    command_t cmd;
#if defined ZMQ_MAKE_VALGRIND_HAPPY
    memset (&cmd, 0, sizeof (cmd));
#endif
    cmd.destination = destination_;
    cmd.type = command_t::term_ack;
    send_command (cmd);
}
void zmq::object_t::send_term_req (class own_t * destination_, class own_t * object_) [protected, inherited]
Definition at line 316 of file object.cpp.
References zmq::command_t::args, zmq::command_t::destination, zmq::command_t::term_req, and zmq::command_t::type.
{
    command_t cmd;
#if defined ZMQ_MAKE_VALGRIND_HAPPY
    memset (&cmd, 0, sizeof (cmd));
#endif
    cmd.destination = destination_;
    cmd.type = command_t::term_req;
    cmd.args.term_req.object = object_;
    send_command (cmd);
}
void zmq::array_item_t::set_array_index (int index_) [inline, inherited]
Definition at line 48 of file array.hpp.
References zmq::array_item_t::array_index.
        {
            array_index = index_;
        }
void zmq::writer_t::set_event_sink (i_writer_events * endpoint_)
Definition at line 180 of file pipe.cpp.
References zmq_assert.
Referenced by zmq::lb_t::attach(), zmq::dist_t::attach(), zmq::session_t::attach_pipes(), zmq::xrep_t::xattach_pipes(), and zmq::pair_t::xattach_pipes().
{
    zmq_assert (!sink);
    sink = sink_;
}
void zmq::writer_t::terminate ()
Definition at line 230 of file pipe.cpp.
References zmq::msg_t::init_delimiter().
Referenced by zmq::lb_t::attach(), zmq::dist_t::attach(), zmq::xrep_t::xattach_pipes(), and zmq::pair_t::xattach_pipes().
{
    //  Prevent double termination.
    if (terminating)
        return;
    terminating = true;
    //  Mark the pipe as not available for writing.
    active = false;
    //  Rollback any unfinished messages.
    rollback ();
    //  Push delimiter into the pipe. Trick the compiler to belive that
    //  the tag is a valid pointer. Note that watermarks are not checked
    //  thus the delimiter can be written even though the pipe is full.
    msg_t msg;
    msg.init_delimiter ();
    pipe->write (msg, false);
    flush ();
}
void zmq::object_t::unregister_endpoints (class socket_base_t * socket_) [protected, inherited]
Definition at line 141 of file object.cpp.
{
    return ctx->unregister_endpoints (socket_);
}
bool zmq::writer_t::write (msg_t * msg_)
Definition at line 201 of file pipe.cpp.
References zmq::msg_t::flags, zmq::msg_t::more, and unlikely.
Referenced by zmq::dist_t::write().
{
    if (unlikely (!check_write (msg_)))
        return false;
    pipe->write (*msg_, msg_->flags () & msg_t::more);
    if (!(msg_->flags () & msg_t::more))
        msgs_written++;
    return true;
}
Friends And Related Function Documentation
void create_pipe (object_t * , object_t * , int , reader_t ** , writer_t **) [friend]
Member Data Documentation
bool zmq::writer_t::active [private]
Definition at line 167 of file pipe.hpp.
int zmq::writer_t::hwm [private]
Definition at line 176 of file pipe.hpp.
uint64_t zmq::writer_t::msgs_read [private]
Definition at line 180 of file pipe.hpp.
uint64_t zmq::writer_t::msgs_written [private]
Definition at line 183 of file pipe.hpp.
pipe_t* zmq::writer_t::pipe [private]
Definition at line 170 of file pipe.hpp.
reader_t* zmq::writer_t::reader [private]
Definition at line 173 of file pipe.hpp.
Referenced by writer_t().
i_writer_events* zmq::writer_t::sink [private]
Definition at line 186 of file pipe.hpp.
bool zmq::writer_t::terminating [private]
Definition at line 190 of file pipe.hpp.
The documentation for this class was generated from the following files:
/home/travlr/src/libzmq/src/pipe.hpp
/home/travlr/src/libzmq/src/pipe.cpp