libzmq: zmq::push_t Class Reference
zmq::push_t Class Reference
#include <push.hpp>
Public Member Functions
push_t (class ctx_t *parent_, uint32_t tid_)
~push_t ()
void activated (class reader_t *pipe_)
void activated (class writer_t *pipe_)
int bind (const char *addr_)
void check_destroy ()
bool check_tag ()
int close ()
int connect (const char *addr_)
class session_t * find_session (const blob_t &name_)
int get_array_index ()
ctx_t * get_ctx ()
mailbox_t * get_mailbox ()
uint32_t get_tid ()
int getsockopt (int option_, void *optval_, size_t *optvallen_)
bool has_in ()
bool has_out ()
void in_event ()
void inc_seqnum ()
void out_event ()
void process_command (struct command_t &cmd_)
int recv (class msg_t *msg_, int flags_)
bool register_session (const blob_t &name_, class session_t *session_)
void register_term_acks (int count_)
int send (class msg_t *msg_, int flags_)
void set_array_index (int index_)
int setsockopt (int option_, const void *optval_, size_t optvallen_)
void start_reaping (poller_t *poller_)
void stop ()
void terminated (class writer_t *pipe_)
void terminated (class reader_t *pipe_)
void timer_event (int id_)
void unregister_session (const blob_t &name_)
void unregister_term_ack ()
Static Public Member Functions
static socket_base_t * create (int type_, class ctx_t *parent_, uint32_t tid_)
Protected Member Functions
class io_thread_t * choose_io_thread (uint64_t affinity_)
void destroy_socket (class socket_base_t *socket_)
struct endpoint_t find_endpoint (const char *addr_)
void launch_child (own_t *object_)
void launch_sibling (own_t *object_)
void log (const char *format_,...)
virtual void process_activate_reader ()
virtual void process_activate_writer (uint64_t msgs_read_)
virtual void process_attach (struct i_engine *engine_, const blob_t &peer_identity_)
void process_destroy ()
virtual void process_pipe_term ()
virtual void process_pipe_term_ack ()
virtual void process_plug ()
virtual void process_reap (class socket_base_t *socket_)
virtual void process_reaped ()
int register_endpoint (const char *addr_, struct endpoint_t &endpoint_)
void send_activate_reader (class reader_t *destination_)
void send_activate_writer (class writer_t *destination_, uint64_t msgs_read_)
void send_attach (class session_t *destination_, struct i_engine *engine_, const blob_t &peer_identity_, bool inc_seqnum_=true)
void send_bind (class own_t *destination_, class reader_t *in_pipe_, class writer_t *out_pipe_, const blob_t &peer_identity_, bool inc_seqnum_=true)
void send_done ()
void send_own (class own_t *destination_, class own_t *object_)
void send_pipe_term (class writer_t *destination_)
void send_pipe_term_ack (class reader_t *destination_)
void send_plug (class own_t *destination_, bool inc_seqnum_=true)
void send_reap (class socket_base_t *socket_)
void send_reaped ()
void send_stop ()
void send_term (class own_t *destination_, int linger_)
void send_term_ack (class own_t *destination_)
void send_term_req (class own_t *destination_, class own_t *object_)
void terminate ()
void unregister_endpoints (class socket_base_t *socket_)
void xattach_pipes (class reader_t *inpipe_, class writer_t *outpipe_, const blob_t &peer_identity_)
virtual bool xhas_in ()
bool xhas_out ()
virtual int xrecv (class msg_t *msg_, int options_)
int xsend (class msg_t *msg_, int flags_)
virtual int xsetsockopt (int option_, const void *optval_, size_t optvallen_)
Protected Attributes
options_t options
Private Member Functions
push_t (const push_t &)
const push_t & operator= (const push_t &)
void process_term (int linger_)
Private Attributes
lb_t lb
Detailed Description
Definition at line 30 of file push.hpp.
Constructor & Destructor Documentation
zmq::push_t::push_t (class ctx_t * parent_, uint32_t tid_)
Definition at line 26 of file push.cpp.
References zmq::own_t::options, zmq::options_t::requires_in, zmq::options_t::requires_out, zmq::options_t::type, and ZMQ_PUSH.
                                                      :
    socket_base_t (parent_, tid_),
    lb (this)
{
    options.type = ZMQ_PUSH;
    options.requires_in = false;
    options.requires_out = true;
}
zmq::push_t::~push_t ()
Definition at line 35 of file push.cpp.
{
}
zmq::push_t::push_t (const push_t &) [private]
Member Function Documentation
void zmq::socket_base_t::activated (class reader_t * pipe_) [inherited]
Reimplemented in zmq::pair_t, and zmq::xrep_t.
void zmq::socket_base_t::activated (class writer_t * pipe_) [inherited]
Reimplemented in zmq::pair_t, and zmq::xrep_t.
int zmq::socket_base_t::bind (const char * addr_) [inherited]
Definition at line 295 of file socket_base.cpp.
References alloc_assert, EMTHREAD, ETERM, zmq::zmq_listener_t::set_address(), unlikely, and zmq_assert.
Referenced by zmq::ctx_t::ctx_t().
{
    if (unlikely (ctx_terminated)) {
        errno = ETERM;
        return -1;
    }
    //  Parse addr_ string.
    std::string protocol;
    std::string address;
    int rc = parse_uri (addr_, protocol, address);
    if (rc != 0)
        return -1;
    rc = check_protocol (protocol);
    if (rc != 0)
        return -1;
    if (protocol == "inproc" || protocol == "sys") {
        endpoint_t endpoint = {this, options};
        return register_endpoint (addr_, endpoint);
    }
    if (protocol == "tcp" || protocol == "ipc") {
        //  Choose I/O thread to run the listerner in.
        io_thread_t *io_thread = choose_io_thread (options.affinity);
        if (!io_thread) {
            errno = EMTHREAD;
            return -1;
        }
        //  Create and run the listener.
        zmq_listener_t *listener = new (std::nothrow) zmq_listener_t (
            io_thread, this, options);
        alloc_assert (listener);
        int rc = listener->set_address (protocol.c_str(), address.c_str ());
        if (rc != 0) {
            delete listener;
            return -1;
        }
        launch_child (listener);
        return 0;
    }
    if (protocol == "pgm" || protocol == "epgm") {
        //  For convenience's sake, bind can be used interchageable with
        //  connect for PGM and EPGM transports.
        return connect (addr_);
    }
    zmq_assert (false);
    return -1;
}
void zmq::socket_base_t::check_destroy () [inherited]
Definition at line 794 of file socket_base.cpp.
References zmq::own_t::process_destroy().
Referenced by zmq::reaper_t::process_reap().
{
    //  If the object was already marked as destroyed, finish the deallocation.
    if (destroyed) {
        //  Remove the socket from the reaper's poller.
        poller->rm_fd (handle);
        //  Remove the socket from the context.
        destroy_socket (this);
        //  Notify the reaper about the fact.
        send_reaped ();
        //  Deallocate.
        own_t::process_destroy ();
    }
}
bool zmq::socket_base_t::check_tag () [inherited]
Definition at line 63 of file socket_base.cpp.
References zmq::socket_base_t::tag.
{
    return tag == 0xbaddecaf;
}
zmq::io_thread_t * zmq::object_t::choose_io_thread (uint64_t affinity_) [protected, inherited]
Definition at line 164 of file object.cpp.
References zmq::object_t::choose_io_thread().
Referenced by zmq::object_t::choose_io_thread().
{
    return ctx->choose_io_thread (affinity_);
}
int zmq::socket_base_t::close () [inherited]
Definition at line 593 of file socket_base.cpp.
{
    //  Transfer the ownership of the socket from this application thread
    //  to the reaper thread which will take care of the rest of shutdown
    //  process.
    send_reap (this);
    return 0;
}
int zmq::socket_base_t::connect (const char * addr_) [inherited]
Definition at line 352 of file socket_base.cpp.
References alloc_assert, zmq::session_t::attach_pipes(), zmq::create_pipe(), EMTHREAD, ETERM, zmq::options_t::identity, zmq::endpoint_t::options, zmq::options_t::rcvhwm, zmq::options_t::sndhwm, zmq::endpoint_t::socket, and unlikely.
{
    if (unlikely (ctx_terminated)) {
        errno = ETERM;
        return -1;
    }
    //  Parse addr_ string.
    std::string protocol;
    std::string address;
    int rc = parse_uri (addr_, protocol, address);
    if (rc != 0)
        return -1;
    rc = check_protocol (protocol);
    if (rc != 0)
        return -1;
    if (protocol == "inproc" || protocol == "sys") {
        //  TODO: inproc connect is specific with respect to creating pipes
        //  as there's no 'reconnect' functionality implemented. Once that
        //  is in place we should follow generic pipe creation algorithm.
        //  Find the peer endpoint.
        endpoint_t peer = find_endpoint (addr_);
        if (!peer.socket)
            return -1;
        reader_t *inpipe_reader = NULL;
        writer_t *inpipe_writer = NULL;
        reader_t *outpipe_reader = NULL;
        writer_t *outpipe_writer = NULL;
        // The total HWM for an inproc connection should be the sum of
        // the binder's HWM and the connector's HWM.
        int  sndhwm;
        int  rcvhwm;
        if (options.sndhwm == 0 || peer.options.rcvhwm == 0)
            sndhwm = 0;
        else
            sndhwm = options.sndhwm + peer.options.rcvhwm;
        if (options.rcvhwm == 0 || peer.options.sndhwm == 0)
            rcvhwm = 0;
        else
            rcvhwm = options.rcvhwm + peer.options.sndhwm;
        //  Create inbound pipe, if required.
        if (options.requires_in)
            create_pipe (this, peer.socket, rcvhwm, &inpipe_reader,
                &inpipe_writer);
        //  Create outbound pipe, if required.
        if (options.requires_out)
            create_pipe (peer.socket, this, sndhwm, &outpipe_reader,
                &outpipe_writer);
        //  Attach the pipes to this socket object.
        attach_pipes (inpipe_reader, outpipe_writer, peer.options.identity);
        //  Attach the pipes to the peer socket. Note that peer's seqnum
        //  was incremented in find_endpoint function. We don't need it
        //  increased here.
        send_bind (peer.socket, outpipe_reader, inpipe_writer,
            options.identity, false);
        return 0;
    }
    //  Choose the I/O thread to run the session in.
    io_thread_t *io_thread = choose_io_thread (options.affinity);
    if (!io_thread) {
        errno = EMTHREAD;
        return -1;
    }
    //  Create session.
    connect_session_t *session = new (std::nothrow) connect_session_t (
        io_thread, this, options, protocol.c_str (), address.c_str ());
    alloc_assert (session);
    //  If 'immediate connect' feature is required, we'll create the pipes
    //  to the session straight away. Otherwise, they'll be created by the
    //  session once the connection is established.
    if (options.immediate_connect) {
        reader_t *inpipe_reader = NULL;
        writer_t *inpipe_writer = NULL;
        reader_t *outpipe_reader = NULL;
        writer_t *outpipe_writer = NULL;
        //  Create inbound pipe, if required.
        if (options.requires_in)
            create_pipe (this, session, options.rcvhwm,
                &inpipe_reader, &inpipe_writer);
        //  Create outbound pipe, if required.
        if (options.requires_out)
            create_pipe (session, this, options.sndhwm,
                &outpipe_reader, &outpipe_writer);
        //  Attach the pipes to the socket object.
        attach_pipes (inpipe_reader, outpipe_writer, blob_t ());
        //  Attach the pipes to the session object.
        session->attach_pipes (outpipe_reader, inpipe_writer, blob_t ());
    }
    //  Activate the session. Make it a child of this socket.
    launch_child (session);
    return 0;
}
zmq::socket_base_t * zmq::socket_base_t::create (int type_, class ctx_t * parent_, uint32_t tid_) [static, inherited]
Definition at line 68 of file socket_base.cpp.
References alloc_assert, ZMQ_PAIR, ZMQ_PUB, ZMQ_PULL, ZMQ_PUSH, ZMQ_REP, ZMQ_REQ, ZMQ_SUB, ZMQ_XPUB, ZMQ_XREP, ZMQ_XREQ, and ZMQ_XSUB.
Referenced by zmq::ctx_t::create_socket().
{
    socket_base_t *s = NULL;
    switch (type_) {
    case ZMQ_PAIR:
        s = new (std::nothrow) pair_t (parent_, tid_);
        break;
    case ZMQ_PUB:
        s = new (std::nothrow) pub_t (parent_, tid_);
        break;
    case ZMQ_SUB:
        s = new (std::nothrow) sub_t (parent_, tid_);
        break;
    case ZMQ_REQ:
        s = new (std::nothrow) req_t (parent_, tid_);
        break;
    case ZMQ_REP:
        s = new (std::nothrow) rep_t (parent_, tid_);
        break;
    case ZMQ_XREQ:
        s = new (std::nothrow) xreq_t (parent_, tid_);
        break;
    case ZMQ_XREP:
        s = new (std::nothrow) xrep_t (parent_, tid_);
        break;
    case ZMQ_PULL:
        s = new (std::nothrow) pull_t (parent_, tid_);
        break;
    case ZMQ_PUSH:
        s = new (std::nothrow) push_t (parent_, tid_);
        break;
    case ZMQ_XPUB:
        s = new (std::nothrow) xpub_t (parent_, tid_);
        break;
    case ZMQ_XSUB:
        s = new (std::nothrow) xsub_t (parent_, tid_);
        break;
    default:
        errno = EINVAL;
        return NULL;
    }
    alloc_assert (s);
    return s;
}
void zmq::object_t::destroy_socket (class socket_base_t * socket_) [protected, inherited]
Definition at line 151 of file object.cpp.
{
    ctx->destroy_socket (socket_);
}
zmq::endpoint_t zmq::object_t::find_endpoint (const char * addr_) [read, protected, inherited]
Definition at line 146 of file object.cpp.
{
    return ctx->find_endpoint (addr_);
}
zmq::session_t * zmq::socket_base_t::find_session (const blob_t & name_) [inherited]
Definition at line 632 of file socket_base.cpp.
References zmq::own_t::inc_seqnum().
{
    sessions_sync.lock ();
    sessions_t::iterator it = sessions.find (name_);
    if (it == sessions.end ()) {
        sessions_sync.unlock ();
        return NULL;
    }
    session_t *session = it->second;
    //  Prepare the session for subsequent attach command.
    //  Note the connect sessions have NULL pointers registered here.
    if (session)
        session->inc_seqnum ();
    sessions_sync.unlock ();
    return session;
}
int zmq::array_item_t::get_array_index () [inline, inherited]
Definition at line 53 of file array.hpp.
References zmq::array_item_t::array_index.
        {
            return array_index;
        }
zmq::ctx_t * zmq::object_t::get_ctx () [inherited]
Definition at line 53 of file object.cpp.
{
    return ctx;
}
zmq::mailbox_t * zmq::socket_base_t::get_mailbox () [inherited]
Definition at line 139 of file socket_base.cpp.
Referenced by zmq::ctx_t::create_socket().
{
    return &mailbox;
}
uint32_t zmq::object_t::get_tid () [inherited]
Definition at line 48 of file object.cpp.
Referenced by zmq::ctx_t::destroy_socket(), and zmq::object_t::send_command().
{
    return tid;
}
int zmq::socket_base_t::getsockopt (int option_, void * optval_, size_t * optvallen_) [inherited]
Definition at line 246 of file socket_base.cpp.
References errno_assert, ETERM, unlikely, ZMQ_EVENTS, ZMQ_FD, ZMQ_POLLIN, ZMQ_POLLOUT, and ZMQ_RCVMORE.
{
    if (unlikely (ctx_terminated)) {
        errno = ETERM;
        return -1;
    }
    if (option_ == ZMQ_RCVMORE) {
        if (*optvallen_ < sizeof (int)) {
            errno = EINVAL;
            return -1;
        }
        *((int*) optval_) = rcvmore ? 1 : 0;
        *optvallen_ = sizeof (int);
        return 0;
    }
    if (option_ == ZMQ_FD) {
        if (*optvallen_ < sizeof (fd_t)) {
            errno = EINVAL;
            return -1;
        }
        *((fd_t*) optval_) = mailbox.get_fd ();
        *optvallen_ = sizeof (fd_t);
        return 0;
    }
    if (option_ == ZMQ_EVENTS) {
        if (*optvallen_ < sizeof (int)) {
            errno = EINVAL;
            return -1;
        }
        int rc = process_commands (false, false);
        if (rc != 0 && (errno == EINTR || errno == ETERM))
            return -1;
        errno_assert (rc == 0);
        *((int*) optval_) = 0;
        if (has_out ())
            *((int*) optval_) |= ZMQ_POLLOUT;
        if (has_in ())
            *((int*) optval_) |= ZMQ_POLLIN;
        *optvallen_ = sizeof (int);
        return 0;
    }
    return options.getsockopt (option_, optval_, optvallen_);
}
bool zmq::socket_base_t::has_in () [inherited]
Definition at line 603 of file socket_base.cpp.
{
    return xhas_in ();
}
bool zmq::socket_base_t::has_out () [inherited]
Definition at line 608 of file socket_base.cpp.
{
    return xhas_out ();
}
void zmq::socket_base_t::in_event () [virtual, inherited]
Implements zmq::i_poll_events.
Definition at line 776 of file socket_base.cpp.
{
    //  Process any commands from other threads/sockets that may be available
    //  at the moment. Ultimately, socket will be destroyed.
    process_commands (false, false);
    check_destroy ();
}
void zmq::own_t::inc_seqnum () [inherited]
Definition at line 56 of file own.cpp.
Referenced by zmq::ctx_t::find_endpoint(), zmq::socket_base_t::find_session(), zmq::object_t::send_attach(), zmq::object_t::send_bind(), zmq::object_t::send_own(), and zmq::object_t::send_plug().
{
    //  This function may be called from a different thread!
    sent_seqnum.add (1);
}
void zmq::own_t::launch_child (own_t * object_) [protected, inherited]
Definition at line 71 of file own.cpp.
References zmq::own_t::set_owner().
{
    //  Specify the owner of the object.
    object_->set_owner (this);
    //  Plug the object into the I/O thread.
    send_plug (object_);
    //  Take ownership of the object.
    send_own (this, object_);
}
void zmq::own_t::launch_sibling (own_t * object_) [protected, inherited]
Definition at line 83 of file own.cpp.
References zmq::own_t::set_owner().
{
    //  At this point it is important that object is plugged in before its
    //  owner has a chance to terminate it. Thus, 'plug' command is sent before
    //  the 'own' command. Given that the mailbox preserves ordering of
    //  commands, 'term' command from the owner cannot make it to the object
    //  before the already written 'plug' command.
    //  Specify the owner of the object.
    object_->set_owner (owner);
    //  Plug the object into its I/O thread.
    send_plug (object_);
    //  Make parent own the object.
    send_own (owner, object_);
}
void zmq::object_t::log (const char * format_, ...) [protected, inherited]
Definition at line 156 of file object.cpp.
{
    va_list args;
    va_start (args, format_);
    ctx->log (format_, args);
    va_end (args);
}
const push_t& zmq::push_t::operator= (const push_t &) [private]
void zmq::socket_base_t::out_event () [virtual, inherited]
Implements zmq::i_poll_events.
Definition at line 784 of file socket_base.cpp.
References zmq_assert.
{
    zmq_assert (false);
}
void zmq::object_t::process_activate_reader () [protected, virtual, inherited]
Reimplemented in zmq::reader_t.
Definition at line 413 of file object.cpp.
References zmq_assert.
{
    zmq_assert (false);
}
void zmq::object_t::process_activate_writer (uint64_t msgs_read_) [protected, virtual, inherited]
Reimplemented in zmq::writer_t.
Definition at line 418 of file object.cpp.
References zmq_assert.
{
    zmq_assert (false);
}
void zmq::object_t::process_attach (struct i_engine * engine_, const blob_t & peer_identity_) [protected, virtual, inherited]
Reimplemented in zmq::session_t.
Definition at line 401 of file object.cpp.
References zmq_assert.
{
    zmq_assert (false);
}
void zmq::object_t::process_command (struct command_t & cmd_) [inherited]
Definition at line 58 of file object.cpp.
References zmq::command_t::activate_reader, zmq::command_t::activate_writer, zmq::command_t::args, zmq::command_t::attach, zmq::command_t::bind, zmq::deallocate_command(), zmq::command_t::own, zmq::command_t::pipe_term, zmq::command_t::pipe_term_ack, zmq::command_t::plug, zmq::command_t::reap, zmq::command_t::reaped, zmq::command_t::stop, zmq::command_t::term, zmq::command_t::term_ack, zmq::command_t::term_req, zmq::command_t::type, and zmq_assert.
Referenced by zmq::reaper_t::in_event(), zmq::io_thread_t::in_event(), and zmq::socket_base_t::process_commands().
{
    switch (cmd_.type) {
    case command_t::activate_reader:
        process_activate_reader ();
        break;
    case command_t::activate_writer:
        process_activate_writer (cmd_.args.activate_writer.msgs_read);
        break;
    case command_t::stop:
        process_stop ();
        break;
    case command_t::plug:
        process_plug ();
        process_seqnum ();
        return;
    case command_t::own:
        process_own (cmd_.args.own.object);
        process_seqnum ();
        break;
    case command_t::attach:
        process_attach (cmd_.args.attach.engine,
            cmd_.args.attach.peer_identity ?
            blob_t (cmd_.args.attach.peer_identity,
            cmd_.args.attach.peer_identity_size) : blob_t ());
        process_seqnum ();
        break;
    case command_t::bind:
        process_bind (cmd_.args.bind.in_pipe, cmd_.args.bind.out_pipe,
            cmd_.args.bind.peer_identity ? blob_t (cmd_.args.bind.peer_identity,
            cmd_.args.bind.peer_identity_size) : blob_t ());
        process_seqnum ();
        break;
    case command_t::pipe_term:
        process_pipe_term ();
        return;
    case command_t::pipe_term_ack:
        process_pipe_term_ack ();
        break;
    case command_t::term_req:
        process_term_req (cmd_.args.term_req.object);
        break;
    case command_t::term:
        process_term (cmd_.args.term.linger);
        break;
    case command_t::term_ack:
        process_term_ack ();
        break;
    case command_t::reap:
        process_reap (cmd_.args.reap.socket);
        break;
    case command_t::reaped:
        process_reaped ();
        break;
    default:
        zmq_assert (false);
    }
    //  The assumption here is that each command is processed once only,
    //  so deallocating it after processing is all right.
    deallocate_command (&cmd_);
}
void zmq::socket_base_t::process_destroy () [protected, virtual, inherited]
Reimplemented from zmq::own_t.
Definition at line 742 of file socket_base.cpp.
{
    destroyed = true;
}
void zmq::object_t::process_pipe_term () [protected, virtual, inherited]
Reimplemented in zmq::writer_t.
Definition at line 423 of file object.cpp.
References zmq_assert.
{
    zmq_assert (false);
}
void zmq::object_t::process_pipe_term_ack () [protected, virtual, inherited]
Reimplemented in zmq::reader_t.
Definition at line 428 of file object.cpp.
References zmq_assert.
{
    zmq_assert (false);
}
void zmq::object_t::process_plug () [protected, virtual, inherited]
Reimplemented in zmq::connect_session_t, zmq::session_t, zmq::zmq_connecter_t, zmq::zmq_init_t, and zmq::zmq_listener_t.
Definition at line 391 of file object.cpp.
References zmq_assert.
{
    zmq_assert (false);
}
void zmq::object_t::process_reap (class socket_base_t * socket_) [protected, virtual, inherited]
Reimplemented in zmq::reaper_t.
Definition at line 448 of file object.cpp.
References zmq_assert.
{
    zmq_assert (false);
}
void zmq::object_t::process_reaped () [protected, virtual, inherited]
Reimplemented in zmq::reaper_t.
Definition at line 453 of file object.cpp.
References zmq_assert.
{
    zmq_assert (false);
}
void zmq::push_t::process_term (int linger_) [private, virtual]
Reimplemented from zmq::socket_base_t.
Definition at line 46 of file push.cpp.
References zmq::socket_base_t::process_term().
{
    lb.terminate ();
    socket_base_t::process_term (linger_);
}
int zmq::socket_base_t::recv (class msg_t * msg_, int flags_) [inherited]
Definition at line 511 of file socket_base.cpp.
References zmq::msg_t::check(), ETERM, zmq::msg_t::flags, zmq::inbound_poll_rate, zmq::msg_t::more, zmq::msg_t::reset_flags(), unlikely, and ZMQ_DONTWAIT.
{
    //  Check whether the library haven't been shut down yet.
    if (unlikely (ctx_terminated)) {
        errno = ETERM;
        return -1;
    }
    //  Check whether message passed to the function is valid.
    if (unlikely (!msg_->check ())) {
        errno = EFAULT;
        return -1;
    }
    //  Get the message.
    int rc = xrecv (msg_, flags_);
    int err = errno;
    //  Once every inbound_poll_rate messages check for signals and process
    //  incoming commands. This happens only if we are not polling altogether
    //  because there are messages available all the time. If poll occurs,
    //  ticks is set to zero and thus we avoid this code.
    //
    //  Note that 'recv' uses different command throttling algorithm (the one
    //  described above) from the one used by 'send'. This is because counting
    //  ticks is more efficient than doing RDTSC all the time.
    if (++ticks == inbound_poll_rate) {
        if (unlikely (process_commands (false, false) != 0))
            return -1;
        ticks = 0;
    }
    //  If we have the message, return immediately.
    if (rc == 0) {
        rcvmore = msg_->flags () & msg_t::more;
        if (rcvmore)
            msg_->reset_flags (msg_t::more);
        return 0;
    }
    //  If we don't have the message, restore the original cause of the problem.
    errno = err;
    //  If the message cannot be fetched immediately, there are two scenarios.
    //  For non-blocking recv, commands are processed in case there's an
    //  activate_reader command already waiting int a command pipe.
    //  If it's not, return EAGAIN.
    if (flags_ & ZMQ_DONTWAIT) {
        if (errno != EAGAIN)
            return -1;
        if (unlikely (process_commands (false, false) != 0))
            return -1;
        ticks = 0;
        rc = xrecv (msg_, flags_);
        if (rc == 0) {
            rcvmore = msg_->flags () & msg_t::more;
            if (rcvmore)
                msg_->reset_flags (msg_t::more);
        }
        return rc;
    }
    //  In blocking scenario, commands are processed over and over again until
    //  we are able to fetch a message.
    bool block = (ticks != 0);
    while (rc != 0) {
        if (errno != EAGAIN)
            return -1;
        if (unlikely (process_commands (block, false) != 0))
            return -1;
        rc = xrecv (msg_, flags_);
        ticks = 0;
        block = true;
    }
    rcvmore = msg_->flags () & msg_t::more;
    if (rcvmore)
        msg_->reset_flags (msg_t::more);
    return 0;
}
int zmq::object_t::register_endpoint (const char * addr_, struct endpoint_t & endpoint_) [protected, inherited]
Definition at line 136 of file object.cpp.
{
    return ctx->register_endpoint (addr_, endpoint_);
}
bool zmq::socket_base_t::register_session (const blob_t & name_, class session_t * session_) [inherited]
Definition at line 613 of file socket_base.cpp.
Referenced by zmq::named_session_t::named_session_t().
{
    sessions_sync.lock ();
    bool registered = sessions.insert (
        sessions_t::value_type (name_, session_)).second;
    sessions_sync.unlock ();
    return registered;
}
void zmq::own_t::register_term_acks (int count_) [inherited]
Definition at line 173 of file own.cpp.
{
    term_acks += count_;
}
int zmq::socket_base_t::send (class msg_t * msg_, int flags_) [inherited]
Definition at line 466 of file socket_base.cpp.
References zmq::msg_t::check(), ETERM, zmq::msg_t::more, zmq::msg_t::set_flags(), unlikely, ZMQ_DONTWAIT, and ZMQ_SNDMORE.
{
    //  Check whether the library haven't been shut down yet.
    if (unlikely (ctx_terminated)) {
        errno = ETERM;
        return -1;
    }
    //  Check whether message passed to the function is valid.
    if (unlikely (!msg_->check ())) {
        errno = EFAULT;
        return -1;
    }
    //  Process pending commands, if any.
    int rc = process_commands (false, true);
    if (unlikely (rc != 0))
        return -1;
    //  At this point we impose the MORE flag on the message.
    if (flags_ & ZMQ_SNDMORE)
        msg_->set_flags (msg_t::more);
    //  Try to send the message.
    rc = xsend (msg_, flags_);
    if (rc == 0)
        return 0;
    //  In case of non-blocking send we'll simply propagate
    //  the error - including EAGAIN - upwards.
    if (flags_ & ZMQ_DONTWAIT)
        return -1;
    //  Oops, we couldn't send the message. Wait for the next
    //  command, process it and try to send the message again.
    while (rc != 0) {
        if (errno != EAGAIN)
            return -1;
        if (unlikely (process_commands (true, false) != 0))
            return -1;
        rc = xsend (msg_, flags_);
    }
    return 0;
}
void zmq::object_t::send_activate_reader (class reader_t * destination_) [protected, inherited]
Definition at line 270 of file object.cpp.
References zmq::command_t::activate_reader, zmq::command_t::destination, and zmq::command_t::type.
{
    command_t cmd;
#if defined ZMQ_MAKE_VALGRIND_HAPPY
    memset (&cmd, 0, sizeof (cmd));
#endif
    cmd.destination = destination_;
    cmd.type = command_t::activate_reader;
    send_command (cmd);
}
void zmq::object_t::send_activate_writer (class writer_t * destination_, uint64_t msgs_read_) [protected, inherited]
Definition at line 281 of file object.cpp.
References zmq::command_t::activate_writer, zmq::command_t::args, zmq::command_t::destination, and zmq::command_t::type.
{
    command_t cmd;
#if defined ZMQ_MAKE_VALGRIND_HAPPY
    memset (&cmd, 0, sizeof (cmd));
#endif
    cmd.destination = destination_;
    cmd.type = command_t::activate_writer;
    cmd.args.activate_writer.msgs_read = msgs_read_;
    send_command (cmd);
}
void zmq::object_t::send_attach (class session_t * destination_, struct i_engine * engine_, const blob_t & peer_identity_, bool inc_seqnum_ = true) [protected, inherited]
Definition at line 209 of file object.cpp.
References alloc_assert, zmq::command_t::args, zmq::command_t::attach, zmq::command_t::destination, zmq::own_t::inc_seqnum(), zmq::command_t::type, and zmq_assert.
{
    if (inc_seqnum_)
        destination_->inc_seqnum ();
    command_t cmd;
#if defined ZMQ_MAKE_VALGRIND_HAPPY
    memset (&cmd, 0, sizeof (cmd));
#endif
    cmd.destination = destination_;
    cmd.type = command_t::attach;
    cmd.args.attach.engine = engine_;
    if (peer_identity_.empty ()) {
        cmd.args.attach.peer_identity_size = 0;
        cmd.args.attach.peer_identity = NULL;
    }
    else {
        zmq_assert (peer_identity_.size () <= 0xff);
        cmd.args.attach.peer_identity_size =
            (unsigned char) peer_identity_.size ();
        cmd.args.attach.peer_identity =
            (unsigned char*) malloc (peer_identity_.size ());
        alloc_assert (cmd.args.attach.peer_identity_size);
        memcpy (cmd.args.attach.peer_identity, peer_identity_.data (),
            peer_identity_.size ());
    }
    send_command (cmd);
}
void zmq::object_t::send_bind (class own_t * destination_, class reader_t * in_pipe_, class writer_t * out_pipe_, const blob_t & peer_identity_, bool inc_seqnum_ = true) [protected, inherited]
Definition at line 239 of file object.cpp.
References alloc_assert, zmq::command_t::args, zmq::command_t::bind, zmq::command_t::destination, zmq::own_t::inc_seqnum(), zmq::command_t::type, and zmq_assert.
{
    if (inc_seqnum_)
        destination_->inc_seqnum ();
    command_t cmd;
#if defined ZMQ_MAKE_VALGRIND_HAPPY
    memset (&cmd, 0, sizeof (cmd));
#endif
    cmd.destination = destination_;
    cmd.type = command_t::bind;
    cmd.args.bind.in_pipe = in_pipe_;
    cmd.args.bind.out_pipe = out_pipe_;
    if (peer_identity_.empty ()) {
        cmd.args.bind.peer_identity_size = 0;
        cmd.args.bind.peer_identity = NULL;
    }
    else {
        zmq_assert (peer_identity_.size () <= 0xff);
        cmd.args.bind.peer_identity_size =
            (unsigned char) peer_identity_.size ();
        cmd.args.bind.peer_identity =
            (unsigned char*) malloc (peer_identity_.size ());
        alloc_assert (cmd.args.bind.peer_identity_size);
        memcpy (cmd.args.bind.peer_identity, peer_identity_.data (),
            peer_identity_.size ());
    }
    send_command (cmd);
}
void zmq::object_t::send_done () [protected, inherited]
Definition at line 375 of file object.cpp.
References zmq::command_t::destination, zmq::command_t::done, zmq::ctx_t::term_tid, and zmq::command_t::type.
{
    command_t cmd;
#if defined ZMQ_MAKE_VALGRIND_HAPPY
    memset (&cmd, 0, sizeof (cmd));
#endif
    cmd.destination = NULL;
    cmd.type = command_t::done;
    ctx->send_command (ctx_t::term_tid, cmd);
}
void zmq::object_t::send_own (class own_t * destination_, class own_t * object_) [protected, inherited]
Definition at line 196 of file object.cpp.
References zmq::command_t::args, zmq::command_t::destination, zmq::own_t::inc_seqnum(), zmq::command_t::own, and zmq::command_t::type.
{
    destination_->inc_seqnum ();
    command_t cmd;
#if defined ZMQ_MAKE_VALGRIND_HAPPY
    memset (&cmd, 0, sizeof (cmd));
#endif
    cmd.destination = destination_;
    cmd.type = command_t::own;
    cmd.args.own.object = object_;
    send_command (cmd);
}
void zmq::object_t::send_pipe_term (class writer_t * destination_) [protected, inherited]
Definition at line 294 of file object.cpp.
References zmq::command_t::destination, zmq::command_t::pipe_term, and zmq::command_t::type.
{
    command_t cmd;
#if defined ZMQ_MAKE_VALGRIND_HAPPY
    memset (&cmd, 0, sizeof (cmd));
#endif
    cmd.destination = destination_;
    cmd.type = command_t::pipe_term;
    send_command (cmd);
}
void zmq::object_t::send_pipe_term_ack (class reader_t * destination_) [protected, inherited]
Definition at line 305 of file object.cpp.
References zmq::command_t::destination, zmq::command_t::pipe_term_ack, and zmq::command_t::type.
{
    command_t cmd;
#if defined ZMQ_MAKE_VALGRIND_HAPPY
    memset (&cmd, 0, sizeof (cmd));
#endif
    cmd.destination = destination_;
    cmd.type = command_t::pipe_term_ack;
    send_command (cmd);
}
void zmq::object_t::send_plug (class own_t * destination_, bool inc_seqnum_ = true) [protected, inherited]
Definition at line 182 of file object.cpp.
References zmq::command_t::destination, zmq::own_t::inc_seqnum(), zmq::command_t::plug, and zmq::command_t::type.
{
    if (inc_seqnum_)
        destination_->inc_seqnum ();
    command_t cmd;
#if defined ZMQ_MAKE_VALGRIND_HAPPY
    memset (&cmd, 0, sizeof (cmd));
#endif
    cmd.destination = destination_;
    cmd.type = command_t::plug;
    send_command (cmd);
}
void zmq::object_t::send_reap (class socket_base_t * socket_) [protected, inherited]
Definition at line 352 of file object.cpp.
References zmq::command_t::args, zmq::command_t::destination, zmq::command_t::reap, and zmq::command_t::type.
{
    command_t cmd;
#if defined ZMQ_MAKE_VALGRIND_HAPPY
    memset (&cmd, 0, sizeof (cmd));
#endif
    cmd.destination = ctx->get_reaper ();
    cmd.type = command_t::reap;
    cmd.args.reap.socket = socket_;
    send_command (cmd);
}
void zmq::object_t::send_reaped () [protected, inherited]
Definition at line 364 of file object.cpp.
References zmq::command_t::destination, zmq::command_t::reaped, and zmq::command_t::type.
{
    command_t cmd;
#if defined ZMQ_MAKE_VALGRIND_HAPPY
    memset (&cmd, 0, sizeof (cmd));
#endif
    cmd.destination = ctx->get_reaper ();
    cmd.type = command_t::reaped;
    send_command (cmd);
}
void zmq::object_t::send_stop () [protected, inherited]
Definition at line 169 of file object.cpp.
References zmq::command_t::destination, zmq::command_t::stop, and zmq::command_t::type.
{
    //  'stop' command goes always from administrative thread to
    //  the current object.
    command_t cmd;
#if defined ZMQ_MAKE_VALGRIND_HAPPY
    memset (&cmd, 0, sizeof (cmd));
#endif
    cmd.destination = this;
    cmd.type = command_t::stop;
    ctx->send_command (tid, cmd);
}
void zmq::object_t::send_term (class own_t * destination_, int linger_) [protected, inherited]
Definition at line 329 of file object.cpp.
References zmq::command_t::args, zmq::command_t::destination, zmq::command_t::term, and zmq::command_t::type.
{
    command_t cmd;
#if defined ZMQ_MAKE_VALGRIND_HAPPY
    memset (&cmd, 0, sizeof (cmd));
#endif
    cmd.destination = destination_;
    cmd.type = command_t::term;
    cmd.args.term.linger = linger_;
    send_command (cmd);
}
void zmq::object_t::send_term_ack (class own_t * destination_) [protected, inherited]
Definition at line 341 of file object.cpp.
References zmq::command_t::destination, zmq::command_t::term_ack, and zmq::command_t::type.
{
    command_t cmd;
#if defined ZMQ_MAKE_VALGRIND_HAPPY
    memset (&cmd, 0, sizeof (cmd));
#endif
    cmd.destination = destination_;
    cmd.type = command_t::term_ack;
    send_command (cmd);
}
void zmq::object_t::send_term_req (class own_t * destination_, class own_t * object_) [protected, inherited]
Definition at line 316 of file object.cpp.
References zmq::command_t::args, zmq::command_t::destination, zmq::command_t::term_req, and zmq::command_t::type.
{
    command_t cmd;
#if defined ZMQ_MAKE_VALGRIND_HAPPY
    memset (&cmd, 0, sizeof (cmd));
#endif
    cmd.destination = destination_;
    cmd.type = command_t::term_req;
    cmd.args.term_req.object = object_;
    send_command (cmd);
}
void zmq::array_item_t::set_array_index (int index_) [inline, inherited]
Definition at line 48 of file array.hpp.
References zmq::array_item_t::array_index.
        {
            array_index = index_;
        }
int zmq::socket_base_t::setsockopt (int option_, const void * optval_, size_t optvallen_) [inherited]
Definition at line 228 of file socket_base.cpp.
References ETERM, and unlikely.
{
    if (unlikely (ctx_terminated)) {
        errno = ETERM;
        return -1;
    }
    //  First, check whether specific socket type overloads the option.
    int rc = xsetsockopt (option_, optval_, optvallen_);
    if (rc == 0 || errno != EINVAL)
        return rc;
    //  If the socket type doesn't support the option, pass it to
    //  the generic option parser.
    return options.setsockopt (option_, optval_, optvallen_);
}
void zmq::socket_base_t::start_reaping (poller_t * poller_) [inherited]
Definition at line 651 of file socket_base.cpp.
Referenced by zmq::reaper_t::process_reap().
{
    poller = poller_;
    handle = poller->add_fd (mailbox.get_fd (), this);
    poller->set_pollin (handle);
}
void zmq::socket_base_t::stop () [inherited]
Definition at line 144 of file socket_base.cpp.
{
    //  Called by ctx when it is terminated (zmq_term).
    //  'stop' command is sent from the threads that called zmq_term to
    //  the thread owning the socket. This way, blocking call in the
    //  owner thread can be interrupted.
    send_stop ();
}
void zmq::own_t::terminate () [protected, inherited]
Reimplemented in zmq::session_t.
Definition at line 138 of file own.cpp.
Referenced by zmq::reaper_t::process_reap(), and zmq::session_t::terminate().
{
    //  If termination is already underway, there's no point
    //  in starting it anew.
    if (terminating)
        return;
    //  As for the root of the ownership tree, there's noone to terminate it,
    //  so it has to terminate itself.
    if (!owner) {
        process_term (options.linger);
        return;
    }
    //  If I am an owned object, I'll ask my owner to terminate me.
    send_term_req (owner, this);
}
void zmq::socket_base_t::terminated (class reader_t * pipe_) [inherited]
Reimplemented in zmq::pair_t, and zmq::xrep_t.
void zmq::socket_base_t::terminated (class writer_t * pipe_) [inherited]
Reimplemented in zmq::pair_t, and zmq::xrep_t.
void zmq::socket_base_t::timer_event (int id_) [virtual, inherited]
Implements zmq::i_poll_events.
Definition at line 789 of file socket_base.cpp.
References zmq_assert.
{
    zmq_assert (false);
}
void zmq::object_t::unregister_endpoints (class socket_base_t * socket_) [protected, inherited]
Definition at line 141 of file object.cpp.
{
    return ctx->unregister_endpoints (socket_);
}
void zmq::socket_base_t::unregister_session (const blob_t & name_) [inherited]
Definition at line 623 of file socket_base.cpp.
References zmq_assert.
{
    sessions_sync.lock ();
    sessions_t::iterator it = sessions.find (name_);
    zmq_assert (it != sessions.end ());
    sessions.erase (it);
    sessions_sync.unlock ();
}
void zmq::own_t::unregister_term_ack () [inherited]
Definition at line 178 of file own.cpp.
References zmq_assert.
{
    zmq_assert (term_acks > 0);
    term_acks--;
    //  This may be a last ack we are waiting for before termination...
    check_term_acks ();
}
void zmq::push_t::xattach_pipes (class reader_t * inpipe_, class writer_t * outpipe_, const blob_t & peer_identity_) [protected, virtual]
Implements zmq::socket_base_t.
Definition at line 39 of file push.cpp.
References zmq_assert.
{
    zmq_assert (!inpipe_ && outpipe_);
    lb.attach (outpipe_);
}
bool zmq::socket_base_t::xhas_in () [protected, virtual, inherited]
Reimplemented in zmq::pair_t, zmq::pull_t, zmq::rep_t, zmq::req_t, zmq::xpub_t, zmq::xrep_t, zmq::xreq_t, and zmq::xsub_t.
Definition at line 765 of file socket_base.cpp.
{
    return false;
}
bool zmq::push_t::xhas_out () [protected, virtual]
Reimplemented from zmq::socket_base_t.
Definition at line 57 of file push.cpp.
{
    return lb.has_out ();
}
int zmq::socket_base_t::xrecv (class msg_t * msg_, int options_) [protected, virtual, inherited]
Reimplemented in zmq::pair_t, zmq::pull_t, zmq::rep_t, zmq::req_t, zmq::xpub_t, zmq::xrep_t, zmq::xreq_t, and zmq::xsub_t.
Definition at line 770 of file socket_base.cpp.
References ENOTSUP.
{
    errno = ENOTSUP;
    return -1;
}
int zmq::push_t::xsend (class msg_t * msg_, int flags_) [protected, virtual]
Reimplemented from zmq::socket_base_t.
Definition at line 52 of file push.cpp.
{
    return lb.send (msg_, flags_);
}
int zmq::socket_base_t::xsetsockopt (int option_, const void * optval_, size_t optvallen_) [protected, virtual, inherited]
Reimplemented in zmq::sub_t.
Definition at line 747 of file socket_base.cpp.
{
    errno = EINVAL;
    return -1;
}
Member Data Documentation
lb_t zmq::push_t::lb [private]
Definition at line 51 of file push.hpp.
options_t zmq::own_t::options [protected, inherited]
Definition at line 95 of file own.hpp.
Referenced by zmq::pair_t::pair_t(), zmq::pub_t::pub_t(), zmq::pull_t::pull_t(), push_t(), zmq::rep_t::rep_t(), zmq::req_t::req_t(), zmq::sub_t::sub_t(), zmq::xpub_t::xpub_t(), zmq::xrep_t::xrep_t(), zmq::xreq_t::xreq_t(), zmq::xsub_t::xsub_t(), and zmq::zmq_init_t::zmq_init_t().
The documentation for this class was generated from the following files:
/home/travlr/src/libzmq/src/push.hpp
/home/travlr/src/libzmq/src/push.cpp