libzmq: zmq::tcp_connecter_t Class Reference
zmq::tcp_connecter_t Class Reference
#include <tcp_connecter.hpp>
Public Member Functions
tcp_connecter_t ()
~tcp_connecter_t ()
int close ()
fd_t connect ()
fd_t get_fd ()
int open ()
int set_address (const char *protocol, const char *addr_)
Private Member Functions
tcp_connecter_t (const tcp_connecter_t &)
const tcp_connecter_t & operator= (const tcp_connecter_t &)
Private Attributes
sockaddr_storage addr
socklen_t addr_len
fd_t s
Detailed Description
Definition at line 39 of file tcp_connecter.hpp.
Constructor & Destructor Documentation
zmq::tcp_connecter_t::tcp_connecter_t ()
Definition at line 147 of file tcp_connecter.cpp.
References addr.
                                     :
    s (retired_fd)
{
    memset (&addr, 0, sizeof (addr));
}
zmq::tcp_connecter_t::~tcp_connecter_t ()
Definition at line 153 of file tcp_connecter.cpp.
References zmq::retired_fd.
{
    if (s != retired_fd)
        close ();
}
zmq::tcp_connecter_t::tcp_connecter_t (const tcp_connecter_t &) [private]
Member Function Documentation
int zmq::tcp_connecter_t::close ()
Definition at line 264 of file tcp_connecter.cpp.
References zmq::retired_fd, and zmq_assert.
{
    zmq_assert (s != retired_fd);
    int rc = ::close (s);
    if (rc != 0)
        return -1;
    s = retired_fd;
    return 0;
}
zmq::fd_t zmq::tcp_connecter_t::connect ()
Definition at line 279 of file tcp_connecter.cpp.
References ECONNREFUSED, errno_assert, and zmq::retired_fd.
{
    //  Following code should handle both Berkeley-derived socket
    //  implementations and Solaris.
    int err = 0;
#if defined ZMQ_HAVE_HPUX
    int len = sizeof (err);
#else
    socklen_t len = sizeof (err);
#endif
    int rc = getsockopt (s, SOL_SOCKET, SO_ERROR, (char*) &err, &len);
    if (rc == -1)
        err = errno;
    if (err != 0) {
        //  Assert if the error was caused by 0MQ bug.
        //  Networking problems are OK. No need to assert.
        errno = err;
        errno_assert (errno == ECONNREFUSED || errno == ECONNRESET ||
            errno == ETIMEDOUT || errno == EHOSTUNREACH);
        return retired_fd;
    }
    fd_t result = s;
    s = retired_fd;
    return result;
}
zmq::fd_t zmq::tcp_connecter_t::get_fd ()
Definition at line 274 of file tcp_connecter.cpp.
{
    return s;
}
int zmq::tcp_connecter_t::open ()
Definition at line 170 of file tcp_connecter.cpp.
References EINPROGRESS, errno_assert, zmq::retired_fd, and zmq_assert.
{
    zmq_assert (s == retired_fd);
    struct sockaddr *sa = (struct sockaddr*) &addr;
    if (AF_UNIX != sa->sa_family) {
        //  Create the socket.
        s = socket (sa->sa_family, SOCK_STREAM, IPPROTO_TCP);
        if (s == -1)
            return -1;
        // Set to non-blocking mode.
#ifdef ZMQ_HAVE_OPENVMS
        int flags = 1;
        int rc = ioctl (s, FIONBIO, &flags);
        errno_assert (rc != -1);
#else
        int flags = fcntl (s, F_GETFL, 0);
        if (flags == -1)
            flags = 0;
        int rc = fcntl (s, F_SETFL, flags | O_NONBLOCK);
        errno_assert (rc != -1);
#endif
        //  Disable Nagle's algorithm.
        int flag = 1;
        rc = setsockopt (s, IPPROTO_TCP, TCP_NODELAY, (char*) &flag,
            sizeof (int));
        errno_assert (rc == 0);
#ifdef ZMQ_HAVE_OPENVMS
        //  Disable delayed acknowledgements.
        flag = 1;
        rc = setsockopt (s, IPPROTO_TCP, TCP_NODELACK, (char*) &flag,
            sizeof (int));
        errno_assert (rc != SOCKET_ERROR);
#endif
        //  Connect to the remote peer.
        rc = ::connect (s, (struct sockaddr*) &addr, addr_len);
        //  Connect was successfull immediately.
        if (rc == 0)
            return 0;
        //  Asynchronous connect was launched.
        if (rc == -1 && errno == EINPROGRESS) {
            errno = EAGAIN;
            return -1;
        }
        //  Error occured.
        int err = errno;
        close ();
        errno = err;
        return -1;
    }
#ifndef ZMQ_HAVE_OPENVMS
    else {
        //  Create the socket.
        zmq_assert (AF_UNIX == sa->sa_family);
        s = socket (AF_UNIX, SOCK_STREAM, 0);
        if (s == -1)
            return -1;
        //  Set the non-blocking flag.
        int flag = fcntl (s, F_GETFL, 0);
        if (flag == -1)
            flag = 0;
        int rc = fcntl (s, F_SETFL, flag | O_NONBLOCK);
        errno_assert (rc != -1);
        //  Connect to the remote peer.
        rc = ::connect (s, (struct sockaddr*) &addr, sizeof (sockaddr_un));
        //  Connect was successfull immediately.
        if (rc == 0)
            return 0;
        //  Error occured.
        int err = errno;
        close ();
        errno = err;
        return -1;
    }
#endif
    zmq_assert (false);
    return -1;
}
const tcp_connecter_t& zmq::tcp_connecter_t::operator= (const tcp_connecter_t &) [private]
int zmq::tcp_connecter_t::set_address (const char * protocol, const char * addr_)
Definition at line 159 of file tcp_connecter.cpp.
References EPROTONOSUPPORT, zmq::resolve_ip_hostname(), and zmq::resolve_local_path().
Referenced by zmq::zmq_connecter_t::zmq_connecter_t().
{
    if (strcmp (protocol_, "tcp") == 0)
        return resolve_ip_hostname (&addr, &addr_len, addr_);
    else if (strcmp (protocol_, "ipc") == 0)
        return resolve_local_path (&addr, &addr_len, addr_);
    errno = EPROTONOSUPPORT;
    return -1;
}
Member Data Documentation
sockaddr_storage zmq::tcp_connecter_t::addr [private]
Definition at line 69 of file tcp_connecter.hpp.
Referenced by tcp_connecter_t().
socklen_t zmq::tcp_connecter_t::addr_len [private]
Definition at line 70 of file tcp_connecter.hpp.
fd_t zmq::tcp_connecter_t::s [private]
Definition at line 73 of file tcp_connecter.hpp.
The documentation for this class was generated from the following files:
/home/travlr/src/libzmq/src/tcp_connecter.hpp
/home/travlr/src/libzmq/src/tcp_connecter.cpp