libzmq: zmq::session_t Class Reference
zmq::session_t Class Reference
#include <session.hpp>
Public Member Functions
session_t (class io_thread_t *io_thread_, class socket_base_t *socket_, const options_t &options_)
void activated (class writer_t *pipe_)
void activated (class reader_t *pipe_)
void attach_pipes (class reader_t *inpipe_, class writer_t *outpipe_, const blob_t &peer_identity_)
void delimited (class reader_t *pipe_)
void detach ()
void flush ()
ctx_t * get_ctx ()
uint32_t get_tid ()
void inc_seqnum ()
void plug (class io_thread_t *io_thread_)
void process_command (struct command_t &cmd_)
bool read (msg_t *msg_)
void register_term_acks (int count_)
void terminated (class reader_t *pipe_)
void terminated (class writer_t *pipe_)
void unplug ()
void unregister_term_ack ()
bool write (msg_t *msg_)
Protected Types
typedef poller_t::handle_t handle_t
Protected Member Functions
~session_t ()
handle_t add_fd (fd_t fd_)
void add_timer (int timout_, int id_)
virtual bool attached (const blob_t &peer_identity_)=0
void cancel_timer (int id_)
class io_thread_t * choose_io_thread (uint64_t affinity_)
void destroy_socket (class socket_base_t *socket_)
virtual void detached ()=0
struct endpoint_t find_endpoint (const char *addr_)
bool has_engine ()
void in_event ()
void launch_child (own_t *object_)
void launch_sibling (own_t *object_)
void log (const char *format_,...)
void out_event ()
virtual void process_activate_reader ()
virtual void process_activate_writer (uint64_t msgs_read_)
virtual void process_bind (class reader_t *in_pipe_, class writer_t *out_pipe_, const blob_t &peer_identity_)
virtual void process_destroy ()
virtual void process_pipe_term ()
virtual void process_pipe_term_ack ()
virtual void process_reap (class socket_base_t *socket_)
virtual void process_reaped ()
virtual void process_stop ()
int register_endpoint (const char *addr_, struct endpoint_t &endpoint_)
bool register_session (const blob_t &name_, class session_t *session_)
void reset_pollin (handle_t handle_)
void reset_pollout (handle_t handle_)
void rm_fd (handle_t handle_)
void send_activate_reader (class reader_t *destination_)
void send_activate_writer (class writer_t *destination_, uint64_t msgs_read_)
void send_attach (class session_t *destination_, struct i_engine *engine_, const blob_t &peer_identity_, bool inc_seqnum_=true)
void send_bind (class own_t *destination_, class reader_t *in_pipe_, class writer_t *out_pipe_, const blob_t &peer_identity_, bool inc_seqnum_=true)
void send_done ()
void send_own (class own_t *destination_, class own_t *object_)
void send_pipe_term (class writer_t *destination_)
void send_pipe_term_ack (class reader_t *destination_)
void send_plug (class own_t *destination_, bool inc_seqnum_=true)
void send_reap (class socket_base_t *socket_)
void send_reaped ()
void send_stop ()
void send_term (class own_t *destination_, int linger_)
void send_term_ack (class own_t *destination_)
void send_term_req (class own_t *destination_, class own_t *object_)
void set_pollin (handle_t handle_)
void set_pollout (handle_t handle_)
void terminate ()
void unregister_endpoints (class socket_base_t *socket_)
void unregister_session (const blob_t &name_)
Protected Attributes
options_t options
Private Types
enum { linger_timer_id = 0x20 }
enum { active, pending, terminating }
Private Member Functions
session_t (const session_t &)
void clean_pipes ()
const session_t & operator= (const session_t &)
void proceed_with_term ()
void process_attach (struct i_engine *engine_, const blob_t &peer_identity_)
void process_plug ()
void process_term (int linger_)
void timer_event (int id_)
Private Attributes
bool delimiter_processed
struct i_engine * engine
bool force_terminate
bool has_linger_timer
class reader_t * in_pipe
bool incomplete_in
class io_thread_t * io_thread
class writer_t * out_pipe
bool pipes_attached
class socket_base_t * socket
enum zmq::session_t:: { ... } state
Detailed Description
Definition at line 33 of file session.hpp.
Member Typedef Documentation
typedef poller_t::handle_t zmq::io_object_t::handle_t [protected, inherited]
Definition at line 51 of file io_object.hpp.
Member Enumeration Documentation
anonymous enum [private]
Enumerator:
linger_timer_id
Definition at line 137 of file session.hpp.
{linger_timer_id = 0x20};
anonymous enum [private]
Enumerator:
active
pending
terminating
Definition at line 142 of file session.hpp.
             {
            active,
            pending,
            terminating
        } state;
Constructor & Destructor Documentation
zmq::session_t::session_t (class io_thread_t * io_thread_, class socket_base_t * socket_, const options_t & options_)
Definition at line 28 of file session.cpp.
                                                               :
    own_t (io_thread_, options_),
    io_object_t (io_thread_),
    in_pipe (NULL),
    incomplete_in (false),
    out_pipe (NULL),
    engine (NULL),
    socket (socket_),
    io_thread (io_thread_),
    pipes_attached (false),
    delimiter_processed (false),
    force_terminate (false),
    has_linger_timer (false),
    state (active)
{
}
zmq::session_t::~session_t () [protected]
Definition at line 46 of file session.cpp.
References zmq_assert.
{
    zmq_assert (!in_pipe);
    zmq_assert (!out_pipe);
    if (engine)
        engine->terminate ();
}
zmq::session_t::session_t (const session_t &) [private]
Member Function Documentation
void zmq::session_t::activated (class reader_t * pipe_) [virtual]
Implements zmq::i_reader_events.
Definition at line 196 of file session.cpp.
References likely, and zmq_assert.
{
    zmq_assert (in_pipe == pipe_);
    if (likely (engine != NULL))
        engine->activate_out ();
    else
        in_pipe->check_read ();
}
void zmq::session_t::activated (class writer_t * pipe_) [virtual]
Implements zmq::i_writer_events.
Definition at line 206 of file session.cpp.
References zmq_assert.
{
    zmq_assert (out_pipe == pipe_);
    if (engine)
        engine->activate_in ();
}
zmq::io_object_t::handle_t zmq::io_object_t::add_fd (fd_t fd_) [protected, inherited]
Definition at line 54 of file io_object.cpp.
{
    return poller->add_fd (fd_, this);
}
void zmq::io_object_t::add_timer (int timout_, int id_) [protected, inherited]
Definition at line 84 of file io_object.cpp.
{
    poller->add_timer (timeout_, this, id_);
}
void zmq::session_t::attach_pipes (class reader_t * inpipe_, class writer_t * outpipe_, const blob_t & peer_identity_)
Definition at line 137 of file session.cpp.
References zmq::writer_t::set_event_sink(), zmq::reader_t::set_event_sink(), and zmq_assert.
Referenced by zmq::socket_base_t::connect().
{
    zmq_assert (!pipes_attached);
    pipes_attached = true;
    if (inpipe_) {
        zmq_assert (!in_pipe);
        in_pipe = inpipe_;
        in_pipe->set_event_sink (this);
    }
    if (outpipe_) {
        zmq_assert (!out_pipe);
        out_pipe = outpipe_;
        out_pipe->set_event_sink (this);
    }
    //  If we are already terminating, terminate the pipes straight away.
    if (state == terminating) {
        if (in_pipe) {
            in_pipe->terminate ();
            register_term_acks (1);
        }
        if (out_pipe) {
            out_pipe->terminate ();
            register_term_acks (1);
        }
    }
}
virtual bool zmq::session_t::attached (const blob_t & peer_identity_) [protected, pure virtual]
Implemented in zmq::connect_session_t, zmq::named_session_t, and zmq::transient_session_t.
void zmq::io_object_t::cancel_timer (int id_) [protected, inherited]
Definition at line 89 of file io_object.cpp.
{
    poller->cancel_timer (this, id_);
}
zmq::io_thread_t * zmq::object_t::choose_io_thread (uint64_t affinity_) [protected, inherited]
Definition at line 164 of file object.cpp.
References zmq::object_t::choose_io_thread().
Referenced by zmq::object_t::choose_io_thread().
{
    return ctx->choose_io_thread (affinity_);
}
void zmq::session_t::clean_pipes () [private]
Definition at line 112 of file session.cpp.
References zmq::msg_t::close(), errno_assert, zmq::msg_t::init(), and zmq_assert.
{
    //  Get rid of half-processed messages in the out pipe. Flush any
    //  unflushed messages upstream.
    if (out_pipe) {
        out_pipe->rollback ();
        out_pipe->flush ();
    }
    //  Remove any half-read message from the in pipe.
    if (in_pipe) {
        while (incomplete_in) {
            msg_t msg;
            int rc = msg.init ();
            errno_assert (rc == 0);
            if (!read (&msg)) {
                zmq_assert (!incomplete_in);
                break;
            }
            rc = msg.close ();
            errno_assert (rc == 0);
        }
    }
}
void zmq::session_t::delimited (class reader_t * pipe_) [virtual]
Implements zmq::i_reader_events.
Definition at line 168 of file session.cpp.
References zmq_assert.
{
    zmq_assert (in_pipe == pipe_);
    zmq_assert (!delimiter_processed);
    delimiter_processed = true;
    //  If we are in process of being closed, but still waiting for all
    //  pending messeges being sent, we can terminate here.
    if (state == pending)
        proceed_with_term ();
}
void zmq::object_t::destroy_socket (class socket_base_t * socket_) [protected, inherited]
Definition at line 151 of file object.cpp.
{
    ctx->destroy_socket (socket_);
}
void zmq::session_t::detach () [virtual]
Implements zmq::i_inout.
Definition at line 274 of file session.cpp.
{
    //  Engine is dead. Let's forget about it.
    engine = NULL;
    //  Remove any half-done messages from the pipes.
    clean_pipes ();
    //  Send the event to the derived class.
    detached ();
    //  Just in case, there's only a delimiter in the inbound pipe.
    if (in_pipe)
        in_pipe->check_read ();
}
virtual void zmq::session_t::detached () [protected, pure virtual]
Implemented in zmq::connect_session_t, zmq::named_session_t, and zmq::transient_session_t.
zmq::endpoint_t zmq::object_t::find_endpoint (const char * addr_) [read, protected, inherited]
Definition at line 146 of file object.cpp.
{
    return ctx->find_endpoint (addr_);
}
void zmq::session_t::flush () [virtual]
Implements zmq::i_inout.
Definition at line 106 of file session.cpp.
{
    if (out_pipe)
        out_pipe->flush ();
}
zmq::ctx_t * zmq::object_t::get_ctx () [inherited]
Definition at line 53 of file object.cpp.
{
    return ctx;
}
uint32_t zmq::object_t::get_tid () [inherited]
Definition at line 48 of file object.cpp.
Referenced by zmq::ctx_t::destroy_socket(), and zmq::object_t::send_command().
{
    return tid;
}
bool zmq::session_t::has_engine () [protected]
Definition at line 333 of file session.cpp.
{
    return engine != NULL;
}
void zmq::io_object_t::in_event () [protected, virtual, inherited]
Implements zmq::i_poll_events.
Reimplemented in zmq::zmq_connecter_t, zmq::zmq_engine_t, and zmq::zmq_listener_t.
Definition at line 94 of file io_object.cpp.
References zmq_assert.
{
    zmq_assert (false);
}
void zmq::own_t::inc_seqnum () [inherited]
Definition at line 56 of file own.cpp.
Referenced by zmq::ctx_t::find_endpoint(), zmq::socket_base_t::find_session(), zmq::object_t::send_attach(), zmq::object_t::send_bind(), zmq::object_t::send_own(), and zmq::object_t::send_plug().
{
    //  This function may be called from a different thread!
    sent_seqnum.add (1);
}
void zmq::own_t::launch_child (own_t * object_) [protected, inherited]
Definition at line 71 of file own.cpp.
References zmq::own_t::set_owner().
{
    //  Specify the owner of the object.
    object_->set_owner (this);
    //  Plug the object into the I/O thread.
    send_plug (object_);
    //  Take ownership of the object.
    send_own (this, object_);
}
void zmq::own_t::launch_sibling (own_t * object_) [protected, inherited]
Definition at line 83 of file own.cpp.
References zmq::own_t::set_owner().
{
    //  At this point it is important that object is plugged in before its
    //  owner has a chance to terminate it. Thus, 'plug' command is sent before
    //  the 'own' command. Given that the mailbox preserves ordering of
    //  commands, 'term' command from the owner cannot make it to the object
    //  before the already written 'plug' command.
    //  Specify the owner of the object.
    object_->set_owner (owner);
    //  Plug the object into its I/O thread.
    send_plug (object_);
    //  Make parent own the object.
    send_own (owner, object_);
}
void zmq::object_t::log (const char * format_, ...) [protected, inherited]
Definition at line 156 of file object.cpp.
{
    va_list args;
    va_start (args, format_);
    ctx->log (format_, args);
    va_end (args);
}
const session_t& zmq::session_t::operator= (const session_t &) [private]
void zmq::io_object_t::out_event () [protected, virtual, inherited]
Implements zmq::i_poll_events.
Reimplemented in zmq::zmq_connecter_t, and zmq::zmq_engine_t.
Definition at line 99 of file io_object.cpp.
References zmq_assert.
{
    zmq_assert (false);
}
void zmq::io_object_t::plug (class io_thread_t * io_thread_) [inherited]
Definition at line 36 of file io_object.cpp.
References zmq::io_thread_t::get_poller(), and zmq_assert.
Referenced by zmq::io_object_t::io_object_t(), and zmq::zmq_engine_t::plug().
{
    zmq_assert (io_thread_);
    zmq_assert (!poller);
    //  Retrieve the poller from the thread we are running in.
    poller = io_thread_->get_poller ();
}
void zmq::session_t::proceed_with_term () [private]
Definition at line 55 of file session.cpp.
References zmq::own_t::process_term(), and zmq_assert.
{
    if (state == terminating)
        return;
    zmq_assert (state == pending);
    state = terminating;
    //  If there's still a pending linger timer, remove it.
    if (has_linger_timer) {
        cancel_timer (linger_timer_id);
        has_linger_timer = false;
    }
    if (in_pipe) {
        register_term_acks (1);
        in_pipe->terminate ();
    }
    if (out_pipe) {
        register_term_acks (1);
        out_pipe->terminate ();
    }
    //  The session has already waited for the linger period. We don't want
    //  the child objects to linger any more thus linger is set to zero.
    own_t::process_term (0);
}
void zmq::object_t::process_activate_reader () [protected, virtual, inherited]
Reimplemented in zmq::reader_t.
Definition at line 413 of file object.cpp.
References zmq_assert.
{
    zmq_assert (false);
}
void zmq::object_t::process_activate_writer (uint64_t msgs_read_) [protected, virtual, inherited]
Reimplemented in zmq::writer_t.
Definition at line 418 of file object.cpp.
References zmq_assert.
{
    zmq_assert (false);
}
void zmq::session_t::process_attach (struct i_engine * engine_, const blob_t & peer_identity_) [private, virtual]
Reimplemented from zmq::object_t.
Definition at line 217 of file session.cpp.
References zmq::create_pipe(), zmq::i_engine::plug(), and zmq_assert.
{
    //  If we are already terminating, we destroy the engine straight away.
    //  Note that we don't have to unplug it before deleting as it's not
    //  yet plugged to the session.
    if (state == terminating) {
        if (engine_)
            delete engine_;
        return;
    }
    //  If some other object (e.g. init) notifies us that the connection failed
    //  without creating an engine we need to start the reconnection process.
    if (!engine_) {
        zmq_assert (!engine);
        detached ();
        return;
    }
    //  Trigger the notfication event about the attachment.
    if (!attached (peer_identity_)) {
        delete engine_;
        return;
    }
    //  Check whether the required pipes already exist. If not so, we'll
    //  create them and bind them to the socket object.
    if (!pipes_attached) {
        zmq_assert (!in_pipe && !out_pipe);
        pipes_attached = true;
        reader_t *socket_reader = NULL;
        writer_t *socket_writer = NULL;
        //  Create the pipes, as required.
        if (options.requires_in) {
            create_pipe (socket, this, options.rcvhwm, &socket_reader,
                &out_pipe);
            out_pipe->set_event_sink (this);
        }
        if (options.requires_out) {
            create_pipe (this, socket, options.sndhwm, &in_pipe,
                &socket_writer);
            in_pipe->set_event_sink (this);
        }
        //  Bind the pipes to the socket object.
        if (socket_reader || socket_writer)
            send_bind (socket, socket_reader, socket_writer, peer_identity_);
    }
    //  Plug in the engine.
    zmq_assert (!engine);
    engine = engine_;
    engine->plug (io_thread, this);
}
void zmq::object_t::process_bind (class reader_t * in_pipe_, class writer_t * out_pipe_, const blob_t & peer_identity_) [protected, virtual, inherited]
Reimplemented in zmq::socket_base_t.
Definition at line 407 of file object.cpp.
References zmq_assert.
{
    zmq_assert (false);
}
void zmq::object_t::process_command (struct command_t & cmd_) [inherited]
Definition at line 58 of file object.cpp.
References zmq::command_t::activate_reader, zmq::command_t::activate_writer, zmq::command_t::args, zmq::command_t::attach, zmq::command_t::bind, zmq::deallocate_command(), zmq::command_t::own, zmq::command_t::pipe_term, zmq::command_t::pipe_term_ack, zmq::command_t::plug, zmq::command_t::reap, zmq::command_t::reaped, zmq::command_t::stop, zmq::command_t::term, zmq::command_t::term_ack, zmq::command_t::term_req, zmq::command_t::type, and zmq_assert.
Referenced by zmq::reaper_t::in_event(), zmq::io_thread_t::in_event(), and zmq::socket_base_t::process_commands().
{
    switch (cmd_.type) {
    case command_t::activate_reader:
        process_activate_reader ();
        break;
    case command_t::activate_writer:
        process_activate_writer (cmd_.args.activate_writer.msgs_read);
        break;
    case command_t::stop:
        process_stop ();
        break;
    case command_t::plug:
        process_plug ();
        process_seqnum ();
        return;
    case command_t::own:
        process_own (cmd_.args.own.object);
        process_seqnum ();
        break;
    case command_t::attach:
        process_attach (cmd_.args.attach.engine,
            cmd_.args.attach.peer_identity ?
            blob_t (cmd_.args.attach.peer_identity,
            cmd_.args.attach.peer_identity_size) : blob_t ());
        process_seqnum ();
        break;
    case command_t::bind:
        process_bind (cmd_.args.bind.in_pipe, cmd_.args.bind.out_pipe,
            cmd_.args.bind.peer_identity ? blob_t (cmd_.args.bind.peer_identity,
            cmd_.args.bind.peer_identity_size) : blob_t ());
        process_seqnum ();
        break;
    case command_t::pipe_term:
        process_pipe_term ();
        return;
    case command_t::pipe_term_ack:
        process_pipe_term_ack ();
        break;
    case command_t::term_req:
        process_term_req (cmd_.args.term_req.object);
        break;
    case command_t::term:
        process_term (cmd_.args.term.linger);
        break;
    case command_t::term_ack:
        process_term_ack ();
        break;
    case command_t::reap:
        process_reap (cmd_.args.reap.socket);
        break;
    case command_t::reaped:
        process_reaped ();
        break;
    default:
        zmq_assert (false);
    }
    //  The assumption here is that each command is processed once only,
    //  so deallocating it after processing is all right.
    deallocate_command (&cmd_);
}
void zmq::own_t::process_destroy () [protected, virtual, inherited]
Reimplemented in zmq::socket_base_t.
Definition at line 210 of file own.cpp.
Referenced by zmq::socket_base_t::check_destroy().
{
    delete this;
}
void zmq::object_t::process_pipe_term () [protected, virtual, inherited]
Reimplemented in zmq::writer_t.
Definition at line 423 of file object.cpp.
References zmq_assert.
{
    zmq_assert (false);
}
void zmq::object_t::process_pipe_term_ack () [protected, virtual, inherited]
Reimplemented in zmq::reader_t.
Definition at line 428 of file object.cpp.
References zmq_assert.
{
    zmq_assert (false);
}
void zmq::session_t::process_plug () [private, virtual]
Reimplemented from zmq::object_t.
Reimplemented in zmq::connect_session_t.
Definition at line 213 of file session.cpp.
{
}
void zmq::object_t::process_reap (class socket_base_t * socket_) [protected, virtual, inherited]
Reimplemented in zmq::reaper_t.
Definition at line 448 of file object.cpp.
References zmq_assert.
{
    zmq_assert (false);
}
void zmq::object_t::process_reaped () [protected, virtual, inherited]
Reimplemented in zmq::reaper_t.
Definition at line 453 of file object.cpp.
References zmq_assert.
{
    zmq_assert (false);
}
void zmq::object_t::process_stop () [protected, virtual, inherited]
Reimplemented in zmq::io_thread_t, zmq::reaper_t, and zmq::socket_base_t.
Definition at line 386 of file object.cpp.
References zmq_assert.
{
    zmq_assert (false);
}
void zmq::session_t::process_term (int linger_) [private, virtual]
Reimplemented from zmq::own_t.
Definition at line 290 of file session.cpp.
References zmq_assert.
{
    zmq_assert (state == active);
    state = pending;
    //  If linger is set to zero, we can terminate the session straight away
    //  not waiting for the pending messages to be sent.
    if (linger_ == 0) {
        proceed_with_term ();
        return;
    }
    //  If there's finite linger value, set up a timer.
    if (linger_ > 0) {
       zmq_assert (!has_linger_timer);
       add_timer (linger_, linger_timer_id);
       has_linger_timer = true;
    }
    //  If there's no engine and there's only delimiter in the pipe it wouldn't
    //  be ever read. Thus we check for it explicitly.
    if (in_pipe)
        in_pipe->check_read ();
    //  If there's no in pipe there are no pending messages to send.
    //  We can proceed with the shutdown straight away. Also, if there is
    //  inbound pipe, but the delimiter was already processed, we can
    //  terminate immediately. Alternatively, if the derived session type have
    //  called 'terminate' we'll finish straight away.
    if (!options.requires_out || delimiter_processed || force_terminate ||
        (!options.immediate_connect && !in_pipe))
        proceed_with_term ();
}
bool zmq::session_t::read (msg_t * msg_) [virtual]
Implements zmq::i_inout.
Definition at line 83 of file session.cpp.
References zmq::msg_t::flags, and zmq::msg_t::more.
{
    if (!in_pipe)
        return false;
    if (!in_pipe->read (msg_))
        return false;
    incomplete_in = msg_->flags () & msg_t::more;
    return true;
}
int zmq::object_t::register_endpoint (const char * addr_, struct endpoint_t & endpoint_) [protected, inherited]
Definition at line 136 of file object.cpp.
{
    return ctx->register_endpoint (addr_, endpoint_);
}
bool zmq::session_t::register_session (const blob_t & name_, class session_t * session_) [protected]
Definition at line 338 of file session.cpp.
{
    return socket->register_session (name_, session_);
}
void zmq::own_t::register_term_acks (int count_) [inherited]
Definition at line 173 of file own.cpp.
{
    term_acks += count_;
}
void zmq::io_object_t::reset_pollin (handle_t handle_) [protected, inherited]
Definition at line 69 of file io_object.cpp.
{
    poller->reset_pollin (handle_);
}
void zmq::io_object_t::reset_pollout (handle_t handle_) [protected, inherited]
Definition at line 79 of file io_object.cpp.
{
    poller->reset_pollout (handle_);
}
void zmq::io_object_t::rm_fd (handle_t handle_) [protected, inherited]
Definition at line 59 of file io_object.cpp.
{
    poller->rm_fd (handle_);
}
void zmq::object_t::send_activate_reader (class reader_t * destination_) [protected, inherited]
Definition at line 270 of file object.cpp.
References zmq::command_t::activate_reader, zmq::command_t::destination, and zmq::command_t::type.
{
    command_t cmd;
#if defined ZMQ_MAKE_VALGRIND_HAPPY
    memset (&cmd, 0, sizeof (cmd));
#endif
    cmd.destination = destination_;
    cmd.type = command_t::activate_reader;
    send_command (cmd);
}
void zmq::object_t::send_activate_writer (class writer_t * destination_, uint64_t msgs_read_) [protected, inherited]
Definition at line 281 of file object.cpp.
References zmq::command_t::activate_writer, zmq::command_t::args, zmq::command_t::destination, and zmq::command_t::type.
{
    command_t cmd;
#if defined ZMQ_MAKE_VALGRIND_HAPPY
    memset (&cmd, 0, sizeof (cmd));
#endif
    cmd.destination = destination_;
    cmd.type = command_t::activate_writer;
    cmd.args.activate_writer.msgs_read = msgs_read_;
    send_command (cmd);
}
void zmq::object_t::send_attach (class session_t * destination_, struct i_engine * engine_, const blob_t & peer_identity_, bool inc_seqnum_ = true) [protected, inherited]
Definition at line 209 of file object.cpp.
References alloc_assert, zmq::command_t::args, zmq::command_t::attach, zmq::command_t::destination, zmq::own_t::inc_seqnum(), zmq::command_t::type, and zmq_assert.
{
    if (inc_seqnum_)
        destination_->inc_seqnum ();
    command_t cmd;
#if defined ZMQ_MAKE_VALGRIND_HAPPY
    memset (&cmd, 0, sizeof (cmd));
#endif
    cmd.destination = destination_;
    cmd.type = command_t::attach;
    cmd.args.attach.engine = engine_;
    if (peer_identity_.empty ()) {
        cmd.args.attach.peer_identity_size = 0;
        cmd.args.attach.peer_identity = NULL;
    }
    else {
        zmq_assert (peer_identity_.size () <= 0xff);
        cmd.args.attach.peer_identity_size =
            (unsigned char) peer_identity_.size ();
        cmd.args.attach.peer_identity =
            (unsigned char*) malloc (peer_identity_.size ());
        alloc_assert (cmd.args.attach.peer_identity_size);
        memcpy (cmd.args.attach.peer_identity, peer_identity_.data (),
            peer_identity_.size ());
    }
    send_command (cmd);
}
void zmq::object_t::send_bind (class own_t * destination_, class reader_t * in_pipe_, class writer_t * out_pipe_, const blob_t & peer_identity_, bool inc_seqnum_ = true) [protected, inherited]
Definition at line 239 of file object.cpp.
References alloc_assert, zmq::command_t::args, zmq::command_t::bind, zmq::command_t::destination, zmq::own_t::inc_seqnum(), zmq::command_t::type, and zmq_assert.
{
    if (inc_seqnum_)
        destination_->inc_seqnum ();
    command_t cmd;
#if defined ZMQ_MAKE_VALGRIND_HAPPY
    memset (&cmd, 0, sizeof (cmd));
#endif
    cmd.destination = destination_;
    cmd.type = command_t::bind;
    cmd.args.bind.in_pipe = in_pipe_;
    cmd.args.bind.out_pipe = out_pipe_;
    if (peer_identity_.empty ()) {
        cmd.args.bind.peer_identity_size = 0;
        cmd.args.bind.peer_identity = NULL;
    }
    else {
        zmq_assert (peer_identity_.size () <= 0xff);
        cmd.args.bind.peer_identity_size =
            (unsigned char) peer_identity_.size ();
        cmd.args.bind.peer_identity =
            (unsigned char*) malloc (peer_identity_.size ());
        alloc_assert (cmd.args.bind.peer_identity_size);
        memcpy (cmd.args.bind.peer_identity, peer_identity_.data (),
            peer_identity_.size ());
    }
    send_command (cmd);
}
void zmq::object_t::send_done () [protected, inherited]
Definition at line 375 of file object.cpp.
References zmq::command_t::destination, zmq::command_t::done, zmq::ctx_t::term_tid, and zmq::command_t::type.
{
    command_t cmd;
#if defined ZMQ_MAKE_VALGRIND_HAPPY
    memset (&cmd, 0, sizeof (cmd));
#endif
    cmd.destination = NULL;
    cmd.type = command_t::done;
    ctx->send_command (ctx_t::term_tid, cmd);
}
void zmq::object_t::send_own (class own_t * destination_, class own_t * object_) [protected, inherited]
Definition at line 196 of file object.cpp.
References zmq::command_t::args, zmq::command_t::destination, zmq::own_t::inc_seqnum(), zmq::command_t::own, and zmq::command_t::type.
{
    destination_->inc_seqnum ();
    command_t cmd;
#if defined ZMQ_MAKE_VALGRIND_HAPPY
    memset (&cmd, 0, sizeof (cmd));
#endif
    cmd.destination = destination_;
    cmd.type = command_t::own;
    cmd.args.own.object = object_;
    send_command (cmd);
}
void zmq::object_t::send_pipe_term (class writer_t * destination_) [protected, inherited]
Definition at line 294 of file object.cpp.
References zmq::command_t::destination, zmq::command_t::pipe_term, and zmq::command_t::type.
{
    command_t cmd;
#if defined ZMQ_MAKE_VALGRIND_HAPPY
    memset (&cmd, 0, sizeof (cmd));
#endif
    cmd.destination = destination_;
    cmd.type = command_t::pipe_term;
    send_command (cmd);
}
void zmq::object_t::send_pipe_term_ack (class reader_t * destination_) [protected, inherited]
Definition at line 305 of file object.cpp.
References zmq::command_t::destination, zmq::command_t::pipe_term_ack, and zmq::command_t::type.
{
    command_t cmd;
#if defined ZMQ_MAKE_VALGRIND_HAPPY
    memset (&cmd, 0, sizeof (cmd));
#endif
    cmd.destination = destination_;
    cmd.type = command_t::pipe_term_ack;
    send_command (cmd);
}
void zmq::object_t::send_plug (class own_t * destination_, bool inc_seqnum_ = true) [protected, inherited]
Definition at line 182 of file object.cpp.
References zmq::command_t::destination, zmq::own_t::inc_seqnum(), zmq::command_t::plug, and zmq::command_t::type.
{
    if (inc_seqnum_)
        destination_->inc_seqnum ();
    command_t cmd;
#if defined ZMQ_MAKE_VALGRIND_HAPPY
    memset (&cmd, 0, sizeof (cmd));
#endif
    cmd.destination = destination_;
    cmd.type = command_t::plug;
    send_command (cmd);
}
void zmq::object_t::send_reap (class socket_base_t * socket_) [protected, inherited]
Definition at line 352 of file object.cpp.
References zmq::command_t::args, zmq::command_t::destination, zmq::command_t::reap, and zmq::command_t::type.
{
    command_t cmd;
#if defined ZMQ_MAKE_VALGRIND_HAPPY
    memset (&cmd, 0, sizeof (cmd));
#endif
    cmd.destination = ctx->get_reaper ();
    cmd.type = command_t::reap;
    cmd.args.reap.socket = socket_;
    send_command (cmd);
}
void zmq::object_t::send_reaped () [protected, inherited]
Definition at line 364 of file object.cpp.
References zmq::command_t::destination, zmq::command_t::reaped, and zmq::command_t::type.
{
    command_t cmd;
#if defined ZMQ_MAKE_VALGRIND_HAPPY
    memset (&cmd, 0, sizeof (cmd));
#endif
    cmd.destination = ctx->get_reaper ();
    cmd.type = command_t::reaped;
    send_command (cmd);
}
void zmq::object_t::send_stop () [protected, inherited]
Definition at line 169 of file object.cpp.
References zmq::command_t::destination, zmq::command_t::stop, and zmq::command_t::type.
{
    //  'stop' command goes always from administrative thread to
    //  the current object.
    command_t cmd;
#if defined ZMQ_MAKE_VALGRIND_HAPPY
    memset (&cmd, 0, sizeof (cmd));
#endif
    cmd.destination = this;
    cmd.type = command_t::stop;
    ctx->send_command (tid, cmd);
}
void zmq::object_t::send_term (class own_t * destination_, int linger_) [protected, inherited]
Definition at line 329 of file object.cpp.
References zmq::command_t::args, zmq::command_t::destination, zmq::command_t::term, and zmq::command_t::type.
{
    command_t cmd;
#if defined ZMQ_MAKE_VALGRIND_HAPPY
    memset (&cmd, 0, sizeof (cmd));
#endif
    cmd.destination = destination_;
    cmd.type = command_t::term;
    cmd.args.term.linger = linger_;
    send_command (cmd);
}
void zmq::object_t::send_term_ack (class own_t * destination_) [protected, inherited]
Definition at line 341 of file object.cpp.
References zmq::command_t::destination, zmq::command_t::term_ack, and zmq::command_t::type.
{
    command_t cmd;
#if defined ZMQ_MAKE_VALGRIND_HAPPY
    memset (&cmd, 0, sizeof (cmd));
#endif
    cmd.destination = destination_;
    cmd.type = command_t::term_ack;
    send_command (cmd);
}
void zmq::object_t::send_term_req (class own_t * destination_, class own_t * object_) [protected, inherited]
Definition at line 316 of file object.cpp.
References zmq::command_t::args, zmq::command_t::destination, zmq::command_t::term_req, and zmq::command_t::type.
{
    command_t cmd;
#if defined ZMQ_MAKE_VALGRIND_HAPPY
    memset (&cmd, 0, sizeof (cmd));
#endif
    cmd.destination = destination_;
    cmd.type = command_t::term_req;
    cmd.args.term_req.object = object_;
    send_command (cmd);
}
void zmq::io_object_t::set_pollin (handle_t handle_) [protected, inherited]
Definition at line 64 of file io_object.cpp.
{
    poller->set_pollin (handle_);
}
void zmq::io_object_t::set_pollout (handle_t handle_) [protected, inherited]
Definition at line 74 of file io_object.cpp.
{
    poller->set_pollout (handle_);
}
void zmq::session_t::terminate () [protected]
Reimplemented from zmq::own_t.
Definition at line 348 of file session.cpp.
References zmq::own_t::terminate().
{
    force_terminate = true;
    own_t::terminate ();
}
void zmq::session_t::terminated (class reader_t * pipe_) [virtual]
Implements zmq::i_reader_events.
Definition at line 180 of file session.cpp.
References zmq_assert.
{
    zmq_assert (in_pipe == pipe_);
    in_pipe = NULL;
    if (state == terminating)
        unregister_term_ack ();
}
void zmq::session_t::terminated (class writer_t * pipe_) [virtual]
Implements zmq::i_writer_events.
Definition at line 188 of file session.cpp.
References zmq_assert.
{
    zmq_assert (out_pipe == pipe_);
    out_pipe = NULL;
    if (state == terminating)
        unregister_term_ack ();
}
void zmq::session_t::timer_event (int id_) [private, virtual]
Reimplemented from zmq::io_object_t.
Definition at line 324 of file session.cpp.
References zmq_assert.
{
    //  Linger period expired. We can proceed with termination even though
    //  there are still pending messages to be sent.
    zmq_assert (id_ == linger_timer_id);
    has_linger_timer = false;
    proceed_with_term ();
}
void zmq::io_object_t::unplug () [inherited]
Reimplemented in zmq::zmq_engine_t.
Definition at line 45 of file io_object.cpp.
References zmq_assert.
Referenced by zmq::zmq_engine_t::unplug().
{
    zmq_assert (poller);
    //  Forget about old poller in preparation to be migrated
    //  to a different I/O thread.
    poller = NULL;
}
void zmq::object_t::unregister_endpoints (class socket_base_t * socket_) [protected, inherited]
Definition at line 141 of file object.cpp.
{
    return ctx->unregister_endpoints (socket_);
}
void zmq::session_t::unregister_session (const blob_t & name_) [protected]
Definition at line 343 of file session.cpp.
{
    socket->unregister_session (name_);
}
void zmq::own_t::unregister_term_ack () [inherited]
Definition at line 178 of file own.cpp.
References zmq_assert.
{
    zmq_assert (term_acks > 0);
    term_acks--;
    //  This may be a last ack we are waiting for before termination...
    check_term_acks ();
}
bool zmq::session_t::write (msg_t * msg_) [virtual]
Implements zmq::i_inout.
Definition at line 95 of file session.cpp.
References errno_assert, and zmq::msg_t::init().
{
    if (out_pipe && out_pipe->write (msg_)) {
        int rc = msg_->init ();
        errno_assert (rc == 0);
        return true;
    }
    return false;
}
Member Data Documentation
bool zmq::session_t::delimiter_processed [private]
Definition at line 130 of file session.hpp.
struct i_engine* zmq::session_t::engine [private]
Definition at line 117 of file session.hpp.
bool zmq::session_t::force_terminate [private]
Definition at line 134 of file session.hpp.
bool zmq::session_t::has_linger_timer [private]
Definition at line 140 of file session.hpp.
class reader_t* zmq::session_t::in_pipe [private]
Definition at line 107 of file session.hpp.
bool zmq::session_t::incomplete_in [private]
Definition at line 111 of file session.hpp.
class io_thread_t* zmq::session_t::io_thread [private]
Definition at line 124 of file session.hpp.
options_t zmq::own_t::options [protected, inherited]
Definition at line 95 of file own.hpp.
Referenced by zmq::pair_t::pair_t(), zmq::pub_t::pub_t(), zmq::pull_t::pull_t(), zmq::push_t::push_t(), zmq::rep_t::rep_t(), zmq::req_t::req_t(), zmq::sub_t::sub_t(), zmq::xpub_t::xpub_t(), zmq::xrep_t::xrep_t(), zmq::xreq_t::xreq_t(), zmq::xsub_t::xsub_t(), and zmq::zmq_init_t::zmq_init_t().
class writer_t* zmq::session_t::out_pipe [private]
Definition at line 114 of file session.hpp.
bool zmq::session_t::pipes_attached [private]
Definition at line 127 of file session.hpp.
class socket_base_t* zmq::session_t::socket [private]
Definition at line 120 of file session.hpp.
enum { ... } zmq::session_t::state [private]
The documentation for this class was generated from the following files:
/home/travlr/src/libzmq/src/session.hpp
/home/travlr/src/libzmq/src/session.cpp