libzmq: zmq::encoder_t Class Reference
zmq::encoder_t Class Reference
#include <encoder.hpp>
Public Member Functions
encoder_t (size_t bufsize_)
~encoder_t ()
void get_data (unsigned char **data_, size_t *size_, int *offset_=NULL)
void set_session (class session_t *session_)
Protected Types
typedef bool(encoder_t::* step_t)()
Protected Member Functions
void next_step (void *write_pos_, size_t to_write_, step_t next_, bool beginning_)
Private Member Functions
encoder_t (const encoder_t &)
bool message_ready ()
const encoder_t & operator= (const encoder_t &)
bool size_ready ()
Private Attributes
msg_t in_progress
class session_t * session
unsigned char tmpbuf [10]
Detailed Description
Definition at line 159 of file encoder.hpp.
Member Typedef Documentation
typedef bool(encoder_t ::* zmq::encoder_base_t< encoder_t >::step_t)() [protected, inherited]
Definition at line 129 of file encoder.hpp.
Constructor & Destructor Documentation
zmq::encoder_t::encoder_t (size_t bufsize_)
Definition at line 25 of file encoder.cpp.
References errno_assert, in_progress, zmq::msg_t::init(), message_ready(), and zmq::encoder_base_t< encoder_t >::next_step().
zmq::encoder_t::~encoder_t ()
Definition at line 36 of file encoder.cpp.
References errno_assert.
zmq::encoder_t::encoder_t (const encoder_t &) [private]
Member Function Documentation
void zmq::encoder_base_t< encoder_t >::get_data (unsigned char ** data_, size_t * size_, int * offset_ = NULL) [inline, inherited]
Definition at line 63 of file encoder.hpp.
References zmq::encoder_base_t< T >::beginning, zmq::encoder_base_t< T >::buf, zmq::encoder_base_t< T >::bufsize, zmq::encoder_base_t< T >::next, zmq::encoder_base_t< T >::to_write, and zmq::encoder_base_t< T >::write_pos.
bool zmq::encoder_t::message_ready () [private]
Definition at line 55 of file encoder.cpp.
References errno_assert, zmq::msg_t::label, zmq::msg_t::more, and size_ready().
Referenced by encoder_t(), and size_ready().
void zmq::encoder_base_t< encoder_t >::next_step (void * write_pos_, size_t to_write_, step_t next_, bool beginning_) [inline, protected, inherited]
Definition at line 134 of file encoder.hpp.
References zmq::encoder_base_t< T >::beginning, zmq::encoder_base_t< T >::next, zmq::encoder_base_t< T >::to_write, and zmq::encoder_base_t< T >::write_pos.
Referenced by encoder_t().
const encoder_t& zmq::encoder_t::operator= (const encoder_t &) [private]
void zmq::encoder_t::set_session (class session_t * session_)
Definition at line 42 of file encoder.cpp.
bool zmq::encoder_t::size_ready () [private]
Definition at line 47 of file encoder.cpp.
References message_ready().
Referenced by message_ready().
Member Data Documentation
msg_t zmq::encoder_t::in_progress [private]
Definition at line 174 of file encoder.hpp.
Referenced by encoder_t().
class session_t* zmq::encoder_t::session [private]
Definition at line 173 of file encoder.hpp.
unsigned char zmq::encoder_t::tmpbuf[10] [private]
Definition at line 175 of file encoder.hpp.
The documentation for this class was generated from the following files:
src/encoder.hpp
src/encoder.cpp