libzmq: zmq::ipc_address_t Class Reference
zmq::ipc_address_t Class Reference
#include <ipc_address.hpp>
Public Member Functions
ipc_address_t ()
~ipc_address_t ()
sockaddr * addr ()
socklen_t addrlen ()
int resolve (const char *path_)
Private Member Functions
ipc_address_t (const ipc_address_t &)
const ipc_address_t & operator= (const ipc_address_t &)
Private Attributes
struct sockaddr_un address
Detailed Description
Definition at line 34 of file ipc_address.hpp.
Constructor & Destructor Documentation
zmq::ipc_address_t::ipc_address_t ()
Definition at line 29 of file ipc_address.cpp.
References address.
zmq::ipc_address_t::~ipc_address_t ()
Definition at line 34 of file ipc_address.cpp.
zmq::ipc_address_t::ipc_address_t (const ipc_address_t &) [private]
Member Function Documentation
sockaddr * zmq::ipc_address_t::addr ()
Definition at line 50 of file ipc_address.cpp.
Referenced by zmq::ipc_listener_t::set_address().
socklen_t zmq::ipc_address_t::addrlen ()
Definition at line 55 of file ipc_address.cpp.
Referenced by zmq::ipc_listener_t::set_address().
const ipc_address_t& zmq::ipc_address_t::operator= (const ipc_address_t &) [private]
int zmq::ipc_address_t::resolve (const char * path_)
Definition at line 38 of file ipc_address.cpp.
Referenced by zmq::ipc_listener_t::set_address().
Member Data Documentation
struct sockaddr_un zmq::ipc_address_t::address [private]
Definition at line 49 of file ipc_address.hpp.
Referenced by ipc_address_t().
The documentation for this class was generated from the following files:
src/ipc_address.hpp
src/ipc_address.cpp