libzmq: zmq::fq_t Class Reference
zmq::fq_t Class Reference
#include <fq.hpp>
Public Member Functions
fq_t (class own_t *sink_)
~fq_t ()
void activated (reader_t *pipe_)
void attach (reader_t *pipe_)
void delimited (reader_t *pipe_)
bool has_in ()
int recv (msg_t *msg_, int flags_)
void terminate ()
void terminated (reader_t *pipe_)
Private Types
typedef array_t< reader_t > pipes_t
Private Member Functions
fq_t (const fq_t &)
const fq_t & operator= (const fq_t &)
Private Attributes
pipes_t::size_type active
pipes_t::size_type current
bool more
pipes_t pipes
class own_t * sink
bool terminating
Detailed Description
Definition at line 34 of file fq.hpp.
Member Typedef Documentation
typedef array_t<reader_t> zmq::fq_t::pipes_t [private]
Definition at line 55 of file fq.hpp.
Constructor & Destructor Documentation
zmq::fq_t::fq_t (class own_t * sink_)
Definition at line 27 of file fq.cpp.
zmq::fq_t::~fq_t ()
Definition at line 36 of file fq.cpp.
References zmq_assert.
zmq::fq_t::fq_t (const fq_t &) [private]
Member Function Documentation
void zmq::fq_t::activated (reader_t * pipe_) [virtual]
Implements zmq::i_reader_events.
Definition at line 89 of file fq.cpp.
void zmq::fq_t::attach (reader_t * pipe_)
Definition at line 41 of file fq.cpp.
References zmq::reader_t::set_event_sink(), and zmq::reader_t::terminate().
void zmq::fq_t::delimited (reader_t * pipe_) [virtual]
Implements zmq::i_reader_events.
Definition at line 75 of file fq.cpp.
bool zmq::fq_t::has_in ()
Definition at line 142 of file fq.cpp.
const fq_t& zmq::fq_t::operator= (const fq_t &) [private]
int zmq::fq_t::recv (msg_t * msg_, int flags_)
Definition at line 96 of file fq.cpp.
References zmq::msg_t::close(), errno_assert, zmq::msg_t::flags, zmq::msg_t::init(), zmq::msg_t::more, and zmq_assert.
void zmq::fq_t::terminate ()
Definition at line 79 of file fq.cpp.
References zmq_assert.
void zmq::fq_t::terminated (reader_t * pipe_) [virtual]
Implements zmq::i_reader_events.
Definition at line 56 of file fq.cpp.
References zmq_assert.
Member Data Documentation
pipes_t::size_type zmq::fq_t::active [private]
Definition at line 60 of file fq.hpp.
pipes_t::size_type zmq::fq_t::current [private]
Definition at line 63 of file fq.hpp.
bool zmq::fq_t::more [private]
Definition at line 67 of file fq.hpp.
pipes_t zmq::fq_t::pipes [private]
Definition at line 56 of file fq.hpp.
class own_t* zmq::fq_t::sink [private]
Definition at line 70 of file fq.hpp.
bool zmq::fq_t::terminating [private]
Definition at line 73 of file fq.hpp.
The documentation for this class was generated from the following files:
src/fq.hpp
src/fq.cpp