libzmq: zmq::mailbox_t Class Reference
zmq::mailbox_t Class Reference
#include <mailbox.hpp>
Public Member Functions
mailbox_t ()
~mailbox_t ()
fd_t get_fd ()
int recv (command_t *cmd_, int timeout_)
void send (const command_t &cmd_)
Private Member Functions
mailbox_t (const mailbox_t &)
const mailbox_t & operator= (const mailbox_t &)
int recv_timeout (command_t *cmd_, int timeout_)
Static Private Member Functions
static int make_socketpair (fd_t *r_, fd_t *w_)
Private Attributes
bool blocking
fd_t r
fd_t w
Detailed Description
Definition at line 35 of file mailbox.hpp.
Constructor & Destructor Documentation
zmq::mailbox_t::mailbox_t ()
Definition at line 146 of file mailbox.cpp.
References errno_assert, make_socketpair(), and zmq_assert.
zmq::mailbox_t::~mailbox_t ()
Definition at line 167 of file mailbox.cpp.
zmq::mailbox_t::mailbox_t (const mailbox_t &) [private]
Member Function Documentation
zmq::fd_t zmq::mailbox_t::get_fd ()
Definition at line 75 of file mailbox.cpp.
References r.
Referenced by zmq::io_thread_t::io_thread_t(), and zmq::reaper_t::reaper_t().
int zmq::mailbox_t::make_socketpair (fd_t * r_, fd_t * w_) [static, private]
Definition at line 257 of file mailbox.cpp.
References errno_assert.
Referenced by mailbox_t().
const mailbox_t& zmq::mailbox_t::operator= (const mailbox_t &) [private]
int zmq::mailbox_t::recv (command_t * cmd_, int timeout_)
Definition at line 213 of file mailbox.cpp.
References errno_assert, and zmq_assert.
int zmq::mailbox_t::recv_timeout (command_t * cmd_, int timeout_) [private]
Definition at line 388 of file mailbox.cpp.
References errno_assert, unlikely, and zmq_assert.
void zmq::mailbox_t::send (const command_t & cmd_)
Definition at line 173 of file mailbox.cpp.
References errno_assert, and zmq_assert.
Member Data Documentation
bool zmq::mailbox_t::blocking [private]
Definition at line 62 of file mailbox.hpp.
fd_t zmq::mailbox_t::r [private]
Definition at line 58 of file mailbox.hpp.
Referenced by get_fd().
fd_t zmq::mailbox_t::w [private]
Definition at line 57 of file mailbox.hpp.
The documentation for this class was generated from the following files:
src/mailbox.hpp
src/mailbox.cpp