libzmq: zmq::pair_t Class Reference
zmq::pair_t Class Reference
#include <pair.hpp>
Public Member Functions
pair_t (class ctx_t *parent_, uint32_t tid_)
~pair_t ()
void activated (class reader_t *pipe_)
void activated (class writer_t *pipe_)
int bind (const char *addr_)
void check_destroy ()
bool check_tag ()
int close ()
int connect (const char *addr_)
void delimited (class reader_t *pipe_)
class session_t * find_session (const blob_t &name_)
int get_array_index ()
ctx_t * get_ctx ()
mailbox_t * get_mailbox ()
uint32_t get_tid ()
int getsockopt (int option_, void *optval_, size_t *optvallen_)
bool has_in ()
bool has_out ()
void in_event ()
void inc_seqnum ()
void out_event ()
void process_command (struct command_t &cmd_)
int recv (class msg_t *msg_, int flags_)
bool register_session (const blob_t &name_, class session_t *session_)
void register_term_acks (int count_)
int send (class msg_t *msg_, int flags_)
void set_array_index (int index_)
int setsockopt (int option_, const void *optval_, size_t optvallen_)
void start_reaping (poller_t *poller_)
void stop ()
void terminated (class writer_t *pipe_)
void terminated (class reader_t *pipe_)
void timer_event (int id_)
void unregister_session (const blob_t &name_)
void unregister_term_ack ()
void xattach_pipes (class reader_t *inpipe_, class writer_t *outpipe_, const blob_t &peer_identity_)
bool xhas_in ()
bool xhas_out ()
int xrecv (class msg_t *msg_, int flags_)
int xsend (class msg_t *msg_, int flags_)
Static Public Member Functions
static socket_base_t * create (int type_, class ctx_t *parent_, uint32_t tid_)
Protected Member Functions
class io_thread_t * choose_io_thread (uint64_t affinity_)
void destroy_socket (class socket_base_t *socket_)
struct endpoint_t find_endpoint (const char *addr_)
void launch_child (own_t *object_)
void launch_sibling (own_t *object_)
void log (const char *format_,...)
virtual void process_activate_reader ()
virtual void process_activate_writer (uint64_t msgs_read_)
virtual void process_attach (struct i_engine *engine_, const blob_t &peer_identity_)
void process_destroy ()
virtual void process_pipe_term ()
virtual void process_pipe_term_ack ()
virtual void process_plug ()
virtual void process_reap (class socket_base_t *socket_)
virtual void process_reaped ()
int register_endpoint (const char *addr_, struct endpoint_t &endpoint_)
void send_activate_reader (class reader_t *destination_)
void send_activate_writer (class writer_t *destination_, uint64_t msgs_read_)
void send_attach (class session_t *destination_, struct i_engine *engine_, const blob_t &peer_identity_, bool inc_seqnum_=true)
void send_bind (class own_t *destination_, class reader_t *in_pipe_, class writer_t *out_pipe_, const blob_t &peer_identity_, bool inc_seqnum_=true)
void send_done ()
void send_own (class own_t *destination_, class own_t *object_)
void send_pipe_term (class writer_t *destination_)
void send_pipe_term_ack (class reader_t *destination_)
void send_plug (class own_t *destination_, bool inc_seqnum_=true)
void send_reap (class socket_base_t *socket_)
void send_reaped ()
void send_stop ()
void send_term (class own_t *destination_, int linger_)
void send_term_ack (class own_t *destination_)
void send_term_req (class own_t *destination_, class own_t *object_)
void terminate ()
void unregister_endpoints (class socket_base_t *socket_)
virtual int xsetsockopt (int option_, const void *optval_, size_t optvallen_)
Protected Attributes
options_t options
Private Member Functions
pair_t (const pair_t &)
const pair_t & operator= (const pair_t &)
void process_term (int linger_)
Private Attributes
class reader_t * inpipe
bool inpipe_alive
class writer_t * outpipe
bool outpipe_alive
bool terminating
Detailed Description
Definition at line 30 of file pair.hpp.
Constructor & Destructor Documentation
zmq::pair_t::pair_t (class ctx_t * parent_, uint32_t tid_)
Definition at line 26 of file pair.cpp.
References zmq::own_t::options, zmq::options_t::requires_in, zmq::options_t::requires_out, zmq::options_t::type, and ZMQ_PAIR.
zmq::pair_t::~pair_t ()
Definition at line 39 of file pair.cpp.
References zmq_assert.
zmq::pair_t::pair_t (const pair_t &) [private]
Member Function Documentation
void zmq::pair_t::activated (class reader_t * pipe_) [virtual]
Implements zmq::i_reader_events.
Definition at line 106 of file pair.cpp.
References zmq_assert.
void zmq::pair_t::activated (class writer_t * pipe_) [virtual]
Implements zmq::i_writer_events.
Definition at line 112 of file pair.cpp.
References zmq_assert.
int zmq::socket_base_t::bind (const char * addr_) [inherited]
Definition at line 295 of file socket_base.cpp.
References alloc_assert, EMTHREAD, ETERM, zmq::zmq_listener_t::set_address(), unlikely, and zmq_assert.
Referenced by zmq::ctx_t::ctx_t().
void zmq::socket_base_t::check_destroy () [inherited]
Definition at line 794 of file socket_base.cpp.
References zmq::own_t::process_destroy().
Referenced by zmq::reaper_t::process_reap().
bool zmq::socket_base_t::check_tag () [inherited]
Definition at line 63 of file socket_base.cpp.
References zmq::socket_base_t::tag.
zmq::io_thread_t * zmq::object_t::choose_io_thread (uint64_t affinity_) [protected, inherited]
Definition at line 164 of file object.cpp.
References zmq::object_t::choose_io_thread().
Referenced by zmq::object_t::choose_io_thread().
int zmq::socket_base_t::close () [inherited]
Definition at line 593 of file socket_base.cpp.
int zmq::socket_base_t::connect (const char * addr_) [inherited]
Definition at line 352 of file socket_base.cpp.
References alloc_assert, zmq::session_t::attach_pipes(), EMTHREAD, ETERM, zmq::options_t::identity, zmq::endpoint_t::options, zmq::options_t::rcvhwm, zmq::options_t::sndhwm, zmq::endpoint_t::socket, and unlikely.
zmq::socket_base_t * zmq::socket_base_t::create (int type_, class ctx_t * parent_, uint32_t tid_) [static, inherited]
Definition at line 68 of file socket_base.cpp.
References alloc_assert, ZMQ_PAIR, ZMQ_PUB, ZMQ_PULL, ZMQ_PUSH, ZMQ_REP, ZMQ_REQ, ZMQ_SUB, ZMQ_XPUB, ZMQ_XREP, ZMQ_XREQ, and ZMQ_XSUB.
Referenced by zmq::ctx_t::create_socket().
void zmq::pair_t::delimited (class reader_t * pipe_) [virtual]
Implements zmq::i_reader_events.
Definition at line 85 of file pair.cpp.
void zmq::object_t::destroy_socket (class socket_base_t * socket_) [protected, inherited]
Definition at line 151 of file object.cpp.
zmq::endpoint_t zmq::object_t::find_endpoint (const char * addr_) [read, protected, inherited]
Definition at line 146 of file object.cpp.
zmq::session_t * zmq::socket_base_t::find_session (const blob_t & name_) [inherited]
Definition at line 632 of file socket_base.cpp.
References zmq::own_t::inc_seqnum().
int zmq::array_item_t::get_array_index () [inline, inherited]
Definition at line 53 of file array.hpp.
References zmq::array_item_t::array_index.
zmq::ctx_t * zmq::object_t::get_ctx () [inherited]
Definition at line 53 of file object.cpp.
zmq::mailbox_t * zmq::socket_base_t::get_mailbox () [inherited]
Definition at line 139 of file socket_base.cpp.
Referenced by zmq::ctx_t::create_socket().
uint32_t zmq::object_t::get_tid () [inherited]
Definition at line 48 of file object.cpp.
Referenced by zmq::ctx_t::destroy_socket(), and zmq::object_t::send_command().
int zmq::socket_base_t::getsockopt (int option_, void * optval_, size_t * optvallen_) [inherited]
Definition at line 246 of file socket_base.cpp.
References errno_assert, ETERM, unlikely, ZMQ_EVENTS, ZMQ_FD, ZMQ_POLLIN, ZMQ_POLLOUT, and ZMQ_RCVMORE.
bool zmq::socket_base_t::has_in () [inherited]
Definition at line 603 of file socket_base.cpp.
bool zmq::socket_base_t::has_out () [inherited]
Definition at line 608 of file socket_base.cpp.
void zmq::socket_base_t::in_event () [virtual, inherited]
Implements zmq::i_poll_events.
Definition at line 776 of file socket_base.cpp.
void zmq::own_t::inc_seqnum () [inherited]
Definition at line 56 of file own.cpp.
Referenced by zmq::ctx_t::find_endpoint(), zmq::socket_base_t::find_session(), zmq::object_t::send_attach(), zmq::object_t::send_bind(), zmq::object_t::send_own(), and zmq::object_t::send_plug().
void zmq::own_t::launch_child (own_t * object_) [protected, inherited]
Definition at line 71 of file own.cpp.
References zmq::own_t::set_owner().
void zmq::own_t::launch_sibling (own_t * object_) [protected, inherited]
Definition at line 83 of file own.cpp.
References zmq::own_t::set_owner().
void zmq::object_t::log (const char * format_, ...) [protected, inherited]
Definition at line 156 of file object.cpp.
const pair_t& zmq::pair_t::operator= (const pair_t &) [private]
void zmq::socket_base_t::out_event () [virtual, inherited]
Implements zmq::i_poll_events.
Definition at line 784 of file socket_base.cpp.
References zmq_assert.
void zmq::object_t::process_activate_reader () [protected, virtual, inherited]
Reimplemented in zmq::reader_t.
Definition at line 413 of file object.cpp.
References zmq_assert.
void zmq::object_t::process_activate_writer (uint64_t msgs_read_) [protected, virtual, inherited]
Reimplemented in zmq::writer_t.
Definition at line 418 of file object.cpp.
References zmq_assert.
void zmq::object_t::process_attach (struct i_engine * engine_, const blob_t & peer_identity_) [protected, virtual, inherited]
Reimplemented in zmq::session_t.
Definition at line 401 of file object.cpp.
References zmq_assert.
void zmq::object_t::process_command (struct command_t & cmd_) [inherited]
Definition at line 58 of file object.cpp.
References zmq::command_t::activate_reader, zmq::command_t::activate_writer, zmq::command_t::args, zmq::command_t::attach, zmq::command_t::bind, zmq::command_t::own, zmq::command_t::pipe_term, zmq::command_t::pipe_term_ack, zmq::command_t::plug, zmq::command_t::reap, zmq::command_t::reaped, zmq::command_t::stop, zmq::command_t::term, zmq::command_t::term_ack, zmq::command_t::term_req, zmq::command_t::type, and zmq_assert.
Referenced by zmq::reaper_t::in_event(), zmq::io_thread_t::in_event(), and zmq::socket_base_t::process_commands().
void zmq::socket_base_t::process_destroy () [protected, virtual, inherited]
Reimplemented from zmq::own_t.
Definition at line 742 of file socket_base.cpp.
void zmq::object_t::process_pipe_term () [protected, virtual, inherited]
Reimplemented in zmq::writer_t.
Definition at line 423 of file object.cpp.
References zmq_assert.
void zmq::object_t::process_pipe_term_ack () [protected, virtual, inherited]
Reimplemented in zmq::reader_t.
Definition at line 428 of file object.cpp.
References zmq_assert.
void zmq::object_t::process_plug () [protected, virtual, inherited]
Reimplemented in zmq::connect_session_t, zmq::session_t, zmq::zmq_connecter_t, zmq::zmq_init_t, and zmq::zmq_listener_t.
Definition at line 391 of file object.cpp.
References zmq_assert.
void zmq::object_t::process_reap (class socket_base_t * socket_) [protected, virtual, inherited]
Reimplemented in zmq::reaper_t.
Definition at line 448 of file object.cpp.
References zmq_assert.
void zmq::object_t::process_reaped () [protected, virtual, inherited]
Reimplemented in zmq::reaper_t.
Definition at line 453 of file object.cpp.
References zmq_assert.
void zmq::pair_t::process_term (int linger_) [private, virtual]
Reimplemented from zmq::socket_base_t.
Definition at line 89 of file pair.cpp.
References zmq::socket_base_t::process_term().
int zmq::socket_base_t::recv (class msg_t * msg_, int flags_) [inherited]
Definition at line 511 of file socket_base.cpp.
References zmq::msg_t::check(), ETERM, zmq::msg_t::flags, zmq::msg_t::more, zmq::msg_t::reset_flags(), unlikely, and ZMQ_DONTWAIT.
int zmq::object_t::register_endpoint (const char * addr_, struct endpoint_t & endpoint_) [protected, inherited]
Definition at line 136 of file object.cpp.
bool zmq::socket_base_t::register_session (const blob_t & name_, class session_t * session_) [inherited]
Definition at line 613 of file socket_base.cpp.
Referenced by zmq::named_session_t::named_session_t().
void zmq::own_t::register_term_acks (int count_) [inherited]
Definition at line 173 of file own.cpp.
int zmq::socket_base_t::send (class msg_t * msg_, int flags_) [inherited]
Definition at line 466 of file socket_base.cpp.
References zmq::msg_t::check(), ETERM, zmq::msg_t::more, zmq::msg_t::set_flags(), unlikely, ZMQ_DONTWAIT, and ZMQ_SNDMORE.
void zmq::object_t::send_activate_reader (class reader_t * destination_) [protected, inherited]
Definition at line 270 of file object.cpp.
References zmq::command_t::activate_reader, zmq::command_t::destination, and zmq::command_t::type.
void zmq::object_t::send_activate_writer (class writer_t * destination_, uint64_t msgs_read_) [protected, inherited]
Definition at line 281 of file object.cpp.
References zmq::command_t::activate_writer, zmq::command_t::args, zmq::command_t::destination, and zmq::command_t::type.
void zmq::object_t::send_attach (class session_t * destination_, struct i_engine * engine_, const blob_t & peer_identity_, bool inc_seqnum_ = true) [protected, inherited]
Definition at line 209 of file object.cpp.
References alloc_assert, zmq::command_t::args, zmq::command_t::attach, zmq::command_t::destination, zmq::own_t::inc_seqnum(), zmq::command_t::type, and zmq_assert.
void zmq::object_t::send_bind (class own_t * destination_, class reader_t * in_pipe_, class writer_t * out_pipe_, const blob_t & peer_identity_, bool inc_seqnum_ = true) [protected, inherited]
Definition at line 239 of file object.cpp.
References alloc_assert, zmq::command_t::args, zmq::command_t::bind, zmq::command_t::destination, zmq::own_t::inc_seqnum(), zmq::command_t::type, and zmq_assert.
void zmq::object_t::send_done () [protected, inherited]
Definition at line 375 of file object.cpp.
References zmq::command_t::destination, zmq::command_t::done, zmq::ctx_t::term_tid, and zmq::command_t::type.
void zmq::object_t::send_own (class own_t * destination_, class own_t * object_) [protected, inherited]
Definition at line 196 of file object.cpp.
References zmq::command_t::args, zmq::command_t::destination, zmq::own_t::inc_seqnum(), zmq::command_t::own, and zmq::command_t::type.
void zmq::object_t::send_pipe_term (class writer_t * destination_) [protected, inherited]
Definition at line 294 of file object.cpp.
References zmq::command_t::destination, zmq::command_t::pipe_term, and zmq::command_t::type.
void zmq::object_t::send_pipe_term_ack (class reader_t * destination_) [protected, inherited]
Definition at line 305 of file object.cpp.
References zmq::command_t::destination, zmq::command_t::pipe_term_ack, and zmq::command_t::type.
void zmq::object_t::send_plug (class own_t * destination_, bool inc_seqnum_ = true) [protected, inherited]
Definition at line 182 of file object.cpp.
References zmq::command_t::destination, zmq::own_t::inc_seqnum(), zmq::command_t::plug, and zmq::command_t::type.
void zmq::object_t::send_reap (class socket_base_t * socket_) [protected, inherited]
Definition at line 352 of file object.cpp.
References zmq::command_t::args, zmq::command_t::destination, zmq::command_t::reap, and zmq::command_t::type.
void zmq::object_t::send_reaped () [protected, inherited]
Definition at line 364 of file object.cpp.
References zmq::command_t::destination, zmq::command_t::reaped, and zmq::command_t::type.
void zmq::object_t::send_stop () [protected, inherited]
Definition at line 169 of file object.cpp.
References zmq::command_t::destination, zmq::command_t::stop, and zmq::command_t::type.
void zmq::object_t::send_term (class own_t * destination_, int linger_) [protected, inherited]
Definition at line 329 of file object.cpp.
References zmq::command_t::args, zmq::command_t::destination, zmq::command_t::term, and zmq::command_t::type.
void zmq::object_t::send_term_ack (class own_t * destination_) [protected, inherited]
Definition at line 341 of file object.cpp.
References zmq::command_t::destination, zmq::command_t::term_ack, and zmq::command_t::type.
void zmq::object_t::send_term_req (class own_t * destination_, class own_t * object_) [protected, inherited]
Definition at line 316 of file object.cpp.
References zmq::command_t::args, zmq::command_t::destination, zmq::command_t::term_req, and zmq::command_t::type.
void zmq::array_item_t::set_array_index (int index_) [inline, inherited]
Definition at line 48 of file array.hpp.
References zmq::array_item_t::array_index.
int zmq::socket_base_t::setsockopt (int option_, const void * optval_, size_t optvallen_) [inherited]
Definition at line 228 of file socket_base.cpp.
References ETERM, and unlikely.
void zmq::socket_base_t::start_reaping (poller_t * poller_) [inherited]
Definition at line 651 of file socket_base.cpp.
Referenced by zmq::reaper_t::process_reap().
void zmq::socket_base_t::stop () [inherited]
Definition at line 144 of file socket_base.cpp.
void zmq::own_t::terminate () [protected, inherited]
Reimplemented in zmq::session_t.
Definition at line 138 of file own.cpp.
Referenced by zmq::reaper_t::process_reap(), and zmq::session_t::terminate().
void zmq::pair_t::terminated (class writer_t * pipe_) [virtual]
Implements zmq::i_writer_events.
Definition at line 75 of file pair.cpp.
References zmq_assert.
void zmq::pair_t::terminated (class reader_t * pipe_) [virtual]
Implements zmq::i_reader_events.
Definition at line 65 of file pair.cpp.
References zmq_assert.
void zmq::socket_base_t::timer_event (int id_) [virtual, inherited]
Implements zmq::i_poll_events.
Definition at line 789 of file socket_base.cpp.
References zmq_assert.
void zmq::object_t::unregister_endpoints (class socket_base_t * socket_) [protected, inherited]
Definition at line 141 of file object.cpp.
void zmq::socket_base_t::unregister_session (const blob_t & name_) [inherited]
Definition at line 623 of file socket_base.cpp.
References zmq_assert.
void zmq::own_t::unregister_term_ack () [inherited]
Definition at line 178 of file own.cpp.
References zmq_assert.
void zmq::pair_t::xattach_pipes (class reader_t * inpipe_, class writer_t * outpipe_, const blob_t & peer_identity_) [virtual]
Implements zmq::socket_base_t.
Definition at line 45 of file pair.cpp.
References zmq::writer_t::set_event_sink(), zmq::reader_t::set_event_sink(), zmq::writer_t::terminate(), zmq::reader_t::terminate(), and zmq_assert.
bool zmq::pair_t::xhas_in () [virtual]
Reimplemented from zmq::socket_base_t.
Definition at line 161 of file pair.cpp.
bool zmq::pair_t::xhas_out () [virtual]
Reimplemented from zmq::socket_base_t.
Definition at line 170 of file pair.cpp.
References zmq::msg_t::close(), errno_assert, and zmq::msg_t::init().
int zmq::pair_t::xrecv (class msg_t * msg_, int flags_) [virtual]
Reimplemented from zmq::socket_base_t.
Definition at line 141 of file pair.cpp.
References zmq::msg_t::close(), errno_assert, and zmq::msg_t::init().
int zmq::pair_t::xsend (class msg_t * msg_, int flags_) [virtual]
Reimplemented from zmq::socket_base_t.
Definition at line 118 of file pair.cpp.
References errno_assert, zmq::msg_t::init(), and ZMQ_SNDMORE.
int zmq::socket_base_t::xsetsockopt (int option_, const void * optval_, size_t optvallen_) [protected, virtual, inherited]
Reimplemented in zmq::sub_t.
Definition at line 747 of file socket_base.cpp.
Member Data Documentation
class reader_t* zmq::pair_t::inpipe [private]
Definition at line 62 of file pair.hpp.
bool zmq::pair_t::inpipe_alive [private]
Definition at line 65 of file pair.hpp.
options_t zmq::own_t::options [protected, inherited]
Definition at line 95 of file own.hpp.
Referenced by pair_t(), zmq::pub_t::pub_t(), zmq::pull_t::pull_t(), zmq::push_t::push_t(), zmq::rep_t::rep_t(), zmq::req_t::req_t(), zmq::sub_t::sub_t(), zmq::xpub_t::xpub_t(), zmq::xrep_t::xrep_t(), zmq::xreq_t::xreq_t(), zmq::xsub_t::xsub_t(), and zmq::zmq_init_t::zmq_init_t().
class writer_t* zmq::pair_t::outpipe [private]
Definition at line 63 of file pair.hpp.
bool zmq::pair_t::outpipe_alive [private]
Definition at line 66 of file pair.hpp.
bool zmq::pair_t::terminating [private]
Reimplemented from zmq::own_t.
Definition at line 68 of file pair.hpp.
The documentation for this class was generated from the following files:
src/pair.hpp
src/pair.cpp