libzmq: zmq::dist_t Class Reference
zmq::dist_t Class Reference
#include <dist.hpp>
Public Member Functions
dist_t (class own_t *sink_)
~dist_t ()
void activated (writer_t *pipe_)
void attach (writer_t *pipe_)
bool has_out ()
int send (class msg_t *msg_, int flags_)
void terminate ()
void terminated (writer_t *pipe_)
Private Types
typedef array_t< class writer_t > pipes_t
Private Member Functions
dist_t (const dist_t &)
void distribute (class msg_t *msg_, int flags_)
const dist_t & operator= (const dist_t &)
bool write (class writer_t *pipe_, class msg_t *msg_)
Private Attributes
pipes_t::size_type active
pipes_t::size_type eligible
bool more
pipes_t pipes
class own_t * sink
bool terminating
Detailed Description
Definition at line 34 of file dist.hpp.
Member Typedef Documentation
typedef array_t<class writer_t> zmq::dist_t::pipes_t [private]
Definition at line 60 of file dist.hpp.
Constructor & Destructor Documentation
zmq::dist_t::dist_t (class own_t * sink_)
Definition at line 28 of file dist.cpp.
                               :
    active (0),
    eligible (0),
    more (false),
    sink (sink_),
    terminating (false)
{
}
zmq::dist_t::~dist_t ()
Definition at line 37 of file dist.cpp.
References zmq_assert.
{
    zmq_assert (pipes.empty ());
}
zmq::dist_t::dist_t (const dist_t &) [private]
Member Function Documentation
void zmq::dist_t::activated (writer_t * pipe_) [virtual]
Implements zmq::i_writer_events.
Definition at line 91 of file dist.cpp.
{
    //  Move the pipe from passive to eligible state.
    pipes.swap (pipes.index (pipe_), eligible);
    eligible++;
    //  If there's no message being sent at the moment, move it to
    //  the active state.
    if (!more) {
        pipes.swap (eligible - 1, active);
        active++;
    }
}
void zmq::dist_t::attach (writer_t * pipe_)
Definition at line 42 of file dist.cpp.
References zmq::writer_t::set_event_sink(), zmq::writer_t::terminate(), and unlikely.
{
    pipe_->set_event_sink (this);
    //  If we are in the middle of sending a message, we'll add new pipe
    //  into the list of eligible pipes. Otherwise we add it to the list
    //  of active pipes.
    if (more) {
        pipes.push_back (pipe_);
        pipes.swap (eligible, pipes.size () - 1);
        eligible++;
    }
    else {
        pipes.push_back (pipe_);
        pipes.swap (active, pipes.size () - 1);
        active++;
        eligible++;
    }
    if (unlikely (terminating)) {
        sink->register_term_acks (1);
        pipe_->terminate ();
    }
}
void zmq::dist_t::distribute (class msg_t * msg_, int flags_) [private]
Definition at line 122 of file dist.cpp.
References zmq::msg_t::add_refs(), zmq::msg_t::close(), errno_assert, zmq::msg_t::init(), zmq::msg_t::rm_refs(), and zmq_assert.
{
    //  If there are no active pipes available, simply drop the message.
    if (active == 0) {
        int rc = msg_->close ();
        errno_assert (rc == 0);
        rc = msg_->init ();
        zmq_assert (rc == 0);
        return;
    }
    //  Add active-1 references to the message. We already hold one reference,
    //  that's why -1.
    msg_->add_refs (active - 1);
    //  Push copy of the message to each active pipe.
    for (pipes_t::size_type i = 0; i < active;) {
        if (!write (pipes [i], msg_))
            msg_->rm_refs (1);
        else
            i++;
    }
    //  Detach the original message from the data buffer. Note that we don't
    //  close the message. That's because we've already used all the references.
    int rc = msg_->init ();
    errno_assert (rc == 0);
}
bool zmq::dist_t::has_out ()
Definition at line 151 of file dist.cpp.
{
    return true;
}
const dist_t& zmq::dist_t::operator= (const dist_t &) [private]
int zmq::dist_t::send (class msg_t * msg_, int flags_)
Definition at line 105 of file dist.cpp.
References zmq::msg_t::flags, and zmq::msg_t::more.
{
    //  Is this end of a multipart message?
    bool msg_more = msg_->flags () & msg_t::more;
    //  Push the message to active pipes.
    distribute (msg_, flags_);
    //  If mutlipart message is fully sent, activate all the eligible pipes.
    if (!msg_more)
        active = eligible;
    more = msg_more;
    return 0;
}
void zmq::dist_t::terminate ()
Definition at line 67 of file dist.cpp.
References zmq_assert.
{
    zmq_assert (!terminating);
    terminating = true;
    sink->register_term_acks ((int) pipes.size ());
    for (pipes_t::size_type i = 0; i != pipes.size (); i++)
        pipes [i]->terminate ();
}
void zmq::dist_t::terminated (writer_t * pipe_) [virtual]
Implements zmq::i_writer_events.
Definition at line 77 of file dist.cpp.
References unlikely.
{
    //  Remove the pipe from the list; adjust number of active and/or
    //  eligible pipes accordingly.
    if (pipes.index (pipe_) < active)
        active--;
    if (pipes.index (pipe_) < eligible)
        eligible--;
    pipes.erase (pipe_);
    if (unlikely (terminating))
        sink->unregister_term_ack ();
}
bool zmq::dist_t::write (class writer_t * pipe_, class msg_t * msg_) [private]
Definition at line 156 of file dist.cpp.
References zmq::msg_t::flags, zmq::writer_t::flush(), zmq::msg_t::more, and zmq::writer_t::write().
{
    if (!pipe_->write (msg_)) {
        pipes.swap (pipes.index (pipe_), active - 1);
        active--;
        pipes.swap (active, eligible - 1);
        eligible--;
        return false;
    }
    if (!(msg_->flags () & msg_t::more))
        pipe_->flush ();
    return true;
}
Member Data Documentation
pipes_t::size_type zmq::dist_t::active [private]
Definition at line 66 of file dist.hpp.
pipes_t::size_type zmq::dist_t::eligible [private]
Definition at line 73 of file dist.hpp.
bool zmq::dist_t::more [private]
Definition at line 76 of file dist.hpp.
pipes_t zmq::dist_t::pipes [private]
Definition at line 61 of file dist.hpp.
class own_t* zmq::dist_t::sink [private]
Definition at line 79 of file dist.hpp.
bool zmq::dist_t::terminating [private]
Definition at line 82 of file dist.hpp.
The documentation for this class was generated from the following files:
/home/travlr/src/libzmq/src/dist.hpp
/home/travlr/src/libzmq/src/dist.cpp