libzmq: zmq::stream_engine_t Class Reference
zmq::stream_engine_t Class Reference
#include <stream_engine.hpp>
Public Member Functions
stream_engine_t (fd_t fd_, const options_t &options_)
~stream_engine_t ()
void activate_in ()
void activate_out ()
void in_event ()
void out_event ()
void plug (class io_thread_t *io_thread_)
void plug (class io_thread_t *io_thread_, class session_base_t *session_)
void terminate ()
void unplug ()
Protected Types
typedef poller_t::handle_t handle_t
Protected Member Functions
handle_t add_fd (fd_t fd_)
void add_timer (int timout_, int id_)
void cancel_timer (int id_)
void reset_pollin (handle_t handle_)
void reset_pollout (handle_t handle_)
void rm_fd (handle_t handle_)
void set_pollin (handle_t handle_)
void set_pollout (handle_t handle_)
void timer_event (int id_)
Private Member Functions
stream_engine_t (const stream_engine_t &)
void error ()
const stream_engine_t & operator= (const stream_engine_t &)
int read (void *data_, size_t size_)
int write (const void *data_, size_t size_)
Private Attributes
decoder_t decoder
encoder_t encoder
handle_t handle
unsigned char * inpos
size_t insize
class session_base_t * leftover_session
options_t options
unsigned char * outpos
size_t outsize
bool plugged
fd_t s
class session_base_t * session
Detailed Description
Definition at line 39 of file stream_engine.hpp.
Member Typedef Documentation
typedef poller_t::handle_t zmq::io_object_t::handle_t [protected, inherited]
Definition at line 51 of file io_object.hpp.
Constructor & Destructor Documentation
zmq::stream_engine_t::stream_engine_t (fd_t fd_, const options_t & options_)
Definition at line 44 of file stream_engine.cpp.
References errno_assert, options, zmq::options_t::rcvbuf, s, and zmq::options_t::sndbuf.
zmq::stream_engine_t::~stream_engine_t ()
Definition at line 89 of file stream_engine.cpp.
References errno_assert, and zmq_assert.
zmq::stream_engine_t::stream_engine_t (const stream_engine_t &) [private]
Member Function Documentation
void zmq::stream_engine_t::activate_in () [virtual]
Implements zmq::i_engine.
Definition at line 258 of file stream_engine.cpp.
void zmq::stream_engine_t::activate_out () [virtual]
Implements zmq::i_engine.
Definition at line 247 of file stream_engine.cpp.
zmq::io_object_t::handle_t zmq::io_object_t::add_fd (fd_t fd_) [protected, inherited]
Definition at line 54 of file io_object.cpp.
void zmq::io_object_t::add_timer (int timout_, int id_) [protected, inherited]
Definition at line 84 of file io_object.cpp.
void zmq::io_object_t::cancel_timer (int id_) [protected, inherited]
Definition at line 89 of file io_object.cpp.
void zmq::stream_engine_t::error () [private]
Definition at line 266 of file stream_engine.cpp.
References zmq_assert.
void zmq::stream_engine_t::in_event () [virtual]
Reimplemented from zmq::io_object_t.
Definition at line 153 of file stream_engine.cpp.
References unlikely, and zmq_assert.
const stream_engine_t& zmq::stream_engine_t::operator= (const stream_engine_t &) [private]
void zmq::stream_engine_t::out_event () [virtual]
Reimplemented from zmq::io_object_t.
Definition at line 208 of file stream_engine.cpp.
References unlikely, and zmq_assert.
void zmq::stream_engine_t::plug (class io_thread_t * io_thread_, class session_base_t * session_) [virtual]
Implements zmq::i_engine.
Definition at line 105 of file stream_engine.cpp.
References zmq::io_object_t::plug(), and zmq_assert.
void zmq::io_object_t::plug (class io_thread_t * io_thread_) [inherited]
Definition at line 36 of file io_object.cpp.
References zmq::io_thread_t::get_poller(), and zmq_assert.
Referenced by zmq::io_object_t::io_object_t(), and plug().
int zmq::stream_engine_t::read (void * data_, size_t size_) [private]
Definition at line 319 of file stream_engine.cpp.
References ECONNREFUSED, and errno_assert.
void zmq::io_object_t::reset_pollin (handle_t handle_) [protected, inherited]
Definition at line 69 of file io_object.cpp.
void zmq::io_object_t::reset_pollout (handle_t handle_) [protected, inherited]
Definition at line 79 of file io_object.cpp.
void zmq::io_object_t::rm_fd (handle_t handle_) [protected, inherited]
Definition at line 59 of file io_object.cpp.
void zmq::io_object_t::set_pollin (handle_t handle_) [protected, inherited]
Definition at line 64 of file io_object.cpp.
void zmq::io_object_t::set_pollout (handle_t handle_) [protected, inherited]
Definition at line 74 of file io_object.cpp.
void zmq::stream_engine_t::terminate () [virtual]
Implements zmq::i_engine.
Definition at line 147 of file stream_engine.cpp.
void zmq::io_object_t::timer_event (int id_) [protected, virtual, inherited]
Implements zmq::i_poll_events.
Reimplemented in zmq::ipc_connecter_t, zmq::session_base_t, and zmq::tcp_connecter_t.
Definition at line 104 of file io_object.cpp.
References zmq_assert.
void zmq::stream_engine_t::unplug () [virtual]
Implements zmq::i_engine.
Definition at line 129 of file stream_engine.cpp.
References zmq::io_object_t::unplug(), and zmq_assert.
int zmq::stream_engine_t::write (const void * data_, size_t size_) [private]
Definition at line 274 of file stream_engine.cpp.
References errno_assert.
Member Data Documentation
decoder_t zmq::stream_engine_t::decoder [private]
Definition at line 81 of file stream_engine.hpp.
encoder_t zmq::stream_engine_t::encoder [private]
Definition at line 85 of file stream_engine.hpp.
handle_t zmq::stream_engine_t::handle [private]
Definition at line 77 of file stream_engine.hpp.
unsigned char* zmq::stream_engine_t::inpos [private]
Definition at line 79 of file stream_engine.hpp.
size_t zmq::stream_engine_t::insize [private]
Definition at line 80 of file stream_engine.hpp.
class session_base_t* zmq::stream_engine_t::leftover_session [private]
Definition at line 91 of file stream_engine.hpp.
options_t zmq::stream_engine_t::options [private]
Definition at line 93 of file stream_engine.hpp.
Referenced by stream_engine_t().
unsigned char* zmq::stream_engine_t::outpos [private]
Definition at line 83 of file stream_engine.hpp.
size_t zmq::stream_engine_t::outsize [private]
Definition at line 84 of file stream_engine.hpp.
bool zmq::stream_engine_t::plugged [private]
Definition at line 95 of file stream_engine.hpp.
fd_t zmq::stream_engine_t::s [private]
Definition at line 75 of file stream_engine.hpp.
Referenced by stream_engine_t().
class session_base_t* zmq::stream_engine_t::session [private]
Definition at line 88 of file stream_engine.hpp.
The documentation for this class was generated from the following files:
/home/travlr/src/libzmq/master/src/stream_engine.hpp
/home/travlr/src/libzmq/master/src/stream_engine.cpp