libzmq: zmq::ctx_t Class Reference
zmq::ctx_t Class Reference
#include <ctx.hpp>
Public Types
enum { term_tid = 0, reaper_tid = 1 }
Public Member Functions
ctx_t (uint32_t io_threads_)
bool check_tag ()
class io_thread_t * choose_io_thread (uint64_t affinity_)
class socket_base_t * create_socket (int type_)
void destroy_socket (class socket_base_t *socket_)
endpoint_t find_endpoint (const char *addr_)
class object_t * get_reaper ()
void log (const char *format_, va_list args_)
int register_endpoint (const char *addr_, endpoint_t &endpoint_)
void send_command (uint32_t tid_, const command_t &command_)
int terminate ()
void unregister_endpoints (class socket_base_t *socket_)
Private Types
typedef std::vector< uint32_t > emtpy_slots_t
typedef std::map< std::string,
endpoint_t > endpoints_t
typedef std::vector< class
io_thread_t * > io_threads_t
typedef array_t< socket_base_t > sockets_t
Private Member Functions
ctx_t (const ctx_t &)
~ctx_t ()
const ctx_t & operator= (const ctx_t &)
Private Attributes
emtpy_slots_t empty_slots
endpoints_t endpoints
mutex_t endpoints_sync
io_threads_t io_threads
class socket_base_t * log_socket
mutex_t log_sync
class reaper_t * reaper
uint32_t slot_count
mutex_t slot_sync
mailbox_t ** slots
sockets_t sockets
uint32_t tag
mailbox_t term_mailbox
bool terminating
Detailed Description
Definition at line 53 of file ctx.hpp.
Member Typedef Documentation
typedef std::vector<uint32_t> zmq::ctx_t::emtpy_slots_t [private]
Definition at line 112 of file ctx.hpp.
typedef std::map<std::string, endpoint_t> zmq::ctx_t::endpoints_t [private]
Definition at line 139 of file ctx.hpp.
typedef std::vector<class io_thread_t*> zmq::ctx_t::io_threads_t [private]
Definition at line 128 of file ctx.hpp.
typedef array_t<socket_base_t> zmq::ctx_t::sockets_t [private]
Definition at line 108 of file ctx.hpp.
Member Enumeration Documentation
anonymous enum
Enumerator:
term_tid
reaper_tid
Definition at line 93 of file ctx.hpp.
             {
            term_tid = 0,
            reaper_tid = 1
        };
Constructor & Destructor Documentation
zmq::ctx_t::ctx_t (uint32_t io_threads_)
Definition at line 39 of file ctx.cpp.
References alloc_assert, zmq::socket_base_t::bind(), create_socket(), empty_slots, zmq::io_thread_t::get_mailbox(), zmq::reaper_t::get_mailbox(), io_threads, log_socket, zmq::max_sockets, reaper, reaper_tid, slot_count, slots, zmq::io_thread_t::start(), zmq::reaper_t::start(), term_mailbox, term_tid, zmq_assert, and ZMQ_PUB.
                                     :
    tag (0xbadcafe0),
    terminating (false)
{
    int rc;
    //  Initialise the array of mailboxes. Additional three slots are for
    //  internal log socket and the zmq_term thread the reaper thread.
    slot_count = max_sockets + io_threads_ + 3;
    slots = (mailbox_t**) malloc (sizeof (mailbox_t*) * slot_count);
    alloc_assert (slots);
    //  Initialise the infrastructure for zmq_term thread.
    slots [term_tid] = &term_mailbox;
    //  Create the reaper thread.
    reaper = new (std::nothrow) reaper_t (this, reaper_tid);
    alloc_assert (reaper);
    slots [reaper_tid] = reaper->get_mailbox ();
    reaper->start ();
    //  Create I/O thread objects and launch them.
    for (uint32_t i = 2; i != io_threads_ + 2; i++) {
        io_thread_t *io_thread = new (std::nothrow) io_thread_t (this, i);
        alloc_assert (io_thread);
        io_threads.push_back (io_thread);
        slots [i] = io_thread->get_mailbox ();
        io_thread->start ();
    }
    //  In the unused part of the slot array, create a list of empty slots.
    for (int32_t i = (int32_t) slot_count - 1;
          i >= (int32_t) io_threads_ + 2; i--) {
        empty_slots.push_back (i);
        slots [i] = NULL;
    }
    //  Create the logging infrastructure.
    log_socket = create_socket (ZMQ_PUB);
    zmq_assert (log_socket);
    rc = log_socket->bind ("sys://log");
    zmq_assert (rc == 0);
}
zmq::ctx_t::~ctx_t () [private]
Definition at line 88 of file ctx.cpp.
References zmq_assert.
{
    //  Check that there are no remaining sockets.
    zmq_assert (sockets.empty ());
    //  Ask I/O threads to terminate. If stop signal wasn't sent to I/O
    //  thread subsequent invocation of destructor would hang-up.
    for (io_threads_t::size_type i = 0; i != io_threads.size (); i++)
        io_threads [i]->stop ();
    //  Wait till I/O threads actually terminate.
    for (io_threads_t::size_type i = 0; i != io_threads.size (); i++)
        delete io_threads [i];
    //  Deallocate the reaper thread object.
    delete reaper;
    //  Deallocate the array of mailboxes. No special work is
    //  needed as mailboxes themselves were deallocated with their
    //  corresponding io_thread/socket objects.
    free (slots);
    //  Remove the tag, so that the object is considered dead.
    tag = 0xdeadbeef;
}
zmq::ctx_t::ctx_t (const ctx_t &) [private]
Member Function Documentation
bool zmq::ctx_t::check_tag ()
Definition at line 83 of file ctx.cpp.
{
    return tag == 0xbadcafe0;
}
zmq::io_thread_t * zmq::ctx_t::choose_io_thread (uint64_t affinity_)
Definition at line 227 of file ctx.cpp.
References zmq::io_thread_t::get_load(), and zmq_assert.
{
    if (io_threads.empty ())
        return NULL;
    //  Find the I/O thread with minimum load.
    int min_load = -1;
    io_threads_t::size_type result = 0;
    for (io_threads_t::size_type i = 0; i != io_threads.size (); i++) {
        if (!affinity_ || (affinity_ & (uint64_t (1) << i))) {
            int load = io_threads [i]->get_load ();
            if (min_load == -1 || load < min_load) {
                min_load = load;
                result = i;
            }
        }
    }
    zmq_assert (min_load != -1);
    return io_threads [result];
}
zmq::socket_base_t * zmq::ctx_t::create_socket (int type_)
Definition at line 160 of file ctx.cpp.
References zmq::socket_base_t::create(), ETERM, and zmq::socket_base_t::get_mailbox().
Referenced by ctx_t().
{
    slot_sync.lock ();
    //  Once zmq_term() was called, we can't create new sockets.
    if (terminating) {
        slot_sync.unlock ();
        errno = ETERM;
        return NULL;
    }
    //  If max_sockets limit was reached, return error.
    if (empty_slots.empty ()) {
        slot_sync.unlock ();
        errno = EMFILE;
        return NULL;
    }
    //  Choose a slot for the socket.
    uint32_t slot = empty_slots.back ();
    empty_slots.pop_back ();
    //  Create the socket and register its mailbox.
    socket_base_t *s = socket_base_t::create (type_, this, slot);
    if (!s) {
        empty_slots.push_back (slot);
        slot_sync.unlock ();
        return NULL;
    }
    sockets.push_back (s);
    slots [slot] = s->get_mailbox ();
    slot_sync.unlock ();
    return s;
}
void zmq::ctx_t::destroy_socket (class socket_base_t * socket_)
Definition at line 197 of file ctx.cpp.
References zmq::object_t::get_tid().
{
    slot_sync.lock ();
    //  Free the associared thread slot.
    uint32_t tid = socket_->get_tid ();
    empty_slots.push_back (tid);
    slots [tid] = NULL;
    //  Remove the socket from the list of sockets.
    sockets.erase (socket_);
    //  If zmq_term() was already called and there are no more socket
    //  we can ask reaper thread to terminate.
    if (terminating && sockets.empty ())
        reaper->stop ();
    slot_sync.unlock ();
}
zmq::endpoint_t zmq::ctx_t::find_endpoint (const char * addr_)
Definition at line 282 of file ctx.cpp.
References ECONNREFUSED, zmq::own_t::inc_seqnum(), and zmq::endpoint_t::socket.
{
     endpoints_sync.lock ();
     endpoints_t::iterator it = endpoints.find (addr_);
     if (it == endpoints.end ()) {
         endpoints_sync.unlock ();
         errno = ECONNREFUSED;
         endpoint_t empty = {NULL, options_t()};
         return empty;
     }
     endpoint_t *endpoint = &it->second;
     //  Increment the command sequence number of the peer so that it won't
     //  get deallocated until "bind" command is issued by the caller.
     //  The subsequent 'bind' has to be called with inc_seqnum parameter
     //  set to false, so that the seqnum isn't incremented twice.
     endpoint->socket->inc_seqnum ();
     endpoints_sync.unlock ();
     return *endpoint;
}
zmq::object_t * zmq::ctx_t::get_reaper ()
Definition at line 217 of file ctx.cpp.
{
    return reaper;
}
void zmq::ctx_t::log (const char * format_, va_list args_)
Definition at line 305 of file ctx.cpp.
References zmq::msg_t::close(), zmq::msg_t::data, errno_assert, zmq::msg_t::init_size(), and zmq::msg_t::size.
{
    //  Create the log message.
    msg_t msg;
    int rc = msg.init_size (strlen (format_) + 1);
    errno_assert (rc == 0);
    memcpy (msg.data (), format_, msg.size ());
    //  At this  point we migrate the log socket to the current thread.
    //  We rely on mutex for executing the memory barrier.
    log_sync.lock ();
    if (log_socket)
        log_socket->send (&msg, 0);
    log_sync.unlock ();
    rc = msg.close ();
    errno_assert (rc == 0);
}
const ctx_t& zmq::ctx_t::operator= (const ctx_t &) [private]
int zmq::ctx_t::register_endpoint (const char * addr_, endpoint_t & endpoint_)
Definition at line 248 of file ctx.cpp.
References EADDRINUSE.
{
    endpoints_sync.lock ();
    bool inserted = endpoints.insert (endpoints_t::value_type (
        std::string (addr_), endpoint_)).second;
    if (!inserted) {
        errno = EADDRINUSE;
        endpoints_sync.unlock ();
        return -1;
    }
    endpoints_sync.unlock ();
    return 0;
}
void zmq::ctx_t::send_command (uint32_t tid_, const command_t & command_)
Definition at line 222 of file ctx.cpp.
{
    slots [tid_]->send (command_);
}
int zmq::ctx_t::terminate ()
Definition at line 114 of file ctx.cpp.
References zmq::command_t::done, zmq::command_t::type, and zmq_assert.
{
    //  Check whether termination was already underway, but interrupted and now
    //  restarted.
    slot_sync.lock ();
    bool restarted = terminating;
    slot_sync.unlock ();
    //  First attempt to terminate the context.
    if (!restarted) {
        //  Close the logging infrastructure.
        log_sync.lock ();
        int rc = log_socket->close ();
        zmq_assert (rc == 0);
        log_socket = NULL;
        log_sync.unlock ();
        //  First send stop command to sockets so that any blocking calls can be
        //  interrupted. If there are no sockets we can ask reaper thread to stop.
        slot_sync.lock ();
        terminating = true;
        for (sockets_t::size_type i = 0; i != sockets.size (); i++)
            sockets [i]->stop ();
        if (sockets.empty ())
            reaper->stop ();
        slot_sync.unlock ();
    }
    //  Wait till reaper thread closes all the sockets.
    command_t cmd;
    int rc = term_mailbox.recv (&cmd, true);
    if (rc == -1 && errno == EINTR)
        return -1;
    zmq_assert (rc == 0);
    zmq_assert (cmd.type == command_t::done);
    slot_sync.lock ();
    zmq_assert (sockets.empty ());
    slot_sync.unlock ();
    //  Deallocate the resources.
    delete this;
    return 0;
}
void zmq::ctx_t::unregister_endpoints (class socket_base_t * socket_)
Definition at line 264 of file ctx.cpp.
{
    endpoints_sync.lock ();
    endpoints_t::iterator it = endpoints.begin ();
    while (it != endpoints.end ()) {
        if (it->second.socket == socket_) {
            endpoints_t::iterator to_erase = it;
            ++it;
            endpoints.erase (to_erase);
            continue;
        }
        ++it;
    }
    endpoints_sync.unlock ();
}
Member Data Documentation
emtpy_slots_t zmq::ctx_t::empty_slots [private]
Definition at line 113 of file ctx.hpp.
Referenced by ctx_t().
endpoints_t zmq::ctx_t::endpoints [private]
Definition at line 140 of file ctx.hpp.
mutex_t zmq::ctx_t::endpoints_sync [private]
Definition at line 143 of file ctx.hpp.
io_threads_t zmq::ctx_t::io_threads [private]
Definition at line 129 of file ctx.hpp.
Referenced by ctx_t().
class socket_base_t* zmq::ctx_t::log_socket [private]
Definition at line 147 of file ctx.hpp.
Referenced by ctx_t().
mutex_t zmq::ctx_t::log_sync [private]
Definition at line 148 of file ctx.hpp.
class reaper_t* zmq::ctx_t::reaper [private]
Definition at line 125 of file ctx.hpp.
Referenced by ctx_t().
uint32_t zmq::ctx_t::slot_count [private]
Definition at line 132 of file ctx.hpp.
Referenced by ctx_t().
mutex_t zmq::ctx_t::slot_sync [private]
Definition at line 122 of file ctx.hpp.
mailbox_t** zmq::ctx_t::slots [private]
Definition at line 133 of file ctx.hpp.
Referenced by ctx_t().
sockets_t zmq::ctx_t::sockets [private]
Definition at line 109 of file ctx.hpp.
uint32_t zmq::ctx_t::tag [private]
Definition at line 103 of file ctx.hpp.
mailbox_t zmq::ctx_t::term_mailbox [private]
Definition at line 136 of file ctx.hpp.
Referenced by ctx_t().
bool zmq::ctx_t::terminating [private]
Definition at line 116 of file ctx.hpp.
The documentation for this class was generated from the following files:
/home/travlr/src/libzmq/src/ctx.hpp
/home/travlr/src/libzmq/src/ctx.cpp