libzmq: zmq::msg_t Class Reference
zmq::msg_t Class Reference
#include <msg.hpp>
Classes
struct content_t
Public Types
enum { label = 1, command = 2, shared = 64, more = 128 }
Public Member Functions
void add_refs (int refs_)
bool check ()
int close ()
int copy (msg_t &src_)
void * data ()
unsigned char flags ()
int init ()
int init_data (void *data_, size_t size_, msg_free_fn *ffn_, void *hint_)
int init_delimiter ()
int init_size (size_t size_)
bool is_delimiter ()
int move (msg_t &src_)
void reset_flags (unsigned char flags_)
void rm_refs (int refs_)
void set_flags (unsigned char flags_)
size_t size ()
Private Types
enum { max_vsm_size = 29 }
enum type_t {
type_min = 101, type_vsm = 101, type_lmsg = 102, type_delimiter = 103,
type_max = 103
}
Private Attributes
union {
struct {
unsigned char flags
unsigned char type
unsigned char unused [max_vsm_size+1]
} base
struct {
unsigned char flags
unsigned char type
unsigned char unused [max_vsm_size+1]
} delimiter
struct {
content_t * content
unsigned char flags
unsigned char type
unsigned char unused [max_vsm_size+1-sizeof(content_t *)]
} lmsg
struct {
unsigned char data [max_vsm_size]
unsigned char flags
unsigned char size
unsigned char type
} vsm
} u
Detailed Description
Definition at line 43 of file msg.hpp.
Member Enumeration Documentation
anonymous enum
Enumerator:
label
command
shared
more
Definition at line 48 of file msg.hpp.
anonymous enum [private]
Enumerator:
max_vsm_size
Definition at line 83 of file msg.hpp.
enum zmq::msg_t::type_t [private]
Enumerator:
type_min
type_vsm
type_lmsg
type_delimiter
type_max
Definition at line 102 of file msg.hpp.
Member Function Documentation
void zmq::msg_t::add_refs (int refs_)
Definition at line 240 of file msg.cpp.
References shared, and zmq_assert.
Referenced by zmq::dist_t::distribute().
bool zmq::msg_t::check ()
Definition at line 38 of file msg.cpp.
References type_max, type_min, and u.
Referenced by copy(), move(), zmq::socket_base_t::recv(), and zmq::socket_base_t::send().
int zmq::msg_t::close ()
Definition at line 104 of file msg.cpp.
References shared, and unlikely.
Referenced by zmq::session_t::clean_pipes(), zmq::dist_t::distribute(), zmq::lb_t::has_out(), zmq::ctx_t::log(), zmq::pipe_t::process_hiccup(), zmq::pipe_t::process_pipe_term_ack(), zmq::fq_t::recvpipe(), zmq::pipe_t::rollback(), zmq::lb_t::send(), zmq::xsub_t::send_subscription(), zmq::pair_t::xhas_out(), zmq::xpub_t::xread_activated(), zmq::xrep_t::xrecv(), zmq::xpub_t::xrecv(), zmq::req_t::xrecv(), zmq::pair_t::xrecv(), zmq::generic_t::xrecv(), zmq::xrep_t::xsend(), zmq::generic_t::xsend(), and zmq::sub_t::xsetsockopt().
int zmq::msg_t::copy (msg_t & src_)
Definition at line 158 of file msg.cpp.
References base, check(), lmsg, shared, u, and unlikely.
void* zmq::msg_t::data ()
unsigned char zmq::msg_t::flags ()
int zmq::msg_t::init ()
Definition at line 43 of file msg.cpp.
Referenced by zmq::session_t::clean_pipes(), zmq::decoder_t::decoder_t(), zmq::dist_t::distribute(), zmq::encoder_t::encoder_t(), zmq::generic_t::generic_t(), zmq::lb_t::has_out(), move(), zmq::fq_t::recvpipe(), zmq::lb_t::send(), zmq::session_t::write(), zmq::pair_t::xhas_out(), zmq::xpub_t::xread_activated(), zmq::req_t::xrecv(), zmq::pair_t::xrecv(), zmq::xrep_t::xrep_t(), zmq::xrep_t::xsend(), zmq::pair_t::xsend(), zmq::generic_t::xsend(), and zmq::xsub_t::xsub_t().
int zmq::msg_t::init_data (void * data_, size_t size_, msg_free_fn * ffn_, void * hint_)
Definition at line 77 of file msg.cpp.
int zmq::msg_t::init_delimiter ()
Definition at line 97 of file msg.cpp.
Referenced by zmq::pipe_t::terminate().
int zmq::msg_t::init_size (size_t size_)
Definition at line 51 of file msg.cpp.
Referenced by zmq::ctx_t::log(), zmq::xsub_t::send_subscription(), zmq::xrep_t::xrecv(), zmq::xpub_t::xrecv(), zmq::generic_t::xrecv(), zmq::req_t::xsend(), and zmq::sub_t::xsetsockopt().
bool zmq::msg_t::is_delimiter ()
Definition at line 235 of file msg.cpp.
Referenced by zmq::pipe_t::is_delimiter(), and zmq::pipe_t::read().
int zmq::msg_t::move (msg_t & src_)
Definition at line 137 of file msg.cpp.
References check(), init(), and unlikely.
Referenced by zmq::xsub_t::xrecv(), zmq::xrep_t::xrecv(), and zmq::generic_t::xrecv().
void zmq::msg_t::reset_flags (unsigned char flags_)
Definition at line 230 of file msg.cpp.
Referenced by zmq::socket_base_t::extract_flags().
void zmq::msg_t::rm_refs (int refs_)
Definition at line 260 of file msg.cpp.
References shared, and zmq_assert.
Referenced by zmq::dist_t::distribute().
void zmq::msg_t::set_flags (unsigned char flags_)
Definition at line 225 of file msg.cpp.
Referenced by zmq::socket_base_t::send(), zmq::xrep_t::xrecv(), zmq::generic_t::xrecv(), and zmq::req_t::xsend().
size_t zmq::msg_t::size ()
Member Data Documentation
struct { ... } zmq::msg_t::base
Referenced by copy().
content_t* zmq::msg_t::content
Definition at line 128 of file msg.hpp.
void * zmq::msg_t::data
Definition at line 122 of file msg.hpp.
Referenced by zmq::ctx_t::log(), zmq::xsub_t::send_subscription(), zmq::xpub_t::xread_activated(), zmq::xrep_t::xrecv(), zmq::xpub_t::xrecv(), zmq::req_t::xrecv(), zmq::generic_t::xrecv(), zmq::xsub_t::xsend(), zmq::xrep_t::xsend(), zmq::xpub_t::xsend(), zmq::req_t::xsend(), zmq::generic_t::xsend(), and zmq::sub_t::xsetsockopt().
struct { ... } zmq::msg_t::delimiter
unsigned char zmq::msg_t::flags
Definition at line 119 of file msg.hpp.
Referenced by zmq::socket_base_t::extract_flags(), zmq::session_t::read(), zmq::pipe_t::read(), zmq::fq_t::recvpipe(), zmq::pipe_t::rollback(), zmq::lb_t::send(), zmq::dist_t::send_to_matching(), zmq::pipe_t::write(), zmq::dist_t::write(), zmq::xsub_t::xrecv(), zmq::xrep_t::xrecv(), zmq::req_t::xrecv(), zmq::rep_t::xrecv(), zmq::generic_t::xrecv(), zmq::xrep_t::xsend(), zmq::xpub_t::xsend(), zmq::req_t::xsend(), zmq::rep_t::xsend(), and zmq::generic_t::xsend().
struct { ... } zmq::msg_t::lmsg
Referenced by copy().
size_t zmq::msg_t::size
Definition at line 123 of file msg.hpp.
Referenced by zmq::ctx_t::log(), zmq::xpub_t::xread_activated(), zmq::req_t::xrecv(), zmq::xsub_t::xsend(), zmq::xrep_t::xsend(), zmq::xpub_t::xsend(), and zmq::generic_t::xsend().
unsigned char zmq::msg_t::type
Definition at line 118 of file msg.hpp.
union { ... } zmq::msg_t::u [private]
Referenced by check(), and copy().
unsigned char zmq::msg_t::unused[max_vsm_size+1]
Definition at line 117 of file msg.hpp.
struct { ... } zmq::msg_t::vsm
The documentation for this class was generated from the following files:
src/msg.hpp
src/msg.cpp