libzmq: /home/travlr/dev/zmq-contribution/repos/libzmq/perf/inproc_lat.cpp File Reference
inproc_lat.cpp File Reference
#include "../include/zmq.h"
#include "../include/zmq_utils.h"
#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include "../src/platform.hpp"
#include <pthread.h>
Functions
int main (int argc, char *argv[])
static void * worker (void *ctx_)
Variables
static size_t message_size
static int roundtrip_count
Function Documentation
int main (int argc, char * argv[])
Definition at line 101 of file inproc_lat.cpp.
References message_size, roundtrip_count, worker(), zmq_bind(), zmq_close(), zmq_init(), zmq_msg_close(), zmq_msg_data(), zmq_msg_init_size(), zmq_msg_size(), zmq_recvmsg(), ZMQ_REQ, zmq_sendmsg(), zmq_socket(), zmq_stopwatch_start(), zmq_stopwatch_stop(), zmq_strerror(), and zmq_term().
static void* worker (void * ctx_) [static]
Definition at line 43 of file inproc_lat.cpp.
References roundtrip_count, zmq_close(), zmq_connect(), zmq_msg_close(), zmq_msg_init(), zmq_recvmsg(), ZMQ_REP, zmq_sendmsg(), zmq_socket(), and zmq_strerror().
Referenced by main().
Variable Documentation
size_t message_size [static]
Definition at line 37 of file inproc_lat.cpp.
Referenced by main().
int roundtrip_count [static]
Definition at line 38 of file inproc_lat.cpp.
Referenced by main(), and worker().