libzmq: zmq Namespace Reference
zmq Namespace Reference
Classes
class array_item_t
class array_t
class atomic_counter_t
class atomic_ptr_t
class clock_t
struct command_t
class connect_session_t
class ctx_t
class decoder_base_t
class decoder_t
class dist_t
class encoder_base_t
class encoder_t
struct endpoint_t
class fq_t
struct i_engine
struct i_inout
struct i_poll_events
struct i_reader_events
struct i_writer_events
class io_object_t
class io_thread_t
class lb_t
class mailbox_t
class msg_t
class mutex_t
class named_session_t
class object_t
struct options_t
class own_t
class pair_t
class poller_base_t
class pub_t
class pull_t
class push_t
class reader_t
class reaper_t
class rep_t
class req_t
class select_t
class semaphore_t
class session_t
class socket_base_t
class sub_t
class tcp_connecter_t
class tcp_listener_t
class tcp_socket_t
class thread_t
class transient_session_t
class trie_t
class writer_t
class xpub_t
class xrep_t
class xreq_t
class xsub_t
class ypipe_t
class yqueue_t
class zmq_connecter_t
class zmq_engine_t
class zmq_init_t
class zmq_listener_t
Typedefs
typedef std::basic_string
< unsigned char > blob_t
typedef int fd_t
typedef ypipe_t< msg_t,
message_pipe_granularity > pipe_t
typedef void(thread_fn)(void *)
Enumerations
enum {
max_sockets = 512, message_pipe_granularity = 256, max_vsm_size = 29, inbound_poll_rate = 100,
in_batch_size = 8192, out_batch_size = 8192, max_wm_delta = 1024, max_io_events = 256,
max_command_delay = 3000000, clock_precision = 1000000, pgm_max_tpdu = 1500
}
enum { retired_fd = -1 }
Functions
void create_pipe (object_t *reader_parent_, object_t *writer_parent_, int hwm_, class reader_t **reader_, class writer_t **writer_)
void deallocate_command (command_t *cmd_)
const char * errno_to_string (int errno_)
void generate_uuid (void *buf_)
uint16_t get_uint16 (unsigned char *buffer_)
uint32_t get_uint32 (unsigned char *buffer_)
uint64_t get_uint64 (unsigned char *buffer_)
uint8_t get_uint8 (unsigned char *buffer_)
void put_uint16 (unsigned char *buffer_, uint16_t value)
void put_uint32 (unsigned char *buffer_, uint32_t value)
void put_uint64 (unsigned char *buffer_, uint64_t value)
void put_uint8 (unsigned char *buffer_, uint8_t value)
int resolve_ip_hostname (sockaddr_storage *addr_, socklen_t *addr_len_, const char *hostname_)
int resolve_ip_interface (sockaddr_storage *addr_, socklen_t *addr_len_, char const *interface_)
int resolve_local_path (sockaddr_storage *addr_, socklen_t *addr_len_, const char *pathname_)
Typedef Documentation
typedef std::basic_string<unsigned char> zmq::blob_t
Definition at line 30 of file blob.hpp.
typedef int zmq::fd_t
Definition at line 41 of file fd.hpp.
typedef ypipe_t<msg_t, message_pipe_granularity> zmq::pipe_t
Definition at line 45 of file pipe.hpp.
typedef void(zmq::thread_fn)(void *)
Definition at line 35 of file thread.hpp.
Enumeration Type Documentation
anonymous enum
Enumerator:
max_sockets
message_pipe_granularity
max_vsm_size
inbound_poll_rate
in_batch_size
out_batch_size
max_wm_delta
max_io_events
max_command_delay
clock_precision
pgm_max_tpdu
Definition at line 29 of file config.hpp.
    {
        //  Maximum number of sockets that can be opened at the same time.
        max_sockets = 512,
        //  Number of new messages in message pipe needed to trigger new memory
        //  allocation. Setting this parameter to 256 decreases the impact of
        //  memory allocation by approximately 99.6%
        message_pipe_granularity = 256,
        //  Size in bytes of the largest message that is still copied around
        //  rather than being reference-counted.
        max_vsm_size = 29,
        //  Determines how often does socket poll for new commands when it
        //  still has unprocessed messages to handle. Thus, if it is set to 100,
        //  socket will process 100 inbound messages before doing the poll.
        //  If there are no unprocessed messages available, poll is done
        //  immediately. Decreasing the value trades overall latency for more
        //  real-time behaviour (less latency peaks).
        inbound_poll_rate = 100,
        //  Maximal batching size for engines with receiving functionality.
        //  So, if there are 10 messages that fit into the batch size, all of
        //  them may be read by a single 'recv' system call, thus avoiding
        //  unnecessary network stack traversals.
        in_batch_size = 8192,
        //  Maximal batching size for engines with sending functionality.
        //  So, if there are 10 messages that fit into the batch size, all of
        //  them may be written by a single 'send' system call, thus avoiding
        //  unnecessary network stack traversals.
        out_batch_size = 8192,
        //  Maximal delta between high and low watermark.
        max_wm_delta = 1024,
        //  Maximum number of events the I/O thread can process in one go.
        max_io_events = 256,
        //  Maximal delay to process command in API thread (in CPU ticks).
        //  3,000,000 ticks equals to 1 - 2 milliseconds on current CPUs.
        //  Note that delay is only applied when there is continuous stream of
        //  messages to process. If not so, commands are processed immediately.
        max_command_delay = 3000000,
        //  Low-precision clock precision in CPU ticks. 1ms. Value of 1000000
        //  should be OK for CPU frequencies above 1GHz. If should work
        //  reasonably well for CPU frequencies above 500MHz. For lower CPU
        //  frequencies you may consider lowering this value to get best
        //  possible latencies.
        clock_precision = 1000000,
        //  Maximum transport data unit size for PGM (TPDU).
        pgm_max_tpdu = 1500
    };
anonymous enum
Enumerator:
retired_fd
Definition at line 42 of file fd.hpp.
{retired_fd = -1};
Function Documentation
void zmq::create_pipe (object_t * reader_parent_, object_t * writer_parent_, int hwm_, class reader_t ** reader_, class writer_t ** writer_)
Definition at line 288 of file pipe.cpp.
References alloc_assert, and max_wm_delta.
Referenced by zmq::socket_base_t::connect(), and zmq::session_t::process_attach().
{
    //  First compute the low water mark. Following point should be taken
    //  into consideration:
    //
    //  1. LWM has to be less than HWM.
    //  2. LWM cannot be set to very low value (such as zero) as after filling
    //     the queue it would start to refill only after all the messages are
    //     read from it and thus unnecessarily hold the progress back.
    //  3. LWM cannot be set to very high value (such as HWM-1) as it would
    //     result in lock-step filling of the queue - if a single message is
    //     read from a full queue, writer thread is resumed to write exactly one
    //     message to the queue and go back to sleep immediately. This would
    //     result in low performance.
    //
    //  Given the 3. it would be good to keep HWM and LWM as far apart as
    //  possible to reduce the thread switching overhead to almost zero,
    //  say HWM-LWM should be max_wm_delta.
    //
    //  That done, we still we have to account for the cases where
    //  HWM < max_wm_delta thus driving LWM to negative numbers.
    //  Let's make LWM 1/2 of HWM in such cases.
    int lwm = (hwm_ > max_wm_delta * 2) ?
        hwm_ - max_wm_delta : (hwm_ + 1) / 2;
    //  Create all three objects pipe consists of: the pipe per se, reader and
    //  writer. The pipe will be handled by reader and writer, its never passed
    //  to the user. Reader and writer are returned to the user.
    pipe_t *pipe = new (std::nothrow) pipe_t ();
    alloc_assert (pipe);
    *reader_ = new (std::nothrow) reader_t (reader_parent_, pipe, lwm);
    alloc_assert (*reader_);
    *writer_ = new (std::nothrow) writer_t (writer_parent_, pipe, *reader_,
        hwm_);
    alloc_assert (*writer_);
}
void zmq::deallocate_command (command_t * cmd_)
Definition at line 25 of file command.cpp.
References zmq::command_t::args, zmq::command_t::attach, zmq::command_t::bind, and zmq::command_t::type.
Referenced by zmq::object_t::process_command().
{
    switch (cmd_->type) {
    case command_t::attach:
        if (cmd_->args.attach.peer_identity)
            free (cmd_->args.attach.peer_identity);
        break;
    case command_t::bind:
        if (cmd_->args.bind.peer_identity)
            free (cmd_->args.bind.peer_identity);
        break;
    default:
        /*  noop  */;
    }
}
const char * zmq::errno_to_string (int errno_)
Definition at line 24 of file err.cpp.
References EADDRINUSE, EADDRNOTAVAIL, ECONNREFUSED, EFSM, EINPROGRESS, EMTHREAD, ENETDOWN, ENOBUFS, ENOCOMPATPROTO, ENOTSUP, EPROTONOSUPPORT, and ETERM.
Referenced by zmq_strerror().
{
    switch (errno_) {
#if defined ZMQ_HAVE_WINDOWS
    case ENOTSUP:
        return "Not supported";
    case EPROTONOSUPPORT:
        return "Protocol not supported";
    case ENOBUFS:
        return "No buffer space available";
    case ENETDOWN:
        return "Network is down";
    case EADDRINUSE:
        return "Address in use";
    case EADDRNOTAVAIL:
        return "Address not available";
    case ECONNREFUSED:
        return "Connection refused";
    case EINPROGRESS:
        return "Operation in progress";
#endif
    case EFSM:
        return "Operation cannot be accomplished in current state";
    case ENOCOMPATPROTO:
        return "The protocol is not compatible with the socket type";
    case ETERM:
        return "Context was terminated";
    case EMTHREAD:
        return "No thread available";
    default:
#if defined _MSC_VER
#pragma warning (push)
#pragma warning (disable:4996)
#endif
        return strerror (errno_);
#if defined _MSC_VER
#pragma warning (pop)
#endif
    }
}
void zmq::generate_uuid (void * buf_)
Definition at line 72 of file uuid.cpp.
References zmq_assert.
Referenced by zmq::socket_base_t::attach_pipes(), and zmq::zmq_init_t::zmq_init_t().
{
    unsigned char *buf = (unsigned char*) buf_;
    //  Generate random value.
    int ret = RAND_bytes (buf, 16);
    zmq_assert (ret == 1);
    //  Set UUID variant to 2 (UUID as specified in RFC4122).
    const unsigned char variant = 2;
    buf [8] = (buf [8] & 0x3f) | (variant << 6);
    //  Set UUID version to 4 (randomly or pseudo-randomly generated UUID).
    const unsigned char version = 4;
    buf [6] = (buf [6] & 0x0f) | (version << 4);
}
uint16_t zmq::get_uint16 (unsigned char * buffer_) [inline]
Definition at line 48 of file wire.hpp.
Referenced by zmq::zmq_init_t::write().
    {
        return
            (((uint16_t) buffer_ [0]) << 8) |
            ((uint16_t) buffer_ [1]);
    }
uint32_t zmq::get_uint32 (unsigned char * buffer_) [inline]
Definition at line 63 of file wire.hpp.
    {
        return
            (((uint32_t) buffer_ [0]) << 24) |
            (((uint32_t) buffer_ [1]) << 16) |
            (((uint32_t) buffer_ [2]) << 8) |
            ((uint32_t) buffer_ [3]);
    }
uint64_t zmq::get_uint64 (unsigned char * buffer_) [inline]
Definition at line 84 of file wire.hpp.
Referenced by zmq::decoder_t::eight_byte_size_ready().
    {
        return
            (((uint64_t) buffer_ [0]) << 56) |
            (((uint64_t) buffer_ [1]) << 48) |
            (((uint64_t) buffer_ [2]) << 40) |
            (((uint64_t) buffer_ [3]) << 32) |
            (((uint64_t) buffer_ [4]) << 24) |
            (((uint64_t) buffer_ [5]) << 16) |
            (((uint64_t) buffer_ [6]) << 8) |
            ((uint64_t) buffer_ [7]);
    }
uint8_t zmq::get_uint8 (unsigned char * buffer_) [inline]
Definition at line 37 of file wire.hpp.
    {
        return *buffer_;
    }
void zmq::put_uint16 (unsigned char * buffer_, uint16_t value) [inline]
Definition at line 42 of file wire.hpp.
Referenced by zmq::zmq_init_t::zmq_init_t().
    {
        buffer_ [0] = (unsigned char) (((value) >> 8) & 0xff);
        buffer_ [1] = (unsigned char) (value & 0xff);
    }
void zmq::put_uint32 (unsigned char * buffer_, uint32_t value) [inline]
Definition at line 55 of file wire.hpp.
    {
        buffer_ [0] = (unsigned char) (((value) >> 24) & 0xff);
        buffer_ [1] = (unsigned char) (((value) >> 16) & 0xff);
        buffer_ [2] = (unsigned char) (((value) >> 8) & 0xff);
        buffer_ [3] = (unsigned char) (value & 0xff);
    }
void zmq::put_uint64 (unsigned char * buffer_, uint64_t value) [inline]
Definition at line 72 of file wire.hpp.
Referenced by zmq::encoder_t::message_ready().
    {
        buffer_ [0] = (unsigned char) (((value) >> 56) & 0xff);
        buffer_ [1] = (unsigned char) (((value) >> 48) & 0xff);
        buffer_ [2] = (unsigned char) (((value) >> 40) & 0xff);
        buffer_ [3] = (unsigned char) (((value) >> 32) & 0xff);
        buffer_ [4] = (unsigned char) (((value) >> 24) & 0xff);
        buffer_ [5] = (unsigned char) (((value) >> 16) & 0xff);
        buffer_ [6] = (unsigned char) (((value) >> 8) & 0xff);
        buffer_ [7] = (unsigned char) (value & 0xff);
    }
void zmq::put_uint8 (unsigned char * buffer_, uint8_t value) [inline]
Definition at line 32 of file wire.hpp.
    {
        *buffer_ = value;
    }
int zmq::resolve_ip_hostname (sockaddr_storage * addr_, socklen_t * addr_len_, const char * hostname_)
Definition at line 271 of file ip.cpp.
References AI_NUMERICSERV, and zmq_assert.
Referenced by zmq::tcp_connecter_t::set_address().
{
    //  Find the ':' that separates hostname name from service.
    const char *delimiter = strchr (hostname_, ':');
    if (!delimiter) {
        errno = EINVAL;
        return -1;
    }
    //  Separate the hostname and service.
    std::string hostname (hostname_, delimiter - hostname_);
    std::string service (delimiter + 1);
    //  Set up the query.
    addrinfo req;
    memset (&req, 0, sizeof (req));
    //  We only support IPv4 addresses for now.
    req.ai_family = AF_INET;
    //  Need to choose one to avoid duplicate results from getaddrinfo() - this
    //  doesn't really matter, since it's not included in the addr-output.
    req.ai_socktype = SOCK_STREAM;
    //  Avoid named services due to unclear socktype.
    req.ai_flags = AI_NUMERICSERV;
    //  Resolve host name. Some of the error info is lost in case of error,
    //  however, there's no way to report EAI errors via errno.
    addrinfo *res;
    int rc = getaddrinfo (hostname.c_str (), service.c_str (), &req, &res);
    if (rc) {
        switch (rc) {
        case EAI_MEMORY:
            errno = ENOMEM;
            break;
        default:
        errno = EINVAL;
            break;
        }
        return -1;
    }
    //  Copy first result to output addr with hostname and service.
    zmq_assert ((size_t) (res->ai_addrlen) <= sizeof (*addr_));
    memcpy (addr_, res->ai_addr, res->ai_addrlen);
    *addr_len_ = (socklen_t) res->ai_addrlen;
    freeaddrinfo (res);
    return 0;
}
int zmq::resolve_ip_interface (sockaddr_storage * addr_, socklen_t * addr_len_, char const * interface_)
Definition at line 178 of file ip.cpp.
References AI_NUMERICSERV, resolve_nic_name(), and zmq_assert.
Referenced by zmq::tcp_listener_t::set_address().
{
    //  Find the ':' at end that separates NIC name from service.
    const char *delimiter = strrchr (interface_, ':');
    if (!delimiter) {
        errno = EINVAL;
        return -1;
    }
    //  Separate the name/port.
    std::string iface (interface_, delimiter - interface_);
    std::string service (delimiter + 1);
    //  Initialize the output parameter.
    memset (addr_, 0, sizeof (*addr_));
    //  Initialise IPv4-format family/port.
    sockaddr_in ip4_addr;
    memset (&ip4_addr, 0, sizeof (ip4_addr));
    ip4_addr.sin_family = AF_INET;
    ip4_addr.sin_port = htons ((uint16_t) atoi (service.c_str()));
    //  Initialize temporary output pointers with ip4_addr
    sockaddr *out_addr = (sockaddr *) &ip4_addr;
    socklen_t out_addrlen = (socklen_t) sizeof (ip4_addr);
    //  0 is not a valid port.
    if (!ip4_addr.sin_port) {
        errno = EINVAL;
        return -1;
    }
    //  * resolves to INADDR_ANY.
    if (iface.compare("*") == 0) {
        ip4_addr.sin_addr.s_addr = htonl (INADDR_ANY);
        zmq_assert (out_addrlen <= (socklen_t) sizeof (*addr_));
        memcpy (addr_, out_addr, out_addrlen);
        *addr_len_ = out_addrlen;
        return 0;
    }
    //  Try to resolve the string as a NIC name.
    int rc = resolve_nic_name (&ip4_addr.sin_addr, iface.c_str());
    if (rc != 0 && errno != ENODEV)
        return rc;
    if (rc == 0) {
        zmq_assert (out_addrlen <= (socklen_t) sizeof (*addr_));
        memcpy (addr_, out_addr, out_addrlen);
        *addr_len_ = out_addrlen;
        return 0;
    }
    //  There's no such interface name. Assume literal address.
#if defined ZMQ_HAVE_OPENVMS && defined __ia64
    __addrinfo64 *res = NULL;
    __addrinfo64 req;
#else
    addrinfo *res = NULL;
    addrinfo req;
#endif
    memset (&req, 0, sizeof (req));
    //  We only support IPv4 addresses for now.
    req.ai_family = AF_INET;
    //  Arbitrary, not used in the output, but avoids duplicate results.
    req.ai_socktype = SOCK_STREAM;
    //  Restrict hostname/service to literals to avoid any DNS lookups or
    //  service-name irregularity due to indeterminate socktype.
    req.ai_flags = AI_PASSIVE | AI_NUMERICHOST | AI_NUMERICSERV;
    //  Resolve the literal address. Some of the error info is lost in case
    //  of error, however, there's no way to report EAI errors via errno.
    rc = getaddrinfo (iface.c_str(), service.c_str(), &req, &res);
    if (rc) {
        errno = ENODEV;
        return -1;
    }
    //  Use the first result.
    zmq_assert ((size_t) (res->ai_addrlen) <= sizeof (*addr_));
    memcpy (addr_, res->ai_addr, res->ai_addrlen);
    *addr_len_ = (socklen_t) res->ai_addrlen;
    //  Cleanup getaddrinfo after copying the possibly referenced result.
    if (res)
        freeaddrinfo (res);
    return 0;
}
int zmq::resolve_local_path (sockaddr_storage * addr_, socklen_t * addr_len_, const char * pathname_)
Definition at line 327 of file ip.cpp.
References EPROTONOSUPPORT.
Referenced by zmq::tcp_listener_t::set_address(), and zmq::tcp_connecter_t::set_address().
{
#if defined ZMQ_HAVE_WINDOWS || defined ZMQ_HAVE_OPENVMS
    errno = EPROTONOSUPPORT;
    return -1;
#else
    sockaddr_un *un = (sockaddr_un*) addr_;
    if (strlen (path_) >= sizeof (un->sun_path))
    {
        errno = ENAMETOOLONG;
        return -1;
    }
    strcpy (un->sun_path, path_);
    un->sun_family = AF_UNIX;
    *addr_len_ = sizeof (sockaddr_un);
    return 0;
#endif
}