libzmq: perf/remote_lat.cpp File Reference
remote_lat.cpp File Reference
#include "../include/zmq.h"
#include "../include/zmq_utils.h"
#include <stdio.h>
#include <stdlib.h>
#include <string.h>
Functions
int main (int argc, char *argv[])
Function Documentation
int main (int argc, char * argv[])
Definition at line 27 of file remote_lat.cpp.
References message_size, roundtrip_count, zmq_close(), zmq_connect(), zmq_init(), zmq_msg_close(), zmq_msg_data(), zmq_msg_init_size(), zmq_msg_size(), zmq_recvmsg(), ZMQ_REQ, zmq_sendmsg(), zmq_socket(), zmq_stopwatch_start(), zmq_stopwatch_stop(), zmq_strerror(), and zmq_term().