libzmq: tests/test_timeo.cpp File Reference
test_timeo.cpp File Reference
#include <assert.h>
#include <string.h>
#include <pthread.h>
#include "../include/zmq.h"
#include "../include/zmq_utils.h"
Functions
int main (int argc, char *argv[])
void * worker (void *ctx)
Function Documentation
int main (int argc, char * argv[])
Definition at line 46 of file test_timeo.cpp.
References worker(), zmq_bind(), zmq_close(), zmq_connect(), ZMQ_DONTWAIT, zmq_errno(), zmq_init(), ZMQ_PULL, ZMQ_PUSH, ZMQ_RCVTIMEO, zmq_recv(), zmq_send(), zmq_setsockopt(), ZMQ_SNDTIMEO, zmq_socket(), zmq_stopwatch_start(), zmq_stopwatch_stop(), and zmq_term().
void* worker (void * ctx)
Definition at line 30 of file test_timeo.cpp.
References zmq_close(), zmq_connect(), ZMQ_PUSH, zmq_sleep(), and zmq_socket().
Referenced by main().