libzmq: tests/test_shutdown_stress.cpp File Reference
test_shutdown_stress.cpp File Reference
#include "../include/zmq.h"
#include <assert.h>
#include <pthread.h>
#include <stddef.h>
Defines
#define THREAD_COUNT 10
Functions
int main (int argc, char *argv[])
static void * worker (void *s)
Define Documentation
#define THREAD_COUNT 10
Definition at line 26 of file test_shutdown_stress.cpp.
Referenced by main().
Function Documentation
int main (int argc, char * argv[])
Definition at line 45 of file test_shutdown_stress.cpp.
References THREAD_COUNT, worker(), zmq_bind(), zmq_close(), zmq_init(), ZMQ_PUB, zmq_socket(), ZMQ_SUB, and zmq_term().
static void* worker (void * s) [static]
Definition at line 30 of file test_shutdown_stress.cpp.
References zmq_close(), and zmq_connect().
Referenced by main().