libzmq: tests/testutil.hpp File Reference
testutil.hpp File Reference
#include <assert.h>
#include <string.h>
#include "../include/zmq.h"
Functions
void bounce (void *sb, void *sc)
Function Documentation
void bounce (void * sb, void * sc) [inline]
Definition at line 29 of file testutil.hpp.
References zmq_getsockopt(), ZMQ_RCVMORE, zmq_recv(), zmq_send(), and ZMQ_SNDMORE.
Referenced by main().