libzmq: tests/test_pair_tcp.cpp File Reference
test_pair_tcp.cpp File Reference
#include <assert.h>
#include "testutil.hpp"
Functions
int main (int argc, char *argv[])
Function Documentation
int main (int argc, char * argv[])
Definition at line 24 of file test_pair_tcp.cpp.
References bounce(), zmq_bind(), zmq_close(), zmq_connect(), zmq_init(), ZMQ_PAIR, zmq_socket(), and zmq_term().