libzmq: tests/test_msg_flags.cpp File Reference
test_msg_flags.cpp File Reference
#include <assert.h>
#include <string.h>
#include "../include/zmq.h"
Functions
int main (int argc, char *argv[])
Function Documentation
int main (int argc, char * argv[])
Definition at line 25 of file test_msg_flags.cpp.
References zmq_bind(), zmq_close(), zmq_connect(), zmq_getmsgopt(), zmq_init(), ZMQ_MORE, zmq_msg_init(), zmq_recvmsg(), zmq_send(), ZMQ_SNDMORE, zmq_socket(), zmq_term(), ZMQ_XREP, and ZMQ_XREQ.