libzmq: libzmq/doxygen/tests/test_sub_forward.cpp File Reference
test_sub_forward.cpp File Reference
#include <assert.h>
#include "../include/zmq.h"
#include "../include/zmq_utils.h"
Functions
int main (int argc, char *argv[])
Function Documentation
int main (int argc, char * argv[])
Definition at line 26 of file test_sub_forward.cpp.
References zmq_bind(), zmq_close(), zmq_connect(), zmq_init(), ZMQ_PUB, zmq_recv(), zmq_send(), zmq_setsockopt(), zmq_sleep(), zmq_socket(), ZMQ_SUB, ZMQ_SUBSCRIBE, zmq_term(), ZMQ_XPUB, and ZMQ_XSUB.