libzmq: /home/travlr/src/libzmq/src/zmq.cpp File Reference
zmq.cpp File Reference
#include "platform.hpp"
#include <string.h>
#include <errno.h>
#include <stdlib.h>
#include <new>
#include "socket_base.hpp"
#include "stdint.hpp"
#include "config.hpp"
#include "likely.hpp"
#include "clock.hpp"
#include "ctx.hpp"
#include "err.hpp"
#include "msg.hpp"
#include "fd.hpp"
#include <unistd.h>
Typedefs
typedef char check_msg_t_size [sizeof(zmq::msg_t)==sizeof(zmq_msg_t)?1:-1]
Functions
int zmq_bind (void *s_, const char *addr_)
int zmq_close (void *s_)
int zmq_connect (void *s_, const char *addr_)
int zmq_errno ()
int zmq_getsockopt (void *s_, int option_, void *optval_, size_t *optvallen_)
void * zmq_init (int io_threads_)
int zmq_msg_close (zmq_msg_t *msg_)
int zmq_msg_copy (zmq_msg_t *dest_, zmq_msg_t *src_)
void * zmq_msg_data (zmq_msg_t *msg_)
int zmq_msg_init (zmq_msg_t *msg_)
int zmq_msg_init_data (zmq_msg_t *msg_, void *data_, size_t size_, zmq_free_fn *ffn_, void *hint_)
int zmq_msg_init_size (zmq_msg_t *msg_, size_t size_)
int zmq_msg_move (zmq_msg_t *dest_, zmq_msg_t *src_)
size_t zmq_msg_size (zmq_msg_t *msg_)
int zmq_poll (zmq_pollitem_t *items_, int nitems_, long timeout_)
int zmq_recv (void *s_, void *buf_, size_t len_, int flags_)
int zmq_recvmsg (void *s_, zmq_msg_t *msg_, int flags_)
int zmq_send (void *s_, const void *buf_, size_t len_, int flags_)
int zmq_sendmsg (void *s_, zmq_msg_t *msg_, int flags_)
int zmq_setsockopt (void *s_, int option_, const void *optval_, size_t optvallen_)
void * zmq_socket (void *ctx_, int type_)
const char * zmq_strerror (int errnum_)
int zmq_term (void *ctx_)
void zmq_version (int *major_, int *minor_, int *patch_)
Typedef Documentation
typedef char check_msg_t_size[sizeof(zmq::msg_t)==sizeof(zmq_msg_t)?1:-1]
Definition at line 61 of file zmq.cpp.
Function Documentation
int zmq_bind (void * s_, const char * addr_)
Definition at line 193 of file zmq.cpp.
References ENOTSOCK.
Referenced by main().
{
    if (!s_ || !((zmq::socket_base_t*) s_)->check_tag ()) {
        errno = ENOTSOCK;
        return -1;
    }
    return (((zmq::socket_base_t*) s_)->bind (addr_));
}
int zmq_close (void * s_)
Definition at line 162 of file zmq.cpp.
References ENOTSOCK.
Referenced by main(), and worker().
{
    if (!s_ || !((zmq::socket_base_t*) s_)->check_tag ()) {
        errno = ENOTSOCK;
        return -1;
    }
    ((zmq::socket_base_t*) s_)->close ();
    return 0;
}
int zmq_connect (void * s_, const char * addr_)
Definition at line 202 of file zmq.cpp.
References ENOTSOCK.
Referenced by main(), and worker().
{
    if (!s_ || !((zmq::socket_base_t*) s_)->check_tag ()) {
        errno = ENOTSOCK;
        return -1;
    }
    return (((zmq::socket_base_t*) s_)->connect (addr_));
}
int zmq_errno (void)
Definition at line 688 of file zmq.cpp.
{
    return errno;
}
int zmq_getsockopt (void * s_, int option_, void * optval_, size_t * optvallen_)
Definition at line 183 of file zmq.cpp.
References ENOTSOCK.
Referenced by zmq_poll().
{
    if (!s_ || !((zmq::socket_base_t*) s_)->check_tag ()) {
        errno = ENOTSOCK;
        return -1;
    }
    return (((zmq::socket_base_t*) s_)->getsockopt (option_, optval_,
        optvallen_));
}
void* zmq_init (int io_threads_)
Definition at line 75 of file zmq.cpp.
References alloc_assert, and zmq_assert.
Referenced by main().
{
    if (io_threads_ < 0) {
        errno = EINVAL;
        return NULL;
    }
#if defined ZMQ_HAVE_OPENPGM
    //  Init PGM transport. Ensure threading and timer are enabled. Find PGM
    //  protocol ID. Note that if you want to use gettimeofday and sleep for
    //  openPGM timing, set environment variables PGM_TIMER to "GTOD" and
    //  PGM_SLEEP to "USLEEP".
    pgm_error_t *pgm_error = NULL;
    const bool ok = pgm_init (&pgm_error);
    if (ok != TRUE) {
        //  Invalid parameters don't set pgm_error_t
        zmq_assert (pgm_error != NULL);
        if (pgm_error->domain == PGM_ERROR_DOMAIN_TIME && (
              pgm_error->code == PGM_ERROR_FAILED)) {
            //  Failed to access RTC or HPET device.
            pgm_error_free (pgm_error);
            errno = EINVAL;
            return NULL;
        }
        //  PGM_ERROR_DOMAIN_ENGINE: WSAStartup errors or missing WSARecvMsg.
        zmq_assert (false);
    }
#endif
#ifdef ZMQ_HAVE_WINDOWS
    //  Intialise Windows sockets. Note that WSAStartup can be called multiple
    //  times given that WSACleanup will be called for each WSAStartup.
   //  We do this before the ctx constructor since its embedded mailbox_t
   //  object needs Winsock to be up and running.
    WORD version_requested = MAKEWORD (2, 2);
    WSADATA wsa_data;
    int rc = WSAStartup (version_requested, &wsa_data);
    zmq_assert (rc == 0);
    zmq_assert (LOBYTE (wsa_data.wVersion) == 2 &&
        HIBYTE (wsa_data.wVersion) == 2);
#endif
    //  Create 0MQ context.
    zmq::ctx_t *ctx = new (std::nothrow) zmq::ctx_t ((uint32_t) io_threads_);
    alloc_assert (ctx);
    return (void*) ctx;
}
int zmq_msg_close (zmq_msg_t * msg_)
Definition at line 300 of file zmq.cpp.
Referenced by main(), worker(), zmq_recv(), and zmq_send().
{
    return ((zmq::msg_t*) msg_)->close ();
}
int zmq_msg_copy (zmq_msg_t * dest_, zmq_msg_t * src_)
Definition at line 310 of file zmq.cpp.
{
    return ((zmq::msg_t*) dest_)->copy (*(zmq::msg_t*) src_);
}
void* zmq_msg_data (zmq_msg_t * msg_)
Definition at line 315 of file zmq.cpp.
Referenced by main(), worker(), zmq_recv(), and zmq_send().
{
    return ((zmq::msg_t*) msg_)->data ();
}
int zmq_msg_init (zmq_msg_t * msg_)
Definition at line 284 of file zmq.cpp.
Referenced by main(), worker(), and zmq_recv().
{
    return ((zmq::msg_t*) msg_)->init ();
}
int zmq_msg_init_data (zmq_msg_t * msg_, void * data_, size_t size_, zmq_free_fn * ffn_, void * hint_)
Definition at line 294 of file zmq.cpp.
{
    return ((zmq::msg_t*) msg_)->init_data (data_, size_, ffn_, hint_);
}
int zmq_msg_init_size (zmq_msg_t * msg_, size_t size_)
Definition at line 289 of file zmq.cpp.
Referenced by main(), worker(), and zmq_send().
{
    return ((zmq::msg_t*) msg_)->init_size (size_);
}
int zmq_msg_move (zmq_msg_t * dest_, zmq_msg_t * src_)
Definition at line 305 of file zmq.cpp.
{
    return ((zmq::msg_t*) dest_)->move (*(zmq::msg_t*) src_);
}
size_t zmq_msg_size (zmq_msg_t * msg_)
Definition at line 320 of file zmq.cpp.
Referenced by main(), zmq_recvmsg(), and zmq_sendmsg().
{
    return ((zmq::msg_t*) msg_)->size ();
}
int zmq_poll (zmq_pollitem_t * items_, int nitems_, long timeout_)
Definition at line 339 of file zmq.cpp.
References alloc_assert, ENOTSUP, errno_assert, zmq_pollitem_t::events, zmq_pollitem_t::fd, zmq::clock_t::now_ms(), zmq_pollitem_t::revents, unlikely, zmq_assert, ZMQ_EVENTS, ZMQ_FD, zmq_getsockopt(), ZMQ_POLLERR, ZMQ_POLLIN, and ZMQ_POLLOUT.
{
#if defined ZMQ_POLL_BASED_ON_POLL
    if (unlikely (nitems_ < 0)) {
        errno = EINVAL;
        return -1;
    }
    if (unlikely (nitems_ == 0)) {
        if (timeout_ == 0)
            return 0;
#if defined ZMQ_HAVE_WINDOWS
        Sleep (timeout_ > 0 ? timeout_ : INFINITE);
        return 0;
#else
        return usleep (timeout_ * 1000);
#endif
    }
    if (!items_) {
        errno = EFAULT;
        return -1;
    }
    zmq::clock_t clock;
    uint64_t now = 0;
    uint64_t end = 0;
    pollfd *pollfds = (pollfd*) malloc (nitems_ * sizeof (pollfd));
    alloc_assert (pollfds);
    //  Build pollset for poll () system call.
    for (int i = 0; i != nitems_; i++) {
        //  If the poll item is a 0MQ socket, we poll on the file descriptor
        //  retrieved by the ZMQ_FD socket option.
        if (items_ [i].socket) {
            size_t zmq_fd_size = sizeof (zmq::fd_t);
            if (zmq_getsockopt (items_ [i].socket, ZMQ_FD, &pollfds [i].fd,
                &zmq_fd_size) == -1) {
                free (pollfds);
                return -1;
            }
            pollfds [i].events = items_ [i].events ? POLLIN : 0;
        }
        //  Else, the poll item is a raw file descriptor. Just convert the
        //  events to normal POLLIN/POLLOUT for poll ().
        else {
            pollfds [i].fd = items_ [i].fd;
            pollfds [i].events =
                (items_ [i].events & ZMQ_POLLIN ? POLLIN : 0) |
                (items_ [i].events & ZMQ_POLLOUT ? POLLOUT : 0);
        }
    }
    bool first_pass = true;
    int nevents = 0;
    while (true) {
         //  Compute the timeout for the subsequent poll.
         int timeout;
         if (first_pass)
             timeout = 0;
         else if (timeout_ < 0)
             timeout = -1;
         else
             timeout = end - now;
        //  Wait for events.
        while (true) {
            int rc = poll (pollfds, nitems_, timeout);
            if (rc == -1 && errno == EINTR) {
                free (pollfds);
                return -1;
            }
            errno_assert (rc >= 0);
            break;
        }
        //  Check for the events.
        for (int i = 0; i != nitems_; i++) {
            items_ [i].revents = 0;
            //  The poll item is a 0MQ socket. Retrieve pending events
            //  using the ZMQ_EVENTS socket option.
            if (items_ [i].socket) {
                size_t zmq_events_size = sizeof (uint32_t);
                uint32_t zmq_events;
                if (zmq_getsockopt (items_ [i].socket, ZMQ_EVENTS, &zmq_events,
                    &zmq_events_size) == -1) {
                    free (pollfds);
                    return -1;
                }
                if ((items_ [i].events & ZMQ_POLLOUT) &&
                      (zmq_events & ZMQ_POLLOUT))
                    items_ [i].revents |= ZMQ_POLLOUT;
                if ((items_ [i].events & ZMQ_POLLIN) &&
                      (zmq_events & ZMQ_POLLIN))
                    items_ [i].revents |= ZMQ_POLLIN;
            }
            //  Else, the poll item is a raw file descriptor, simply convert
            //  the events to zmq_pollitem_t-style format.
            else {
                if (pollfds [i].revents & POLLIN)
                    items_ [i].revents |= ZMQ_POLLIN;
                if (pollfds [i].revents & POLLOUT)
                    items_ [i].revents |= ZMQ_POLLOUT;
                if (pollfds [i].revents & ~(POLLIN | POLLOUT))
                    items_ [i].revents |= ZMQ_POLLERR;
            }
            if (items_ [i].revents)
                nevents++;
        }
        //  If timout is zero, exit immediately whether there are events or not.
        if (timeout_ == 0)
            break;
        //  If there are events to return, we can exit immediately.
        if (nevents)
            break;
        //  At this point we are meant to wait for events but there are none.
        //  If timeout is infinite we can just loop until we get some events.
        if (timeout_ < 0) {
            if (first_pass)
                first_pass = false;
            continue;
        }
        //  The timeout is finite and there are no events. In the first pass
        //  we get a timestamp of when the polling have begun. (We assume that
        //  first pass have taken negligible time). We also compute the time
        //  when the polling should time out.
        if (first_pass) {
            now = clock.now_ms ();
            end = now + timeout_;
            if (now == end)
                break;
            first_pass = false;
            continue;
        }
        //  Find out whether timeout have expired.
        now = clock.now_ms ();
        if (now >= end)
            break;
    }
    free (pollfds);
    return nevents;
#elif defined ZMQ_POLL_BASED_ON_SELECT
    if (unlikely (nitems_ < 0)) {
        errno = EINVAL;
        return -1;
    }
    if (unlikely (nitems_ == 0)) {
        if (timeout_ == 0)
            return 0;
#if defined ZMQ_HAVE_WINDOWS
        Sleep (timeout_ > 0 ? timeout_ : INFINITE);
        return 0;
#else
        return usleep (timeout_ * 1000);
#endif
    }
    if (!items_) {
        errno = EFAULT;
        return -1;
    }
    zmq::clock_t clock;
    uint64_t now = 0;
    uint64_t end = 0;
    //  Ensure we do not attempt to select () on more than FD_SETSIZE
    //  file descriptors.
    zmq_assert (nitems_ <= FD_SETSIZE);
    fd_set pollset_in;
    FD_ZERO (&pollset_in);
    fd_set pollset_out;
    FD_ZERO (&pollset_out);
    fd_set pollset_err;
    FD_ZERO (&pollset_err);
    zmq::fd_t maxfd = 0;
    //  Build the fd_sets for passing to select ().
    for (int i = 0; i != nitems_; i++) {
        //  If the poll item is a 0MQ socket we are interested in input on the
        //  notification file descriptor retrieved by the ZMQ_FD socket option.
        if (items_ [i].socket) {
            size_t zmq_fd_size = sizeof (zmq::fd_t);
            zmq::fd_t notify_fd;
            if (zmq_getsockopt (items_ [i].socket, ZMQ_FD, &notify_fd,
                &zmq_fd_size) == -1)
                return -1;
            if (items_ [i].events) {
                FD_SET (notify_fd, &pollset_in);
                if (maxfd < notify_fd)
                    maxfd = notify_fd;
            }
        }
        //  Else, the poll item is a raw file descriptor. Convert the poll item
        //  events to the appropriate fd_sets.
        else {
            if (items_ [i].events & ZMQ_POLLIN)
                FD_SET (items_ [i].fd, &pollset_in);
            if (items_ [i].events & ZMQ_POLLOUT)
                FD_SET (items_ [i].fd, &pollset_out);
            if (items_ [i].events & ZMQ_POLLERR)
                FD_SET (items_ [i].fd, &pollset_err);
            if (maxfd < items_ [i].fd)
                maxfd = items_ [i].fd;
        }
    }
    bool first_pass = true;
    int nevents = 0;
    fd_set inset, outset, errset;
    while (true) {
        //  Compute the timeout for the subsequent poll.
        timeval timeout;
        timeval *ptimeout;
        if (first_pass) {
            timeout.tv_sec = 0;
            timeout.tv_usec = 0;
            ptimeout = &timeout;
        }
        else if (timeout_ < 0)
            ptimeout = NULL;
        else {
            timeout.tv_sec = (long) ((end - now) / 1000);
            timeout.tv_usec = (long) ((end - now) % 1000 * 1000);
            ptimeout = &timeout;
        }
        //  Wait for events. Ignore interrupts if there's infinite timeout.
        while (true) {
            memcpy (&inset, &pollset_in, sizeof (fd_set));
            memcpy (&outset, &pollset_out, sizeof (fd_set));
            memcpy (&errset, &pollset_err, sizeof (fd_set));
#if defined ZMQ_HAVE_WINDOWS
            int rc = select (0, &inset, &outset, &errset, ptimeout);
            wsa_assert (rc != SOCKET_ERROR);
#else
            int rc = select (maxfd + 1, &inset, &outset, &errset, ptimeout);
            if (rc == -1 && errno == EINTR)
                return -1;
            errno_assert (rc >= 0);
#endif
            break;
        }
        //  Check for the events.
        for (int i = 0; i != nitems_; i++) {
            items_ [i].revents = 0;
            //  The poll item is a 0MQ socket. Retrieve pending events
            //  using the ZMQ_EVENTS socket option.
            if (items_ [i].socket) {
                size_t zmq_events_size = sizeof (uint32_t);
                uint32_t zmq_events;
                if (zmq_getsockopt (items_ [i].socket, ZMQ_EVENTS, &zmq_events,
                      &zmq_events_size) == -1)
                    return -1;
                if ((items_ [i].events & ZMQ_POLLOUT) &&
                      (zmq_events & ZMQ_POLLOUT))
                    items_ [i].revents |= ZMQ_POLLOUT;
                if ((items_ [i].events & ZMQ_POLLIN) &&
                      (zmq_events & ZMQ_POLLIN))
                    items_ [i].revents |= ZMQ_POLLIN;
            }
            //  Else, the poll item is a raw file descriptor, simply convert
            //  the events to zmq_pollitem_t-style format.
            else {
                if (FD_ISSET (items_ [i].fd, &inset))
                    items_ [i].revents |= ZMQ_POLLIN;
                if (FD_ISSET (items_ [i].fd, &outset))
                    items_ [i].revents |= ZMQ_POLLOUT;
                if (FD_ISSET (items_ [i].fd, &errset))
                    items_ [i].revents |= ZMQ_POLLERR;
            }
            if (items_ [i].revents)
                nevents++;
        }
        //  If timout is zero, exit immediately whether there are events or not.
        if (timeout_ == 0)
            break;
        //  If there are events to return, we can exit immediately.
        if (nevents)
            break;
        //  At this point we are meant to wait for events but there are none.
        //  If timeout is infinite we can just loop until we get some events.
        if (timeout_ < 0) {
            if (first_pass)
                first_pass = false;
            continue;
        }
        //  The timeout is finite and there are no events. In the first pass
        //  we get a timestamp of when the polling have begun. (We assume that
        //  first pass have taken negligible time). We also compute the time
        //  when the polling should time out.
        if (first_pass) {
            now = clock.now_ms ();
            end = now + timeout_;
            if (now == end)
                break;
            first_pass = false;
            continue;
        }
        //  Find out whether timeout have expired.
        now = clock.now_ms ();
        if (now >= end)
            break;
    }
    return nevents;
#else
    //  Exotic platforms that support neither poll() nor select().
    errno = ENOTSUP;
    return -1;
#endif
}
int zmq_recv (void * s_, void * buf_, size_t len_, int flags_)
Definition at line 233 of file zmq.cpp.
References errno_assert, unlikely, zmq_msg_close(), zmq_msg_data(), zmq_msg_init(), and zmq_recvmsg().
Referenced by bounce(), and main().
{
    zmq_msg_t msg;
    int rc = zmq_msg_init (&msg);
    errno_assert (rc == 0);
    int nbytes = zmq_recvmsg (s_, &msg, flags_);
    if (unlikely (nbytes < 0)) {
        int err = errno;
        rc = zmq_msg_close (&msg);
        errno_assert (rc == 0);
        errno = err;
        return -1;
    }
    //  At the moment an oversized message is silently truncated.
    //  TODO: Build in a notification mechanism to report the overflows.
    size_t to_copy = size_t (nbytes) < len_ ? size_t (nbytes) : len_;
    memcpy (buf_, zmq_msg_data (&msg), to_copy);
    rc = zmq_msg_close (&msg);
    errno_assert (rc == 0);
    return nbytes;
}
int zmq_recvmsg (void * s_, zmq_msg_t * msg_, int flags_)
Definition at line 272 of file zmq.cpp.
References ENOTSOCK, unlikely, and zmq_msg_size().
Referenced by main(), worker(), and zmq_recv().
{
    if (!s_ || !((zmq::socket_base_t*) s_)->check_tag ()) {
        errno = ENOTSOCK;
        return -1;
    }
    int rc = (((zmq::socket_base_t*) s_)->recv ((zmq::msg_t*) msg_, flags_));
    if (unlikely (rc < 0))
        return -1;
    return (int) zmq_msg_size (msg_);
}
int zmq_send (void * s_, const void * buf_, size_t len_, int flags_)
Definition at line 211 of file zmq.cpp.
References errno_assert, unlikely, zmq_msg_close(), zmq_msg_data(), zmq_msg_init_size(), and zmq_sendmsg().
Referenced by bounce(), and main().
{
    zmq_msg_t msg;
    int rc = zmq_msg_init_size (&msg, len_);
    if (rc != 0)
        return -1;
    memcpy (zmq_msg_data (&msg), buf_, len_);
    rc = zmq_sendmsg (s_, &msg, flags_);
    if (unlikely (rc < 0)) {
        int err = errno;
        int rc2 = zmq_msg_close (&msg);
        errno_assert (rc2 == 0);
        errno = err;
        return -1;
    }
    //  Note the optimisation here. We don't close the msg object as it is
    //  empty anyway. This may change when implementation of zmq_msg_t changes.
    return rc;
}
int zmq_sendmsg (void * s_, zmq_msg_t * msg_, int flags_)
Definition at line 259 of file zmq.cpp.
References ENOTSOCK, unlikely, and zmq_msg_size().
Referenced by main(), worker(), and zmq_send().
{
    if (!s_ || !((zmq::socket_base_t*) s_)->check_tag ()) {
        errno = ENOTSOCK;
        return -1;
    }
    int sz = (int) zmq_msg_size (msg_);
    int rc = (((zmq::socket_base_t*) s_)->send ((zmq::msg_t*) msg_, flags_));
    if (unlikely (rc < 0))
        return -1;
    return sz;
}
int zmq_setsockopt (void * s_, int option_, const void * optval_, size_t optvallen_)
Definition at line 172 of file zmq.cpp.
References ENOTSOCK.
Referenced by main().
{
    if (!s_ || !((zmq::socket_base_t*) s_)->check_tag ()) {
        errno = ENOTSOCK;
        return -1;
    }
    return (((zmq::socket_base_t*) s_)->setsockopt (option_, optval_,
        optvallen_));
}
void* zmq_socket (void * ctx_, int type_)
Definition at line 153 of file zmq.cpp.
Referenced by main(), and worker().
{
    if (!ctx_ || !((zmq::ctx_t*) ctx_)->check_tag ()) {
        errno = EFAULT;
        return NULL;
    }
    return (void*) (((zmq::ctx_t*) ctx_)->create_socket (type_));
}
const char* zmq_strerror (int errnum_)
Definition at line 70 of file zmq.cpp.
References zmq::errno_to_string().
Referenced by main(), and worker().
{
    return zmq::errno_to_string (errnum_);
}
int zmq_term (void * ctx_)
Definition at line 127 of file zmq.cpp.
References zmq_assert.
Referenced by main().
{
    if (!ctx_ || !((zmq::ctx_t*) ctx_)->check_tag ()) {
        errno = EFAULT;
        return -1;
    }
    int rc = ((zmq::ctx_t*) ctx_)->terminate ();
    int en = errno;
#ifdef ZMQ_HAVE_WINDOWS
    //  On Windows, uninitialise socket layer.
    rc = WSACleanup ();
    wsa_assert (rc != SOCKET_ERROR);
#endif
#if defined ZMQ_HAVE_OPENPGM
    //  Shut down the OpenPGM library.
    if (pgm_shutdown () != TRUE)
        zmq_assert (false);
#endif
    errno = en;
    return rc;
}
void zmq_version (int * major_, int * minor_, int * patch_)
Definition at line 63 of file zmq.cpp.
References ZMQ_VERSION_MAJOR, ZMQ_VERSION_MINOR, and ZMQ_VERSION_PATCH.
{
    *major_ = ZMQ_VERSION_MAJOR;
    *minor_ = ZMQ_VERSION_MINOR;
    *patch_ = ZMQ_VERSION_PATCH;
}