libzmq: include/zmq_utils.h File Reference
zmq_utils.h File Reference
Defines
#define ZMQ_EXPORT
Functions
ZMQ_EXPORT void zmq_sleep (int seconds_)
ZMQ_EXPORT void * zmq_stopwatch_start (void)
ZMQ_EXPORT unsigned long zmq_stopwatch_stop (void *watch_)
Define Documentation
#define ZMQ_EXPORT
Definition at line 41 of file zmq_utils.h.
Function Documentation
ZMQ_EXPORT void zmq_sleep (int seconds_)
Definition at line 37 of file zmq_utils.cpp.
Referenced by main(), and worker().
ZMQ_EXPORT void* zmq_stopwatch_start (void)
Definition at line 46 of file zmq_utils.cpp.
References alloc_assert, and zmq::clock_t::now_us().
Referenced by main().
ZMQ_EXPORT unsigned long zmq_stopwatch_stop (void * watch_)
Definition at line 54 of file zmq_utils.cpp.
References zmq::clock_t::now_us().
Referenced by main().