libzmq: src/zmq_utils.cpp File Reference
zmq_utils.cpp File Reference
#include "platform.hpp"
#include "../include/zmq_utils.h"
#include <stdlib.h>
#include "stdint.hpp"
#include "clock.hpp"
#include "err.hpp"
#include <unistd.h>
Functions
void zmq_sleep (int seconds_)
void * zmq_stopwatch_start ()
unsigned long zmq_stopwatch_stop (void *watch_)
Function Documentation
void zmq_sleep (int seconds_)
Definition at line 37 of file zmq_utils.cpp.
Referenced by main(), and worker().
void* zmq_stopwatch_start (void)
Definition at line 46 of file zmq_utils.cpp.
References alloc_assert, and zmq::clock_t::now_us().
Referenced by main().
unsigned long zmq_stopwatch_stop (void * watch_)
Definition at line 54 of file zmq_utils.cpp.
References zmq::clock_t::now_us().
Referenced by main().